### ISSUE TITLE
Sync validation API

### ISSUE THREAD

**Issue by jods4** [aurelia/validation#111]
This suggestion is dependent on changes mentioned in #110. 

I think that `.validate()` should return a `boolean` synchronously when it can. _Or_ we could add a new api such as `.validateSync()` or `.validate(/*sync: */ true)` for that.

This is because a typical use case is to check if the model is valid before sending it to the server (save or whatever). And with the promise our code looks like this (pardon the ES7):
```javascript
if (await this.validation.validate()) {
 /* do the save */ 
}
```

There is a tricky part to handle here, which is that the user can still interact with the application between `.validate()` and `/* do the save */`. So it could submit twice, change the state of the model, etc. I know the window of time is going to be very short, but this is not robust code. And my mom loves to double-click on buttons, don't ask me why.

I think that the developper knows if he's using server-side logic or custom validation with callbacks or not. So he might know that his validation logic can be synchronous (and it often can). 
In those cases the code above (without `await`) is robust (and marginally more efficient).

**Comment by jods4** [comment]
@EisenbergEffect and co, I would like feedback on this:

I have been thinking about refactoring approaches for aurelia-validation lately.

I do believe that having synchronous paths where possible is important and a good thing.

But there is one roadblock on the way: locales.

Currently one configures locale by passing a locale string to the validation configuration. Because one never really knows when the locale is loaded, it means that any validation call is potentially async, waiting on the locale loading to complete. 

I don't think this is a good thing. (In fact -- going on a tangent here -- there are serveral async things that happen inside aurelia-validation, which you cannot know when they complete. The lack of a "completion" api is certainly not a good design and in my experience it makes some tests painful. I recently had to tweak `setTimeout` durations to make tests pass in IE and this was no fun and certainly fragile code.)

Anyway, moving on: what do you think would be an acceptable alternative design for loading locales? The goal is that validations API are not dependent upon locales loading.

My current idea is:
- the business of handling locales should be externalized in aurelia anyway, probably `aurelia-i18n`.
- `aurelia-validation` should be configured with an existing "locale" object, whatever we define. Loading this object might be async but is out of the aurelia scope. `.use({ locale: loadedLocaleObject })` should accept an already loaded object and nothing depends asynchronously on it.

What do you think?

**Comment by PWKad** [comment]
I think this may be a valid consideration from the locale perspective but I'll re-open as validation/i18n issue
