### ISSUE TITLE
ValidationResultProperty (get name of field)

### ISSUE THREAD

**Issue by flieks** [aurelia/validation#118]
Hi,

I get the ValidationResultProperties in the catch() and i can show the message but how do i get the name of the ValidationResultProperty (like "password" or "email") ?

Greetings
Felix

**Comment by nomack84** [comment]
Did you check this https://github.com/aurelia/validation/blob/master/doc/Intro.md#validationresult

**Comment by PWKad** [comment]
As @nomack84 mentioned this is available in the list of properties that are returned.  It is the key of the value that contains the message property.
