### ISSUE TITLE
Discussion: Should resources be loaded async?

### ISSUE THREAD

**Issue by janvanderhaegen** [aurelia/validation#125]
Currently the resources are distributed with the package in separate files, then the chosen resource is loaded on demand.

This leads to a rippling effect of using promises in the entire application (see #110 and others), thus increasing the overall complexity of the code, build process and deployment.

The alternative is to bundle the resources in a single file. This might lead to increased merging conflicts but also a larger download and memory footprint, since end users will be loading a lot resources they'll never end up using.

Any thoughts?

**Comment by JeroenVinke** [comment]
Because the resources import the Utilities class, I think we have to decide between bundling everything, or bundling nothing. If we just bundle the validation files and not the resource files, the resource files can't find the utilities class after build.

**Comment by janvanderhaegen** [comment]
Ouch... Mkay.

We can refactor the dependency on utilities though, or at worst case add a very little repetition (the 'getvalue' method) to every resource file...

**Comment by mbroadst** [comment]
I don't agree with that, you can pass in a utilities object to those methods. Resources seem mostly like translation files to me no? I should only have to incur as much of an overhead as I sign up for when the application is started, right?

**Comment by nomack84** [comment]
From my experience with other frameworks, the translation files always are flat files with just text and placeholders when needed. I think having our resources files depending on a specific object is wrong and is the reason we are facing the current issue. I think we better refactor the resources to `json` files and substitute the Utilities for placeholders and move that logic to the current code. That way we can decouple the resources from the code, which in my opinion is how should be. I think this is not so hard to do and the refactor won't be so complex. 
After that we can simply include in the build the resources folder and load the translation files async as we currently do.
To me this will be the easier path...

**Comment by JeroenVinke** [comment]
There must be a reason for choosing javascript over standard .json files using the i18next notation (https://github.com/i18next/i18next#usage). 

It would be good to know which use cases are made possible by using javascript instead of json files.

**Comment by nomack84** [comment]
@JeroenVinke in the example you cited says: 
>  // given loaded and merged dictionaries in i18next.js to:

To me this implies they load the translations using from `json`, that's simply the common behavior. As I said, having the translation files depending on utilities is a mistake, until proven otherwise. @janvanderhaegen Can you help us here, is there any reason for doing this that we are not seeing ? Can we refactor this as I'm suggesting?

**Comment by mbroadst** [comment]
To be honest I'm not really sure why i18n is even a consideration for the aurelia-validation project itself. i18n should be handled on an entire app basis, and this plugin should leave the translations up to whatever the app is using for i18n. We have [this](https://github.com/aurelia/i18n) now, so all this plugin should be doing is providing some default translation files that the i18n project can use right?

**Comment by EisenbergEffect** [comment]
@janvanderhaegen I agree with @mbroadst The validation plugin should defer as much as possible to the i18n plugin...or should provide some "interface" that an i18n service could implement to support the validation library.

**Comment by mbroadst** [comment]
Not trying to come off so strong here, but it seems to me like a good plan moving forward is to completely disable/remove the resources (translations) for the moment, while the plugin is refactored to e.g. reduce overuse of promises, fix issues with composition, etc. Aurelia is still pre-beta and translations are generally sort of a "polish" step, and certainly a bit of a distraction from foundational work right now. Thoughts?

**Comment by nomack84** [comment]
@mbroadst I think that is just delay the inevitable. Resource translation is a vital feature, we should agree on how implement it from the biggining as it's part of the core features.

**Comment by janvanderhaegen** [comment]
The validation resources needed the utilities to get a particular 'value' from the treshhold. For example:
```
ensure('orderTotal').isLessThen(10000);
ensure('orderTotal').isLessThen( () => customer.maximumCredit);
```
The 'value' that is eventually used in the translation, could be a static value or a function, hence the need for the utilities to 'get the actual value'.

I think the decision was made not to use aurelia-I18N because it didn't support that scenarios at the time, and was not yet a part of the official aurelia repo.

Now that it is, I suggest we refactor the translation mechanism to the I18N plugin and add support to it, if needed, to turn a function into the resulting value.

Does it still makes sense to distribute translations with the validation library itself? Honestly, what's the alternative? As @nomack84 typed while I'm typing this very message: is it feasible to not have intrinsic translations as part of the validation library? Would that not be the worst developer experience ever?

**Comment by mbroadst** [comment]
@nomack84 well that's just my point: I don't think that translations _should_ be a core feature of aurelia-validation. And I think that the discussion and effort around it right now are slowing down improvements on what actually _are_ the core features (there has been zero discussion on my issue posted about validation on composed elements).

I think it's important to focus on the basic functionality of this plugin, while allowing aurelia-i18n to develop and improve, at which time we can hopefully very easily plug into that system.

**Comment by janvanderhaegen** [comment]
Re; progress: I've been buried in work and personal issues the last couple of weeks, but the sky is clearing up for me and this library is the first thing on my mind, all the time. Hopefully I can prove that to you in the next couple of weeks ;-)

**Comment by PWKad** [comment]
Has anyone been able to come up with a transition plan here to move the resources over to i18next library?  Would be really nice to get this in in the next two weeks to get everything stabilized.  If you have an idea consider posting direct steps that need to be taken and we can loop in @zewa666 to make sure everyone's on board and get this started.

**Comment by mbroadst** [comment]
@PWKad I don't believe any consensus was reached on the whole, however I would like to reiterate that I think the "correct" path forward is to temporarily put translation on the back burner.

Integrating with aurelia-i18n seems to be more of a trivial exercise (wrap everything we want translated in `this.i18n.tr`, ship the translation files and let aurelia-i18n know about the location of them), whereas there are more pressing issues to be dealt with (reduction of promises, for example). Translations are already hindering the process, considering you had to disable a number of tests in the latest release directly related to translation - it's not what this plugin is/should be about. </2cents>

**Comment by JeroenVinke** [comment]
I have tried to implement aurelia-i18n and have made some observations.

Firstly, i18next (used by aurelia-i18n) uses ajax to fetch the translations. This is causing some path resolving issues. If you add aurelia-i18n to aurelia-validation using this config:
```
instance.setup({
      resGetPath : 'resources/__lng__.json',
      lng : ValidationConfig.defaults.getValue('locale'),
      attributes : [],
      getAsync : true,
      sendMissing : false,
      fallbackLng : 'en-US',
      debug : false
    });
```
and if you then install aurelia-validation, the browser will look for the .json file in `localhost:9000/resources/en-US.json` instead of `localhost:9000/jspm_packages/github/aurelia/validation@0.3.1/resources/en-US.json`. i18next allows for an override of the fetching mechanism ([here](https://github.com/i18next/i18next/blob/master/src/i18next.sync.js#L91)). Perhaps aurelia-i18n can override this to use the systemjs loader? I think it would be nice if any aurelia plugin could implement aurelia-i18n.

Secondly, the current setup allows to have a different language per validationgroup. I'm not sure if aurelia-i18n is designed to handle this use-case, because I tried to implement it like this:
```
setting(locale, identifier) {
    return this.i18n
      .setLocale(locale)
      .then(() => this.i18n.tr(`settings.${identifier}`));
  }
```
But it turns out that `.setLocale()` will always fetch the json, and no caching is involved whatsoever so you get a lot of requests for the json file.

Thirdly, dependency injection is rarely used because a `ValidationConfig` instance, which contains the `locale` and other settings,  is passed on to a lot of other classes (such as `ValidationGroup`, `ValidationProperty`, `ValidationRulesCollection`). Because of this we'd have to pass on an instance of the dependency-injection container in order to get the instance of aurelia-i18n or any wrapper around aurelia-i18n.

**Comment by zewa666** [comment]
@JeroenVinke can you create an issue regarding resource loading paths and the possible override in the aurelia-i18n repo? Regarding ajax loading take a look here https://github.com/i18next/i18next/issues/174. Don't think that's part of our plugin but more a question of how you init i18next.

**Comment by JeroenVinke** [comment]
@zewa666 I made the issue [here](https://github.com/aurelia/i18n/issues/17). Perhaps the implementation of the override could also include a caching mechanism?

**Comment by JeroenVinke** [comment]
@PWKad @zewa666 found a solution for using systemjs with aurelia-i18n [here](https://github.com/aurelia/i18n/issues/17#issuecomment-142535593). Unforunately I can't dedicate time to create a PR for the implementation of aurelia-i18n so it would be great if someone else could pick this up

**Comment by jods4** [comment]
I think that:
- i18n mechanism itself is something aurelia needs globally. aurelia-validation should be a consumer like any other and not build its own solution. The i18n code belongs to aurelia-i18n.
- formatting localized strings including parameters is a core feature of i18n. Whatever the solution is, it should be in aurelia-i18n. The current solution based upon functions and the misnamed "threshold" object should go away.
- loading the locale inside aurelia-validation itself is probably an error and it leads to a cascade of async code. Read more about it in my comment here: #111. Shortly: I think loading the locale should be pulled out of aurelia-validation, which should be configured with an already loaded locale.
- with respect to bundling: people should be able to bundle the locales they want/need. Bundling everything certainly is an easy way out to the issues mentioned above. But it can get large quickly for a library that supports many validation rules across many languages.

**Comment by EisenbergEffect** [comment]
All that sounds very reasonable to me. I don't see why the locales couldn't be loaded at startup since aurelia supports async plugin configuration.

**Comment by PWKad** [comment]
Thanks for submitting this / commenting on this.  At this time we are closing this because we have completely re-written and are deprecating the previous feature set.  If you feel this should be re-opened please feel free to review [this blog post](http://blog.durandal.io/2016/05/03/aurelias-new-validation-and-testing-capabilities/) and submit either again on this repository, or on the new [validatejs bridge repository](https://github.com/aurelia/validatejs)

Thanks again!
