### ISSUE TITLE
IE10 Support

### ISSUE THREAD

**Issue by alexmills** [aurelia/validation#128]
Hi guys,

I'm having an issue with Aurelia Validation 0.2.7 when used in IE10, the same issue is also present on http://aurelia.io/validation/ 

The error:
```
TypeError: Unable to get property '_validationMetadata' of undefined or null reference.
```
For me it's referring to this block in `validation-group.js` within the JSPM package at line 27:
``` javascript
if (this.subject.__proto__._validationMetadata) {
   this.subject.__proto__._validationMetadata.setup(this);
}
```
Any ideas as to what this issue could be and why it's limited to IE10? I'm not sure of a fix yet as I'm still going through the code but any help would be very much appreciated.

**Comment by leon-andria** [comment]
Hi guys,
This issue applies on every IE9+.
Do we have a plan to fix this ussie ?

Regards,

**Comment by PWKad** [comment]
@leon-andria @alexmills The aurelia.io/validation site is using older versions of all repositories, can you confirm this on the latest set of releases?

**Comment by alexmills** [comment]
@PWKad can confirm, same issue with latest versions.

**Comment by alexmills** [comment]
@PWKad with all the latest releases 
![screen shot 2015-09-11 at 1 00 24 pm](https://cloud.githubusercontent.com/assets/661414/9807388/32a2bef2-5885-11e5-93dd-4f778efa96e8.png)

**Comment by JoshHarris** [comment]
Experiencing the same thing

**Comment by alexmills** [comment]
@PWKad @JoshHarris since updating to `0.3.0` (along with the latest framework components) the issue is resolved in IE9 and IE10. Nice work!

**Comment by PWKad** [comment]
Thanks @alexmills I'm going to close this for now but if someone runs in to this same issue again please let me know and we can re-open it.
