### ISSUE TITLE
Discussion: Refactor plan

### ISSUE THREAD

**Issue by alvarezmario** [aurelia/validation#129]
I propose to follow these steps during our current refactoring. To keep the history log I think we need a separated PR for every step.

### 
- [x] Change the current folder structure `src/validation/*.js -> src/*.js` and move the plugin configuration code to the main validation class. The `Router` does the same. With this we won't need the `index.js` anymore.
- [ ] Refactor the `i18n`support. Already being discussed in #125 
- [x] Add TS support. This should be the final step and not the first

In #122 & #126 we proposed TS support but I think we need to fix first the first two steps in order to add TS without any issues. Step 1 is easy and @JeroenVinke already did it in #126. I think we need this as a separate PR, as it has nothing to do with TS support. @JeroenVinke can you make a PR with only this?
After that we need to fix the `i18n` support, probably using `aurelia-i18n` because is what makes more sense. 
And at the end when everything is fine, the we add TS support as the final `aurelia-validation` file should be OK. 

Thoughts ?

**Comment by JeroenVinke** [comment]
In the first step it is still necessary to have an index.js to exports all classes. The exports in index.js can be removed when the build process exports a single .js file (aurelia-validation.js). And this can only be done when the resources have been refactored

**Comment by PWKad** [comment]
Has anyone PR'd the main built file yet?  If not and no one has the bandwidth I can add this.

**Comment by PWKad** [comment]
@nomack84 the third point has been met, agreed?

**Comment by nomack84** [comment]
@PWKad Yep :) Only left to refactor the i18n section...

**Comment by EisenbergEffect** [comment]
@PWKad Is this ok to close?
