### ISSUE TITLE
Breaks on numeric values that aren't strings

### ISSUE THREAD

**Issue by Zensavona** [aurelia/validation#136]
I'm getting validation failures on values that have been data-bound to the UI and not edited by the user, which are numbers rather than strings containing numbers. 

Once the user edits one of these data-bound numbers they are converted to strings, but until then, they remain numeric and the validation library rejects them, even if they should pass validation.

E.g. 

![Example](https://cloud.githubusercontent.com/assets/425801/9757718/8402c53e-56e2-11e5-97b8-0709bf6343fb.png)

**Comment by Zensavona** [comment]
ping @EisenbergEffect

**Comment by EisenbergEffect** [comment]
I think this would be handled by having a value converter that handles converting back to numbers, but there might be a better way to handle this. Can @janvanderhaegen or @PWKad comment?

**Comment by Zensavona** [comment]
Fixed this and added some tests @EisenbergEffect
