### ISSUE TITLE
Need to update aurelia-validation to new version of aurelia

### ISSUE THREAD

**Issue by digizen** [aurelia/validation#138]
Right now, running jspm install aurelia-validation on the Sept 5th Aurelia release will download and install a whole bunch of old aurelia modules, forking the project:

     Installed Forks

                     github:aurelia/binding 0.8.6 0.9.1
        github:aurelia/dependency-injection 0.9.2 0.10.1
       github:aurelia/html-template-element 0.2.0 0.3.0
                      github:aurelia/loader 0.8.7 0.9.0
                     github:aurelia/logging 0.6.4 0.7.0
                    github:aurelia/metadata 0.7.3 0.8.0
                        github:aurelia/path 0.8.1 0.9.0
                  github:aurelia/task-queue 0.6.2 0.7.0
                  github:aurelia/templating 0.14.4 0.15.3
                                npm:core-js 0.9.18 1.0.1

**Comment by EisenbergEffect** [comment]
@PWKad Would it be possible for you to help with releases and critical bug fixes on this library? If so, we need to get an updated release out that matches the aurelia release from early this week. I could even take over doing releases in the future if someone can give me an overview of any idiosyncrasies I need to know about.

**Comment by PWKad** [comment]
This is completed.
