### ISSUE TITLE
Important Contributing Practices

### ISSUE THREAD

**Issue by EisenbergEffect** [aurelia/validation#14]
All commit messages need to adhere to the contributing guidelines. Also, each release should be done with the prepare-release gulp test to ensure that the proper change log is generated into the docs folder. The change notes particular to the release should be part of the github release notes. This needs to be done to be consistent with all other Aurelia libraries.

**Comment by janvanderhaegen** [comment]
@EisenbergEffect Sorry about that, I've cleaned up the releases and have the contributing guidelines hanging over my desk.
I will ask help in the gitter channel to make sure next releases are consistent with all other aurelia libraries.

**Comment by EisenbergEffect** [comment]
Not a big deal at this point. Just wanted to call it to your attention for the future.
