### ISSUE TITLE
Cannot read property 'TWBootstrapAppendToInput'

### ISSUE THREAD

**Issue by eaidland** [aurelia/validation#151]
Just updated with jspm update. Now I get the:
Unhandled promise rejection TypeError: Cannot read property 'TWBootstrapAppendToInput' of undefined(…)

    .plugin('aurelia-validation', (config) => {
        config.useLocale('nb-NO').useViewStrategy(ValidateCustomAttributeViewStrategy.TWBootstrapAppendToInput);
    })

something I've missed/need to update?

**Comment by PWKad** [comment]
Yes there is a breaking update to the strategy names, please check the release notes - 

https://github.com/aurelia/validation/releases
