### ISSUE TITLE
Three Questions for next release

### ISSUE THREAD

**Issue by PWKad** [aurelia/validation#152]
# Validation questions -

If you've been using validation for at least some time now a few questions -

1. What's the biggest issue or hurdle in your opinion that needs to be tackled?
1. Does Validation need tighter coupling to more CSS frameworks in the next release or to be looser with the ability to override a template?
1. Would it make sense to make the validation properties that are failing easier to iterate over?

**Comment by nomack84** [comment]
Hi @PWKad, to me this are:
 
 1. #10 as add support for a very important feature. There should probably some others which are also important but that one has high priority
 2. I prefer the ability to override templates. Someone could simply make a plugin with several implementation for various frameworks, but this should be external to the framework, thought we could keep the bootstrap's one as a reference implementation.
 3. I think currently isn't hard to iterate over the failing validation properties, so we could keep it as it is.

Regards

**Comment by jeremy-holt** [comment]
I am having a terrible job understanding the conditional expressions - would it be possible to have some better documentation, say starting with very simple cases and building on them to create more complexity?
I keep coming up against the same use case which is to test whether another field is undefined||null and then apply the validation accordingly  @jeremy-holt  :point_up: [September 29, 2015 3:21 PM](https://gitter.im/Aurelia/Discuss?at=560ad6bddfb3151302855cb3).
As to the css - I think it should be looser with an easy way to override the template. By the way - where are the templates - I did my overrides in my styles.css.

Regards
Jeremy

**Comment by gregoryagu** [comment]
I have been using Validation for several weeks.  The only issue that has come up has to do with showing validation errors in a toast like toastr.  When that is done, there needs to be a way to get a user friendly name for the property that is failing validation.  We switched over to the in-place validation messages where you don't need the friendly name. For example, if the field is "first-name" you would want to display "First Name" in the message.  We found ways to solve this but they are hacky. But overall, the validation plug-in is great.

**Comment by stevies** [comment]
2 - Looser and easier to override. I have found myself just using bootstrap's core mark-up structure to get basic integration working - overriding the template was a bit painful to work with. If that could be made easier, then integrating with any framework should be easier - maybe.

**Comment by devmondo** [comment]
2- yeah please loosen up the css frameworks, we have many scenarios where we have custom form or layouts, and sometimes we dont user bootstrap at all!
 
angular angular's NGMessage is really good example of customization of validation

**Comment by wichert** [comment]
My main issues right now are:

1. validation seems to have a very hard time finding where to insert error messages in the DOM, often failing. This seems especially true with errors returned by an `onValidate` function.
2. There is no way to generate view/form-generic error messages. Many forms have errors that are generic for the entire form, or tied to a block of questions (often grouped in a ``fieldset`` element. *very* common for a set of checkbox or radio buttons). It would be very useful to be able to have `onValidate()` return an error for an unbound name, which you can pick up in your template.

**Comment by PWKad** [comment]
Thanks everyone for the feedback closing this out for now.
