### ISSUE TITLE
Add documentation to public classes and methods

### ISSUE THREAD

**Issue by janvanderhaegen** [aurelia/validation#16]

**Comment by janvanderhaegen** [comment]
Classes and method have documentation, but during gulp prepare-release some errors are shown, not sure what I'm doing wrong

**Comment by PWKad** [comment]
The jsdoc / yuidoc formats will be dropped in favor of using the TypeScript .d.ts files to generate the api.json.  Closing this one for now since there are a bunch of issues open already on TypeScript generation.
