### ISSUE TITLE
Crash: System may be undefined

### ISSUE THREAD

**Issue by jods4** [aurelia/validation#160]
I upgraded to latest aurelia-validation and got a crash on this line:
https://github.com/aurelia/validation/blob/master/src/validation-locale.js#L58

It seems you cannot use `System` like that, as some browser may not have it.
You should use `aurelia-loader` instead, I think, as `DefaultLoader` has alternative implementations for browsers without `System`.

**Comment by stefan505** [comment]
Using RequireJS instead of SystemJS, forces me to change the `load(...)` implementation to:

```
require([basePath + localeIdentifier], function (resource) {
    var locale = _this.addLocale(localeIdentifier, resource.data);
    resolve(locale);
});
```

Will this be addressed in future? I don't want to keep hacking `validation-locale.js` manually each time the packages are updated.

**Comment by EisenbergEffect** [comment]
@PWKad This definitely needs to be changed. `System.import` should not be used anywhere in code. It's actually not part of the spec anymore and going to be changed in the next loader API update. To shield everyone from this, use Aurelia's `Loader` API internally only. That will ensure that no breaking changes happen and that we can simply change our internal loader implementation when the API updates. That will also ensure that the validation library works correctly with requirejs and dojo loader, which it won't in its present form. Those are important scenarios during the transition period to ES6 modules.
