### ISSUE TITLE
Unhandled Promise Rejection

### ISSUE THREAD

**Issue by alsoicode** [aurelia/validation#163]
Hello. I'm seeing an exception when validation fires. My view model is validated successfully, but this exception is logged in the console:

```
Unhandled promise rejection ValidationResult {isValid: false, properties: Object}
(anonymous function) @ es6.promise.js:139
module.exports @ $.invoke.js:6
queue.(anonymous function) @ $.task.js:40
run @ $.task.js:27
listner @ $.task.js:31
```

I'm using aurelia-validation 0.4.0 and aurelia-framework 0.17.0. Here is my view model:

    import {inject} from 'aurelia-framework';
    import {Validation} from 'aurelia-validation';
    import {ensure} from 'aurelia-validation';

    @inject(Validation)
    export class Inquire {

        @ensure(function(value) { value.isNotEmpty() })
        firstName = '';

        @ensure(function(value) { value.isNotEmpty() })
        lastName = '';

        phone = '';

        @ensure(function(value) { value.isNotEmpty().isEmail() })
        email = '';

        @ensure(function(value) { value.isNotEmpty() })
        question = '';

        constructor(validation) {
            this.validation = validation.on(this);
        };

        sendInquiry() {
            this.validation.validate().then(() => {
                console.log('form passed validation');
            });
        };
    };

**Comment by PWKad** [comment]
Yes I believe this is by design, you need to handle all failed validation with a `catch`.

**Comment by alsoicode** [comment]
Being new to ES6, that would go here:

    sendInquiry() {
        this.validation.validate().then(() => {
            console.log('form passed validation');
        }).catch(error => {
            // do something here;
        });
    };

correct?

**Comment by alsoicode** [comment]
Yay, answered my own question :)
