### ISSUE TITLE
TypeError: Cannot read property 'classList' of null

### ISSUE THREAD

**Issue by atsu85** [aurelia/validation#166]
*Overview*: There is an error in console 
> TypeError: Cannot read property 'classList' of null

when using default viewStrategy
and validatable input has less than 5 parents (constant in code https://github.com/aurelia/validation/blob/master/src/strategies/twbootstrap-view-strategy.js#L12)
and input doesn't have a parent `.form-group` that `TWBootstrapViewStrategyBase` is looking for. 
![capture](https://cloud.githubusercontent.com/assets/1206512/10648000/9702d86c-7844-11e5-90c3-dffda5f473f1.PNG)

*Motivation for change*: waste less developers time by adding helpful log message.

When there are more than 5 parents, then currently there are no error or warning in console related to it and validation messages are just not shown to the user. Developer needs to start debugging, why validation messages are not shown.

When there are less than 5 parents, then the error message doesn't say anything meaningful - developer needs to start debugging.

*Version*: aurelia validation 0.4.0 (current latest)

*Proposal*: Instead of error (that doesn't say much useful) it would be better to add logging message. To avoid big changes, I'd suggest logging with warn level, even tough probably not having a form group is error made by the developer.

**Comment by atsu85** [comment]
Please merge my pull request https://github.com/aurelia/validation/pull/167/files
to resolve this issue.

**Comment by PWKad** [comment]
This PR has been merged in to the refactor branch for the templating abstraction.  Closing for now but leaving the PR open until the new repo is created.
