### ISSUE TITLE
Only show validation errors when a field has been entered and left, or when save clicked

### ISSUE THREAD

**Issue by sickboy** [aurelia/validation#173]
It would be great if validation errors can be hidden until a field was actually 'tabbed into' and 'out of'.
And/or when the user clicked the Save button. Not to litter the screen with errors before the user has even started.

Optionally, some indication at a field that it is required is perhaps useful beforehand, like a * or so.

**Comment by PWKad** [comment]
Moved to https://github.com/aurelia/templating-validation/issues/1
