### ISSUE TITLE
error Error instantiating TaskQueue

### ISSUE THREAD

**Issue by VladCherniavsky** [aurelia/validation#175]
After  installing  validation plugin I get the error:
    EROR [app-router] Error: Error instantiating TaskQueue

Without this plugin  my app works correctly.

**Comment by EisenbergEffect** [comment]
@PWKad Can you look into this. @VladCherniavsky I think we are going to need some more information to track this down. Can you create a reproduction for us so we can see the issue?

**Comment by VladCherniavsky** [comment]
@EisenbergEffect You can see it here:http://fic-chat-ux-divdiv.c9.io/.

**Comment by EisenbergEffect** [comment]
@VladCherniavsky The only error I see there is related to browser sync. That isn't Aurelia, but a plugin you are trying to run in production. But, to really track this down, I'm going to need a simple set of steps a can use to reproduce the problem in my own app.

**Comment by VladCherniavsky** [comment]
@EisenbergEffect you need to wait more to see this error. Thank you
![image](https://cloud.githubusercontent.com/assets/8988069/11124162/baff57cc-8974-11e5-96c6-56e860850f5d.png)

**Comment by EisenbergEffect** [comment]
You  have forks...multiple versions of the same libraries trying to run at the same time. That's most likely the cause of your problem (and it also causes things to load...really, really slowly). You probably have a 3rd party plugin that is dependent on an old version of Aurelia or that you haven't updated.
