### ISSUE TITLE
Remove aurelia-validation-message on show.bind being false

### ISSUE THREAD

**Issue by ShawnCholeva** [aurelia/validation#176]
Hey all, I was wondering if there is currently any way to remove the validation-message once a show.bind becomes false.

For example I have this dropdown and input.  When it is selected to yes, the expiration date input displays, and the required message like expected.

![image](https://cloud.githubusercontent.com/assets/13332685/11078145/97651a2e-87c9-11e5-8d45-018f144f60cf.png)

Now once I click the dropdown to No to fail the show.bind, only the validation-message remains like so

![image](https://cloud.githubusercontent.com/assets/13332685/11078163/c3721860-87c9-11e5-8b86-7f3b1f637862.png)

Any ideas or thoughts on this?  I don't believe I am able to use the if.bind since it would be completely removed from the DOM.

**Comment by ShawnCholeva** [comment]
Forgot to add that this validation occurs in a computed from that checks the value of the Yes/No drop down, and if true add a .isNotEmpty() onto the date field.

**Comment by ShawnCholeva** [comment]
A workaround for this is to just have a container around the input field and attach the show.bind to the container.  Not sure if you want the tags to be removed on just the element the show.bind is on, just an idea.

**Comment by PWKad** [comment]
@ShawnCholeva I think hiding everything is the best solution at the moment.  If you disagree please feel free to open this back up and we can discuss further.
