### ISSUE TITLE
Update to aurelia nextVersion

### ISSUE THREAD

**Issue by janvanderhaegen** [aurelia/validation#18]
There are quite some breaking changes according to http://blog.durandal.io/2015/03/25/aurelia-0-10-0-release-status/.
One of them involves the api with which plugins register themselves. There might or might not be other breaking changes as well.
- update to latest version
- add unit tests to the 'loader' mechanism to that future API changes can be tracked automatically, not manually
- fix broken changes

**Comment by janvanderhaegen** [comment]
Updated & fixed changes.
To write unit tests on the API of the 'Aurelia' object, we need to take a dependency on 'aurelia-framework'. Need to investigate how we can take a jspm devDependency

**Comment by zewa666** [comment]
Why would you wan't to test that as part of the plugin? As I see it this is more a general behavior which should be tested in the framework itself instead in every plugin by it's own.

What Aurelia-Validation should test though is that an index.js with an exported function is provided and that one might accept a callback as 2nd parameter.

Here's how I did that for aurelia-18next https://github.com/zewa666/aurelia-i18next/blob/master/test/unit/aurelia.integration.spec.js
What do you think about that?

**Comment by janvanderhaegen** [comment]
Neat stuff!
Going to leave this open a little bit. There are a couple of possible settings for the validation library "I18N", defaults, ... so I need to bundle them into a single configurations object, then create my own callback function signature ;-)

**Comment by janvanderhaegen** [comment]
Closed because I just noticed I only left it open for the configure request, which is identical to #21
