### ISSUE TITLE
Bundling fails

### ISSUE THREAD

**Issue by RWOverdijk** [aurelia/validation#183]
Hello :)

After bundling aurelia-validation into my application and running the server, I get:

> Error loading http://127.0.0.1:8080/jspm_packages/github/aurelia/validation@0.4.1/resources/nl-NL.js

Which makes sense, because in my dist folder I don't have any `jspm_packages`. So my question is this: do you know why locales don't seem to get bundled? Do you know how I can add them? I tried adding `'github:aurelia/validation@0.4.1/resources/nl-NL.js'` to the bundler, but it still tried to download the file. Are you perhaps not using DI for this?

**Comment by JeroenVinke** [comment]
Adding `'aurelia-validation/resources/**/*'` to my bundle configuration fixed this for me

**Comment by RWOverdijk** [comment]
@JeroenVinke Thanks. Works for me, too :)
