### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by hadrienl** [aurelia/validation#187]
Hi,

I think i18n should be better linked to https://github.com/aurelia/i18n. `Validation` should automatically set with the current I18N locale config. Actually, it's set to "en-EN" and I have to set it manually in all my custom elements which uses a validation.
It should search for translation fallbacks in I18N file. Actually, if I set the locale to "fr", it just throw an error because there is no "resources/fr.js" file but a "resources/fr-FR.js". In this case, it should first take a look in the file set with I18N (which is in my case in "/locales/fr/translations.json") and then in "resources/en-US.js".

**Comment by RWOverdijk** [comment]
:+1: 

I'm trying to supply custom validation groups for aurelia-orm. I want to include the translations with it.

**Comment by PWKad** [comment]
This is being tracked in #174 please feel free to add a comment there with a recommendation on how i18n could be configured then.
