### ISSUE TITLE
Don't validate at all until submit

### ISSUE THREAD

**Issue by cknightdevelopment** [aurelia/validation#191]
I was wondering if there is currently a way to have validation not occur at all until the from is submitted for the first time (or perhaps for any action we dictate). I read a common use case [here in your documentation](https://github.com/aurelia/validation/blob/master/doc/Intro.md#how-are-elements-and-validation-rules-matched), but what I am looking to is a bit different. I would like to have the following user experience:

* all fields in a form show no validation messages
* when the user changes the value, validation messages & visual clues will **_NOT_** be shown for each field he/she has edited
* when the user hit submit, all input elements on the form will show validation messages & visual clues
* if all validation rules have passed, the form submission code will actually run. If not, the user will clearly see what properties are valid, which are invalid, and why

Essentially I do not want to show any validation messages until after the user clicks the submit button for the first time. I currently do not really see a way to do this.

Is there something I am missing? How could I go about this? Thank you!

**Comment by valichek** [comment]
You can try to use custom view strategy to show errors or not to show errors https://github.com/aurelia/validation/blob/master/doc/Intro.md#configuseviewstrategyviewstrategyinstance and check some custom attribute (`<input validate="..." validate-disabled.bind="isButtonClicked">`) and set that custom attribute whenever you need to disable/enable errors. Just thoughts.

**Comment by PWKad** [comment]
@cknightdevelopment for now I think @valichek 's recommendation is a solid one.  If you feel there is something else missing please let use know, closing for now.
