### ISSUE TITLE
this.validation = validation.on(...) causes silent failure.  Aurelia does not render view.  No errors in console.

### ISSUE THREAD

**Issue by kdawg1406** [aurelia/validation#195]
I ran "jspm update" on my project today, 19 Dec 2015 to ensure I have the latest drops.

I have a super simple example.  One view, one viewmodel, one Customer object.

The Customer is a pojo.

I've added the validation for the Customer in the viewmodel. 

I've tried each of the three ways to enable validation in the below constructor.  Each syntax results in a silent failure; meaning, no errors or warnings in the Chrome Developer Console, and nothing rendered to the screen.

**My biggest concern is the silent failure.**  I've not seen this behavior before today.  In the last 2 hours of trying to get this to work, I've had many silent failures.

I must be doing something wrong.  I've tried everything I can find on the web, but can't get this scenario to work.

Thank you for your assistance.

Karl

*Suggestion:  Update the docs to reflect common usage scenarios like view controls binding to objects instead of simple view model properties.*

```javascript
import {Validation} from 'aurelia-validation';
import {inject} from 'aurelia-framework';
import {Customer} from '../model/customer';

@inject(Validation)
export class Home2 {

    constructor(validation) {

        this.customer = new Customer();
        this.customer.firstName = "Karl";

        this.validation = validation.on(this.customer).ensure('firstName').isNotEmpty();
        //this.validation = validation.on(this).ensure('customer.firstName').isNotEmpty();
        //this.validation = validation.on(this).ensure('firstName').isNotEmpty();

    }
}
```

```
<template>
    <form validate.bind="validation">
        <div>
            <label >First Name</label>
            <input type="text"
                   validate="firstName"
                   value.bind="customer.firstName"
                   maxlength="8"
                   />
        </div>
        <div>
            <label >Last Name</label>
            <input type="text"
                   validate="lastName"
                   value.bind="customer.lastName"
                   maxlength="20"
                   />
        </div>

    </form>
    <div style="margin-top: 30px">
        <span>Full Name: ${customer.firstName} ${customer.lastName}</span>
    </div>
</template>
```

```javascript
export class Customer {

    constructor() {
        this.firstName = '';
        this.lastName = '';

    }
}
```

**Comment by kdawg1406** [comment]
Forget to mention, if I comment out all this.validation ... in the constructor the view renders fine.

**Comment by bfil** [comment]
Kind of the same problem here, I've updated to the latest beta version of Aurelia, and validation now throws the following error in my console:

`Unhandled promise rejection TypeError: Cannot read property 'getValue' of undefined`

**Comment by PWKad** [comment]
@kdawg1406 The reason the failure is silent is because somewhere along the way one of the promises is being swallowed.  This is being tracked in this issue - https://github.com/aurelia/validation/issues/110 #110
