### ISSUE TITLE
API is inconsistent

### ISSUE THREAD

**Issue by janvanderhaegen** [aurelia/validation#20]
The API currently asks some validation rules to be added using functions prefixed by 'is':
- isStrongPassword()
- isAlphanumeric()
- ...

This is inconsistent with the more 'verb-less' validation rules:
- email()
- minLength()
- notEmpty()

TODO: decide on most desired API, then refactor so that they are consistent:
```javascript
this.validation = validation.on(this)
  .ensure('user.email').email()
  .ensure('user.password').strongPassword();

this.validation = validation.on(this) 
  .ensure('user.email').isEmail()
  .ensure('user.password').isStrongPassword();
```

Personally I'd prefer the latter: having a 'verb' in each function that indicates a validation rule being executed. This is longer but 
- reads more like fluent English in combination with the preceding 'ensure'
- is consistent with verbs in the functions '[passes(customFunction)](https://github.com/aurelia/validation/blob/master/doc/Intro.md#passescustomfunction-threshold)', '[passesRule(validationRule)](https://github.com/aurelia/validation/blob/master/doc/Intro.md#passesrulevalidationrule)' 
- shows the contrast with logical operators such as '[if(conditionalExpression)](https://github.com/aurelia/validation/blob/master/doc/Intro.md#ifconditionalexpression)' and '[switch(conditionalExpression)](https://github.com/aurelia/validation/blob/master/doc/Intro.md#switchconditionalexpression)'

**Comment by ejsmith** [comment]
I prefer the latter verb based version a well.

**Comment by bryanrsmith** [comment]
+1 for verb-based. It makes the API read more fluently, which looks like what you're going for with the API.

**Comment by bastienJS** [comment]
From a german perspective isPasswordStrong sounds better. First the subject then the adjectiv.

**Comment by janvanderhaegen** [comment]
@bastienJS Are you sure? 
```javascript
.ensure('pw').isStrongPassword();
```
Reads like "stellen Sie sicher, "Vorname" ist ein sicheres Passwort", no? I get your point just looking at the method alone, but does isStrongPassword not make more sense in the complete API?

**Comment by bryanrsmith** [comment]
I don't know German, but in this case I don't think of "StrongPassword" as a subject and an adjective, I think of it as a single subject. You're not asking if the password is strong, you're asking if the value is a strongpassword. The operand is a field/value, not a password. So, I like `isStrongPassword` :-)

**Comment by janvanderhaegen** [comment]
Proposal:
    notEmpty() => isNotEmpty()
    between(minimumValue, maximumValue) => isBetween()
    betweenLength(minimumLength, maximumLength) => hasLengthBetween()
    email() => isEmail() 
    equals(otherValue, otherValueLabel) => isEqualTo() or isSameAs()
    in(collection) => isIn()
    isAlphanumeric()
    isAlphanumericOrWhitespace()
    isDigit()
    isStrongPassword(minimumComplexityLevel)
    isNumeric()
    minLength(minimumLength) => hasMinLength()
    minimum(minimumValue) => IsMinumum() / isGreaterThen() / isGreaterOrEqualThen()
    matches(regex)
    matchesRegex(regexString)
    maxLength(maximumLength) => hasMaxLength()
    maximum(maximumValue) => isMaximum() / isLessThen() / isLessOrEqualThen
    notEquals(otherValue, otherValueLabel) => isNotEqualTo() / isNotSameAs()
    passes(customFunction, threshold)
    passesRule(validationRule)
    withMessage(message)

Feedback appreciated :)

**Comment by bryanrsmith** [comment]
:+1: 

* `isEqualTo` sounds strict compared to `isSameAs`. `isSameAs` sounds like it might try harder to find a match, maybe by trimming, changing case, etc.
* `isIn` is a little ambiguous. What about `isInCollection`, or `isContainedBy`?
* Do we need an `isAlpha`? I see `isAlphanumeric` and `isNumeric`. Similarly, there is an `isDigit` but no `isLetter`. Not sure if those are intentional omissions. Is `isDigit` just a convenience for `.isNumeric().hasMaxLength(1)`?
* "then"s should all be "than"s.
* I think `isGreaterThan` is clearer than `isMinimum`, and `isLessThan` is clearer than `isMaximum`.

**Comment by janvanderhaegen** [comment]
- isEqualTo seems more strict than isSameAs, and it's a strict comparision, so agree
- isIn does sound ambigious alone, but I think it's ok once you see it with the parameter: isIn(['Gold', 'Silver']) or isIn(this.allowedValues). Could be wrong
- isAlpha should be added
- isDigit is a constraint on containing only digits. IsNumeric can also contain properly formatted numbers (-9,000,000.123). The allowed properply formatted numbers are provided by I18N implementation. Feedback on better naming for these functions? isDigit => containsOnlyDigits? but then should we rename isAlphanumeric to containsOnlyAlphanumeric?
- Ooops, the then vs than :( Can I hide behide not being native English again? :)
- I like isGreaterThan too over isMinimum, only caveat (with both naming really) is it might sound a little weird when used with dates?  Or are we pushing it here?

Thanks for the feedback!!!!!!!

**Comment by bryanrsmith** [comment]
* You're right that the the array parameter helps `isIn`.

* Your description of `isDigit` makes sense, it's just that the name makes it sound singular. `containsOnlyDigits` or `isOnlyDigits` reads slightly awkwardly, but makes the behavior clearer.

> Can I hide behide not being native English again? :)

Totally!

* I think date comparisons are well enough understood that `isGreaterThan(date)` is fine. `isAtLeast()` might be an alternative. Not sure if it helps :-)

**Comment by janvanderhaegen** [comment]
@bryanrsmith discussing this helps a LOT, thank you!
I think we're down to the isDigit. 
I like the *containsOnly* makes most sense, we could do a whole series of these:
- containsOnlyDigits
- containsOnlyLetters
- containsOnlyAlphanumerics (OrWhiteSpace)
- containsOnly(/[0-9,a-z]/i)

In a later stage, we plan to add input restrictions to validation-bound-fields so that it will not accept any characters other than those allowed by the containsOnly constraint.


A second question: would you prefer to have both *isGreaterThan* and *isGreaterOrEqualThen* or pass an optional parameter if the bounds are inclusive (ie: *isGreaterThan(10, LowerBound.Inclusive)*)? If the latter, how would we name the enum? *LowerBound.Inclusive*?

**Comment by bryanrsmith** [comment]
No problem. Glad to help!

I like `containsOnly`, too.

IMO the optional parameter and enum would be overkill. I think it would make sense to do that if we wanted to make it easy to programmatically chose the inclusiveness, or if the enum had many values that would otherwise require a lot of additional methods. I'd vote for adding both `isGreaterThan` and `isGreaterThanOrEqualTo`, as well as `isLessThan` and `isLessThanOrEqualTo` because it's probably less code anyways, and it's easier to read.

**Comment by janvanderhaegen** [comment]
Thanks again man.
Ok, I like the draft we have so far, very readable :-)
I'm still wondering about one last one: the 'isBetween' method and if/how a developer can indicate if it should be strictly between the bounds or if the bounds are inclusive...
Oy, writing it out made me realize we can probably just create 'isBetween' and 'isStrictlyBetween'... Hah!

If anyone has any more suggestions, we'd love to hear them. If not, hold your peace forever ;-)

**Comment by bryanrsmith** [comment]
I think if they want to be explicit they could split the requirements up and do something like `isGreaterThanOrEqualTo(1).isLessThan(10)`. I think the technical definition of "between" is exclusive, but it's commonly used in English to be inclusive. Would it better to avoid the term "between"? `isInRange(minimum, maximum)` might imply inclusive bounds. Stupid ambiguous language... :-)

**Comment by zewa666** [comment]
just throwing in my 2cents on the last part.

I wouldn't make such a deal of it. Just choose when and document it well. Chances are higher you remember after some time what isBetween is instead whether Between vs Whatever else is.

I think the dev should care about whether to add/subtract 1 to get the desired border inclusion or not.
