### ISSUE TITLE
HelpBlock doesn't appear unless input has id attribute set

### ISSUE THREAD

**Issue by slackboxster** [aurelia/validation#201]
If I have an input that is bound to a validated property and I want error messages to show, I will do something like this:

    <input type="text" name="customCssUrl" value.bind="organization.customCssUrl" validate="customCssUrl">

With this setup, the wrapping form-group div gets a has-warning class, but the help-block is not created.

If, however, I add an id attribute to my input, like so:

    <input id="customCssUrl" type="text" name="customCssUrl" value.bind="organization.customCssUrl" validate="customCssUrl">

Now the help-block is created.

Is this expected behavior? If so, I don't see a reason to require the id property since we already have the field name in the validate attribute. Could this not be searched on already?

**Comment by PWKad** [comment]
For now this is expected because the id is enforced to be unique.  We could refactor this to use other selectors but #174 will remove the view strategy as-is and simplify creating the help blocks.
