### ISSUE TITLE
TWBootstrapViewStrategy.AppendToInput breaks the layout for input-group elements

### ISSUE THREAD

**Issue by GoldenCrystal** [aurelia/validation#204]
Here's a bootstrap HTML snippet for understanding the problem:
```html
<form submit.trigger="submit()" validate.bind="myValidation">
    <div class="form-group">
        <label class="control-label" for="myTextBox">Value</label>
        <div class="input-group">
            <input class="form-control" id="myTextBox" type="text" value.bind="myValue" placeholder="Type anything…" />
            <span class="input-group-btn"><button type="submit" class="btn btn-primary">Submit</button></span>
        </div>
    </div>
</form>
```
Here, there's an input-group  with two elements (one of them being a button).
When using TWBootstrapViewStrategy.AppendToInput, I expect the text to appear below this input group. But this is not what happens:
The text is inserted inside the "input-group" div, between the input and the button. Visually, the text appears below the text box, but the button gets shifted down, and the components of the input group are no longer aligned.

**Comment by PWKad** [comment]
Hello @GoldenCrystal - 

Thanks for reporting this issue.  You can actually extend the view strategy by creating your own custom view strategy if you would like to change where things are input in the view.

I will advise that we are wrapping up some refactoring that should extract the templating pieces from validation and give the developer more control over exactly where in the DOM the errors are shown.  I'm hoping to have this ready as soon as possible but I will be sure to come back and close this issue out at that point.  Marking as `will not fix` at this point so I know not to keep checking back here.
