### ISSUE TITLE
No visual feedback created

### ISSUE THREAD

**Issue by rosshigh** [aurelia/validation#205]
I'm getting the correct validation result but no visual feedback is appearing on the form.   

My HTML looks like this:

```
<form role="form" validate.bind="validation">
         <div class="form-group"> 
               <label for="curriculumTitle">Enter the curriculum title</label>
               <input type="text" value.bind="curriculumTitle" class="form-control" id="curriculumTitle" placeholder="Title">
        </div> 
</form>
```

and the JavaScript:

```
this.validation = validation.on(this)
      .ensure('')
      .isNotEmpty();
...
save() {
    try {
      this.validation.validate() 
        .then(() => {
          this.saveHelpTicket();
        });
    } catch (error){
         alert("validation error");
    }
  }
```
Any suggestions?

Thanks,

Ross

**Comment by PWKad** [comment]
@rosshigh You need to specify a view strategy as defined here - https://github.com/aurelia/validation/blob/master/doc/Intro.md#configuseviewstrategyviewstrategyinstance 

Closing for now, if there is something else going on please feel free to re-open and we can discuss further.
