### ISSUE TITLE
@ensure decorator is being ignored in 0.6.2

### ISSUE THREAD

**Issue by mujimu** [aurelia/validation#216]
Pulled latest npm:aurelia-validation@0.6.2 in a _jspm update_ on my project - and validation was suddenly coming back successful on data that should fail.   

I utilize @ensure decorator within my application. After some debugging, it seemed any validation I did with a direct .ensure() call worked as intended, while any with @ensure decorator simply didn't attempt that rule (it just passed).  It seems the decorator is simply ignored.

I just now cloned latest master. Ran tests. Initially had error with aurelia-pal so ran _jspm update_ which alleviated it. Ran tests again, and found that decorator test is failing...

```
Chrome 48.0.2564 (Mac OS X 10.9.5) Tests on using decorators to set up validation on a single property that is invalid FAILED
	Expected true to be false.
```

The other test (on a single property that is valid) passed as it is always coming back true (rules are ignored).

**Comment by PWKad** [comment]
@mujimu I'm showing all tests passing for me.  Let me use the decorator in the sample to make sure I'm not missing something.

**Comment by Souldrinker** [comment]
Seems like I have a similar issue, but I'm not sure what is going on here. On one of our servers we're running a version of our application that we deployed about a month ago with aurelia-validation 0.6.0 and there all our validations with ensure decorators works fine.

But today during a demo (using aurelia-validation 0.6.2) we noticed that the validations no longer work and everything is let through. After seeing this issue I reverted back to 0.6.0, but the ensure decorators still didn't seem to work?!

I then tried to add .ensures to the validation.on and those worked fine. Could it be that this is due to some change in other parts of the framework since it seems to fail even after reverting to 0.6.0? Or is it just me doing something wrong?

**Comment by meash-nrel** [comment]
@Souldrinker we were chatting on gitter yesterday, seems Aurelia 0.6.2 works fine out of the box for @PWKad but after running _jspm update_, something breaks the decorators.  

The fact you reverted to 0.6.0 and it still didn't work seems to be consistent with our conclusion.... that the root cause of the decorator failure is actually in a different Aurelia framework lib.

**Comment by meash-nrel** [comment]
after updating dependencies one at a time (at least those not interdependent on each other), i isolated the issue to this library causing the failure in validation ensure decorator

aurelia-metadata 1.0.0-beta.1.1.3 -> 1.0.0-beta.1.1.4

**Comment by meash-nrel** [comment]
I am at a loss as to why ... not seeing that anything really changed in aurelia-metadata in 1.1.4.

**Comment by doktordirk** [comment]
so far, no matter what i try, i end up with 
```shell
Chrome 48.0.2564 (Windows 10 0.0.0) Tests on using decorators to set up validation on a single property that is invalid FAILED
        Expected true to be false.
            at Expectations.assertTestResult (C:/Users/dirk/validation/test/expectations.js:27:39)
            at C:/Users/dirk/validation/test/expectations.js:61:26
            at run (C:/Users/dirk/validation/jspm_packages/npm/core-js@2.1.0/modules/es6.promise.js:115:49)
            at C:/Users/dirk/validation/jspm_packages/npm/core-js@2.1.0/modules/es6.promise.js:129:9
```

**Comment by doktordirk** [comment]
with further testing: 
after update it doesn't work (using core-js@2.0.3)
it works after reverting to core-js@1.2.6

**Comment by jsobell** [comment]
The issue appears to be in the ES7 shim code for metadata handling.
The new code calls https://github.com/zloirock/core-js/blob/master/modules/es7.reflect.get-own-metadata.js#L8 but for some reason this is looking at argument[2] instead of argument[0].
Since that method only has two arguments, am I missing something or is that a bug?
I'm too new at this stuff to make an authoritative statement.

**Comment by jsobell** [comment]
Nope, scrap that. It's something to do with the difference between to ES7 shim version and aurelia-metadata's version.  On the core shim the read of the metadata is empty.
The metadata assigned at https://github.com/aurelia/metadata/blob/master/src/metadata.js#L67 is not returned when later read through https://github.com/aurelia/metadata/blob/master/src/metadata.js#L60 despite having the same values.
As this is done elsewhere for resources and binding I'm at a loss as to why it fails for the validation key.

**Comment by obany** [comment]
I have had a look at this issue and the reason this now fails is as follows.

Before the core-js bump the aurelia metadata had it's own polyfills for metadata reflection, with the core-js update these were replaced by the core-js versions.

The aurelia polyfills stored the metadata on the objects directly which works when accessed with either the Object.prototype or a this reference - which is the mechanism used by validation.

`validationGroup = validation.on(this);`


The core-js polyfills store the metadata in a weakmap keyed by the object type so when the validation looks up the metadata using the this reference it fails.

To prove this and as a temporary fix you can setup the validation in your classes using

`validationGroup = validation.on(MyClass.prototype)`

**Comment by stefan505** [comment]
@obany, that worked thanks!

**Comment by jsobell** [comment]
It doesn't work for me. If I try this then the constructor based validations fail and the directive based ones always fail too.

**Comment by obany** [comment]
That's true constructor based validations would fail as they no longer reference the this object, this fix workaround is purely for ensure based validations.

**Comment by EisenbergEffect** [comment]
@obany Thanks for looking into this. @PWKad We need to address this. It may involve a bit of defensive coding inside some of the helper methods to account for various differences in polyfill implementations. In other words, `validation.on` may need to check in multiple locations. I'm not familiar with the internals..I know you've been doing some re-writing to fix issues, so maybe it's already addressed. I just wanted to bring it to your attention.

**Comment by PWKad** [comment]
In the re-write the decorators all focus on decorating the properties at the moment.  I've added use-cases and I believe tested on class methods but I'll make sure if we support that to re-verify.

As far as fixing the current `@ensure` decorator it will probably be this weekend before I can dig in to the internals to see what we can do, if anyone beats me to it PR welcome, even just as a starting point ;)

**Comment by jsobell** [comment]
@obany Yes, but all `@ensure` based rules fail on our tests, so I suspect something else.
We embed a validation rule like this and it reveals that the values are not supplied to the rules for @ensure (with `login.prototype`), but are in the constructor based method (with `this`):
```
 .ensure('password')
        .if(r => { console.log('r',r);  return true; })
        .isNotEmpty();
```

**Comment by obany** [comment]
I have create a PR with a fix, all the unit tests were failing with the latest core-js and Aurelia packages, but with the fix they all work again.

**Comment by meash-nrel** [comment]
PR is https://github.com/aurelia/validation/pull/220

**Comment by jsobell** [comment]
Are we testing this properly? Does the appropriate test check that the rule is correctly supplied, or simply that it has been called?
As I said, this fix introduces the problem I described above on the typescript skeleton project.
