### ISSUE TITLE
Validating a bounded property on a custom attached behavior causes a classList is undefined error

### ISSUE THREAD

**Issue by codelabnz** [aurelia/validation#24]
I have the following setup using the validation plugin

```
<form validate.bind="validation" submit.delegate="save()">
     
     <div class="form-group">
       <input type="text" class="form-control" value.bind="contract.client"/>
     </div>
    
      <lookup-widget title="Client" placeholder="Find Client..." value.two-way="contract.client"></lookup-widget>
     
      <button type="submit" class="btn btn-default">Save</button>
    </form>
</template>
```

When you run the application an error occurs saying "classList is undefined".   Going through the validation source in file validate-attached-behavior.js for the function searchFormGroup is assumes the element is a standard HTMLElement however the lookup-widget is a DocumentFragment which has no classList property.   I assume because the way the widget is rendered via Aurelia that it's injected as a DocumentFragment.

So replicated steps would be to try and bind a property from a model on a custom widget (attached behaviour) where the property has been marked as to be validated.

```javascript
this.validation = validation.on(this)
                        .ensure('contract.client').notEmpty()
```

**Comment by janvanderhaegen** [comment]
Oops! Thanks for reporting and providing such clear instructions.

**Comment by codelabnz** [comment]
:) No worries.

My workaround was the following.

```javascript
searchFormGroup(currentElement, currentDepth) {
    
    if (currentDepth === 5 || currentElement == null) {
      return null;
    }
    
    if (currentElement.classList && currentElement.classList.contains('form-group')) {
      return currentElement;
    }
      
    return this.searchFormGroup(currentElement.parentNode, 1 + currentDepth);
  }
```

Just added a couple of checks on the currentElement object.  Keeps it from breaking but not sure if this has any impact on the rest of the plugin.  Cheers

**Comment by janvanderhaegen** [comment]
@codelabnz Thanks again Tim,

The impact should be minimal, basically the attached behavior is trying to to 'up' the DOM starting with your custom HTML element to find an element that has a class 'form-group'. If the current element does not have a classList, it should indeed just keep looking instead of throwing an exception :S

A quick karma test exposed the flaw, and your fix turned the test green. I'll be releasing the new version in a couple of days.
