### ISSUE TITLE
please make a new release to facilitate development on aurelia-validatejs

### ISSUE THREAD

**Issue by mbroadst** [aurelia/validation#242]
`ValidationError` was moved to this project, a duplicate exists in `aurelia-validatejs` however everything is being imported from this project. This project, however, hasn't made a release in the meantime so e.g. karma tests don't run at all for `aurelia-validatejs` because `ValidationError` isn't exported. I suspect this is because those developing the plugins are using something like `jspm link`, but it's really making development tough for those of us trying to dedicate a lazy sunday morning to helping this project.

**Comment by PWKad** [comment]
This was released yesterday.  Actually it really sucks for me too so I'm just manually copying the dependency over to jspm folder.  It's tough for me too.  Perhaps a mono-repo makes this easier for validation.

**Comment by PWKad** [comment]
@mbroadst last paragraph related - https://github.com/aurelia/validatejs/issues/23#issuecomment-218587957
