### ISSUE TITLE
Add types to support .d.ts file generation

### ISSUE THREAD

**Issue by PWKad** [aurelia/validation#244]
Need these so that the aurelia-validatejs lib can generate it's own without failing

Reference https://github.com/aurelia/validatejs/issues/10

**Comment by jrigsby** [comment]
With validation released to alpha yesterday.  I wanted to try testing it out but I use typescript in visual studio 2015 via gulp.  The other day I followed a project that fixed aurelia rtypings by editing typings.json and went to do the same for aurelia-validation and aurelia-valdiatejs.  For validation I tried using

"aurelia-validation": "github:aurelia/validation/dist/aurelia-validation.d.ts#e52e1c80866b14165d8407fdd87a0aeb73151131"

but when executing typings install I get 

"Attempted to compile "aurelia-validation" as a global module, but it looks like an external module."

Is this related or am I doing something wrong in trying to get typings?  Its alpha so not expecting things to work in every use case but would like to "watch" something to know when I can.

**Comment by WorldMaker** [comment]
@jrigsby That error means that aurelia-validation should be in `dependencies` rather than `globalDependencies` in typings.json.

**Comment by jrigsby** [comment]
Okay thank you, then Ill make the change and try to get it to work.

**Comment by jdanyow** [comment]
@jrigsby are you all set now?

**Comment by jrigsby** [comment]
As far as typescript and building files goes yes.  Thanks.

On Jun 15, 2016, at 11:07 PM, Jeremy Danyow <notifications@github.com<mailto:notifications@github.com>> wrote:


@jrigsby<https://github.com/jrigsby> are you all set now?

-
