### ISSUE TITLE
Message: key/value cannot be null or undefined. Are you trying to inject/register something that doesn't exist with DI?

### ISSUE THREAD

**Issue by caperavensoftware** [aurelia/validation#246]
Trying to inject validation framework gives me di error.
"Message: key/value cannot be null or undefined. Are you trying to inject/register something that doesn't exist with DI?"

1. install validation plugin.
2. Configure main.js to add plugin
3. Import Validation 
4. Inject validation
5. Inject error

```
    aurelia.use
      .standardConfiguration()
      .developmentLogging()
      .plugin('aurelia-validation');
```

`import {Validation} from 'aurelia-validation';`

@inject(Validation)

**Comment by daekfire** [comment]
Would love to know how you solved this. Having the exact same problem in an app that was working before I rebuilt my node/jspm packages, completely baffled!
