### ISSUE TITLE
To be able to save validation rules in JSON file and use it with Aurelia Validation

### ISSUE THREAD

**Issue by abalmus** [aurelia/validation#248]
The idea is to synchronize validation rules with back end validation.

**Comment by jmvtrinidad** [comment]
If the idea is to validate on your back end side. It is more achievable using a custom rules like this [validation](https://github.com/Knockout-Contrib/Knockout-Validation/wiki/Async-Rules) from Knockout.

**Comment by jdanyow** [comment]
Hey @abalmus- could you provide more details?  What are you looking for, what's your backend technology stack, suggestions on how this should work.
