### ISSUE TITLE
Where's the doc of this plugin

### ISSUE THREAD

**Issue by dpinart** [aurelia/validation#250]
If I'm not wrong this plugin used to contain a detailed documentation in the readme page that I can no longer see? Am I'm missing something?

**Comment by EisenbergEffect** [comment]
Validation is being re-written. We hope to have a big update next week.

**Comment by dpinart** [comment]
I need to change validation locale at runtime and do not remember how to do it. I need old documentation :(. Are there many expected break changes withing the new update?
