### ISSUE TITLE
validationTrigger/validateTrigger naming is incorrect and inconsistent

### ISSUE THREAD

**Issue by bblazely** [aurelia/validation#253]
I think I found a minor naming issue:

From the aurelia.io blog, "To configure the controller's validation trigger, import the validationTrigger enum: import {validationTrigger} from 'aurelia-validation'; and assign the controller's validationTrigger property".

Both the enum and property are named 'validateTrigger', not 'validationTrigger'. I'm assuming it's the code that's wrong and not the blog post, as everything else seems to use the validat"ion" name, not validat"e"?

**Comment by jdanyow** [comment]
fixed- thanks for pointing this out!

**Comment by bblazely** [comment]
@jdanyow No probs, I see you went with validateTrigger in the end. I guess when used in the context of calling the validate() method that makes sense. Looks like you've had a busy day!
