### ISSUE TITLE
aurelia-validation.d.ts has missing imports from 'aurelia-binding'

### ISSUE THREAD

**Issue by stefan505** [aurelia/validation#256]
The `aurelia-validation.d.ts` has issues locating some members from `aurelia-binding`:

```
import {
    AccessMember, <--------- This one
    AccessScope, <--------- This one
    AccessKeyed, <--------- This one
    BindingBehavior,
    ValueConverter,
    bindingMode
} from 'aurelia-binding';
```

Not sure if this should be filed here or under `aurelia-binding` though.

**Comment by EisenbergEffect** [comment]
Issue moved to [aurelia/binding #432](https://github.com/aurelia/binding/issues/432) via [**ZenHub.io**](https://www.zenhub.io/)
