### ISSUE TITLE
IE 11 issues with 0.9.2

### ISSUE THREAD

**Issue by maverix** [aurelia/validation#257]
Hi All,

I have just grabbed the latest (0.9.2) and have hit an issue with IE11.

in the validate-binding-behavior bind method
the target is undefined and blows up (no null checking)

quick fix >>

    var target = this.getTarget(binding, source);
    if (target === undefined || target === null)
          return;

Another issue regarding undefined objects in the unbind method

      if (binding.validationController !== undefined && binding.validationController.unregisterBinding != undefined)
        binding.validationController.unregisterBinding(binding);

**Comment by maverix** [comment]
Yeah, I'm seeing lots of IE only errors with the latest validation module.  I'll see about getting a repro together

**Comment by huw489** [comment]
Yes, I've had an IE problem with `return controller.view.firstChild.parentElement;
` changing it to `return controller.view.firstChild.parentNode;` seemed to fix it.

**Comment by maverix** [comment]
The root issue seems to be in the getTarget method of the validate binding.
In my testing this fixes the issue for IE where the getTarget method was returning undefined.

**Comment by maverix** [comment]
@jdanyow could be that the other fix suggested by @huw489 is better. To be honest I didn't really understand the intention of the controller part of the getElement method

**Comment by jdanyow** [comment]
@maverix the `getTarget` method's job is to get the DOM element associated with the data-binding.  Most of the time it's pretty easy... it's the binding's target but sometimes the binding's target is an aurelia custom element, which is a javascript class, so we need to use the controller to locate the actual DOM element.

**Comment by jdanyow** [comment]
now there's a comment in the code explaining what it does ^^^

**Comment by maverix** [comment]
Thanks @janus007. i'm really enjoying working with Aurelia.  Its the first time that javascript development has felt more productive than my traditional server-side MVC stack
