### ISSUE TITLE
problem with .d.ts files

### ISSUE THREAD

**Issue by lucamorelli** [aurelia/validation#258]
Hi, I updated the projects (vs 2015 + ts) to the latest bits, used the workaround to install the latest version  of .d.ts, and updated the aurelia-validation .d.ts too, and I'm having a dfew issues.
This is not the first time I have this kind of problem:
1. I add the .d.ts for **aurelia-validatejs**, but I have have to add the .d.ts for **aurelia-validation** too, otherwise I have compilation problems with aurelia-validatejs too.
2. continue to have problems with 
`import validate from 'validate.js';`
from **aurelia-validatejs** but I can't find any valid .d.ts for validate.js.
3. generally speaking I have a problem understanding which polyfillers .d.ts to use using es5, because if I add just **es6-promise** as I see in a few samples I have a problem in ts compilation with **Map** and I have to replace es6.promise with core-js
4. using the latest version of aurelia-validation.d.ts I have to comment this
```
import {
  //AccessMember,
  //AccessScope,
  //AccessKeyed,
  BindingBehavior,
  ValueConverter,
  bindingMode
} from 'aurelia-binding';

```
because using the suggested **aurelia-binding** version of the d.ts the Access* exports are not defined
5. I'm trying to follow the instrctions of [new-validation-alpha-is-here](http://blog.durandal.io/2016/06/14/new-validation-alpha-is-here/), but in the .d.ts NewInstance is not declared

**Comment by jdanyow** [comment]
please install the latest version of aurelia-binding and aurelia-dependency-inject-  their d.ts files export the types you've mentioned.
