### ISSUE TITLE
Need support for debouncing

### ISSUE THREAD

**Issue by janvanderhaegen** [aurelia/validation#26]
If a userName property is wired up to an AJAX call for validation, we need debouncing, ie not run while the user is typing but only when the user hasn't changed the value for X ms.

**Comment by zewa666** [comment]
I've used this code snippet quite successfully in other projects where using Lodash/Underscore was not possible/allowed https://www.snip2code.com/Snippet/155226/Vanilla-JS-Debounce-CommonJS-Module

**Comment by janvanderhaegen** [comment]
Added debouncer fb577d0c1acbfafd2ce835c598c5137e8a694850.
The default debounce time is 150ms, can be altered:
```javascript
import {Validation} from 'aurelia-validation';
Validation.debounceTime = 250;
```
