### ISSUE TITLE
Where has IsValid and computedFrom gone?

### ISSUE THREAD

**Issue by ClareBear85** [aurelia/validation#263]
I've googled myself and noted that someone else is asking the same question on SO. 

[(http://stackoverflow.com/questions/37969085/aurelia-validation-replacement-for-isvalid-in-aurelia-validation0-9-2)]

Thanks for any help, really struggling here :-(

**Comment by devanp92** [comment]
@ClareBear85 I believe computedFrom got moved to [aurelia/binding](https://github.com/aurelia/binding/blob/b3e48bf42aa2f545652876b69778fc254ef55c55/src/computed-observation.js). Though I'm not sure abut isValid.

**Comment by ClareBear85** [comment]
@devanp92 So the following code should work minus the config?

```
.ensure('Sku1', (config) => {config.computedFrom(['Sku2', ‘Sku1'])})
            .if(() => { return !this.HasProvidedEitherSku })
                .isNotEmpty().withMessage('a SKU is required')
                .hasLengthBetween(0, 50)
            .endIf()
```

**Comment by janvanderhaegen** [comment]
Just trying to clear up the confusion: computedFrom did not move to aurelia/binding, they were two different things with the same name.

validationConfig.computedFrom allowed you to make sure validation for a particular field was re-evaluated when another field changes (the old validation library by default only triggered validation if the field itself changes)
The API name 'computedFrom' was chosen to match the aurelia/binding @computedFrom annotation, which signaled that bindings on a field should be updated when another field changes.

**Comment by ClareBear85** [comment]
So validationConfig.computedFrom has been removed in the latest version? Is there an alternative? 

A couple of people have mentioned the equality, but I don't get how it actually works.

```
constraints = {
  complexAttribute: {
    equality: {
      message: "a SKU is require",
      comparator: function(v1, v2) {
        return this.Sku1 !== '' || this.Sku2 !== '';
      }
    }
  }
};
```

**Comment by devanp92** [comment]
@janvanderhaegen Thanks for clearing that up!

**Comment by ClareBear85** [comment]
I know this has been closed, but I am still confused as to what the alternative is?
