### ISSUE TITLE
Default validateTrigger

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia/validation#264]
It would be nice if we could globally register the default validateTrigger to use. Perhaps via a plugin callback?

Currently I'm using this hack in main.js with success:
`validateTrigger.blur = validateTrigger.change;`

**Comment by jdanyow** [comment]
that is supported- in the [blog post](http://blog.durandal.io/2016/06/14/new-validation-alpha-is-here/), hit ctrl+f and search for the text `change the validation trigger`.

Apologies- the documentation hasn't caught up with the library yet :(

**Comment by JeroenVinke** [comment]
yes, but can we do this globally? for example at application startup?

**Comment by jdanyow** [comment]
oh

**Comment by jdanyow** [comment]
here's how you would override the default system-wide:
```js
import {ValidationController, validateTrigger} from 'aurelia-validation';
ValidationController.prototype.validateTrigger = validateTrigger.manual;
```
