### ISSUE TITLE
Returning a Promise from validation

### ISSUE THREAD

**Issue by heruan** [aurelia/validation#265]
Why not return a Promise in `ValidationController.validate()`, instead of an array of errors? This would permit to do asynchronous validation (e.g. server-side).

**Comment by EisenbergEffect** [comment]
This is a duplicate. There is a long conversation on this in another thread. Closing for now.

**Comment by heruan** [comment]
If you mean https://github.com/aurelia/validation/issues/252 I missed that since it's a bit more general. I'll follow there, thank you!
