### ISSUE TITLE
Instantiate multiple ValidationController

### ISSUE THREAD

**Issue by ggrimbert** [aurelia/validation#266]
Hi,

I am in the following configuration : 

- a wizard component that integrates multiple viewmodels and displays them one by one by pressing a "next button".
- a BaseWizardViewModel extended by every viewmodel, it contains the ValidationController. 
- 4 viewmodels that extends BaseWizardViewModel

I tried some things with NewInstance and Container, but I get two cases : 
 - the ValidationController is the same for all my views, so it tries to validate some components that are not in the screen.
 - the ValidationController is different for each view, but it contains nothing (no renderer, no property to validate), and so valdiate nothing.

So my question is, how can I create multiple instances of ValidationController, without injecting it ? I don't want to inject it because it's in a base class.

**Comment by jdanyow** [comment]
this was added in friday's release- see docs for details
