### ISSUE TITLE
Promises that finish late are not supported correctly

### ISSUE THREAD

**Issue by janvanderhaegen** [aurelia/validation#27]
Suppose there's an AJAX call to validate a property.
User types "A", AJAX call for "A" is triggered
User types "AB, AJAX call for "AB" is triggered
AJAX call for "AB" finishes early: "AB" is valid.
AJAX call for "A" finishes late: "A" is invalid

Expected result: since the value is 'AB', the property is valid

Actual result: the AJAX call for "A" is the last one to finish and sets the result to invalid

**Comment by zewa666** [comment]
I remember that Rx has a concept like switchLatest, which would only take the last of a series of Ajax calls. See example here http://hueypetersen.com/posts/2013/06/26/helper-functions-for-rx-and-angular/
So we might should look for something similar in VanillaJS.

A first help would be to integrate a debouncer as that would already solve quite a lot of those repeated calls.

**Comment by janvanderhaegen** [comment]
@zewa666 The debounce implementation will be a good start. 

We'll probably need to address this internally too, because there's no guarantee that there are only AJAX calls racing...

For example this is a very common one (happens in the aurelia-validation examples, currently):
User types "A", AJAX call to validate "A" is triggered.
User types backslash, '' is validated as valid because this is not a required field
AJAX call to validate "A" completes, field is marked as invalid.
=> result: '' is considered invalid, even though it was not a required field

Or:
user types "zewa", AJAX call to validate "zewa" as a unique username is triggered
user types "zewa666", rule 'containsOnlyAlpha' turns invalid because there are numbers
AJAX call to validate "zewa" returns with valid status,
=> result: 'zewa666' is marked as a valid username, even though there was a rule that there could not be numbers.

I think we have to think both in the direction of 'debounce: do not validate when the value is continously changing', as well as 'cancelling further validation execution when the value changes', and 'not allowing validation result to be set from rules which executed on a previous value'.

**Comment by zewa666** [comment]
yeah ... you're right. So we have to guarantee that any subsequent call will terminate any previous execution/validation. Since Promises are used for Ajax calls we should be good with canceling them.
