### ISSUE TITLE
Validate radio button group not individual inputs.

### ISSUE THREAD

**Issue by y2k4life** [aurelia/validation#271]
If I do the following there is a blip on the validation.

1. From the Zip Code tab to the Yes & No radio group
2. The individual input Yes has focus, but not checked.
3. Click on No. This will cause a 'blur` event on the Yes input which will cause validation.
4. You will see the validation error blip in the split second going from Yes to No.
5. Then once No is checked the validation passes and the error is removed.

I can understand why my question is can this be fixed and if so how?

![groupradiobuttons](https://cloud.githubusercontent.com/assets/10999532/16541702/5b605262-403f-11e6-9c8c-bbda441da562.gif)

**Comment by y2k4life** [comment]
I just noticed that if I have the focus on the Yes but not checked then move to the right using the cursor key I don't get this behavior.

**Comment by jdanyow** [comment]
would work better using `<yes-no value.bind="multipleLocations & validate"></yes-no>`

**Comment by y2k4life** [comment]
How? What if I did not have a yes-no component? How do I blur on components?

**Comment by jdanyow** [comment]
if you need to validate on blur, and the component that represents your property is made up of two radio inputs, the best thing to do is go ahead and create that yes-no component.

**Comment by y2k4life** [comment]
Can you show in code rather than words? I'm having a hard time wrapping my brain around how to take a group of HTML inputs and know when I leave one those inputs that I'm leaving the component instead of leaving the one of the inputs to another within the component. How would I write the code or what would the code look like that says you have left the component now when to fire a 'blur' event?

**Comment by antonmos** [comment]
for the record, https://github.com/aurelia/validation/issues/271#issuecomment-235113128 worked for me as follows:
```yes-no.html
<template bindable="value">
<label repeat.for="opt of [['Yes', true], ['No', false]]">
<input type="radio" name="b_${field}" model.bind="opt[1]" checked.bind="value"/>${opt[0]}</label>
</template>
```

```parent-template.html
<template>
<require from="components/yes-no.html"></require>
Do you agree?<br/>
<yes-no value.two-way="result & validate"></yes-no>
```

**Comment by antonmos** [comment]
@jdanyow could you please clarify how to fire the 'blur' event?

**Comment by antonmos** [comment]
ah, looks like https://github.com/aurelia/validation/issues/297 is supposed to answer this.  Currently, it only links to a solution when the custom element has one focusable element.

**Comment by antonmos** [comment]
I was able to get it to work by using validateOnChange. yay!

**Comment by jdanyow** [comment]
http://stackoverflow.com/questions/43894214/aurelia-validation-validating-multiple-checkboxes/43896083
