### ISSUE TITLE
Validation preventing rendering of entire site occasionally 

### ISSUE THREAD

**Issue by devteamexpress** [aurelia/validation#274]
> 
<img width="1440" alt="screen shot 2016-07-12 at 8 14 25 am" src="https://cloud.githubusercontent.com/assets/1812255/16755781/d321ad52-4808-11e6-9b60-bb618f28c27f.png">
<img width="1440" alt="screen shot 2016-07-12 at 8 14 39 am" src="https://cloud.githubusercontent.com/assets/1812255/16755782/d3221468-4808-11e6-8e3b-23f948330baa.png">

**Comment by devteamexpress** [comment]
The above happens when trying to load our site occasionally.  Please help us resolve asap

**Comment by EisenbergEffect** [comment]
That version of the validation library isn't supported and we can't fix bugs on that. The code is on a branch for historical resources only. We can accept a pull request to that branch if you solve the issue. From the screenshot, it looks like the team member who wrote that uses the Container.instance, which they should not have used. It's probably not initialized in time. The code should inject the container or get it from the aurelia configuration object instead. Double check the sunset branch and make sure this wasn't already fixed. If not, we'll accept a PR and make a release for you, but we can't address this ourselves at this time.
