### ISSUE TITLE
Is there any validation rule for <select> ?

### ISSUE THREAD

**Issue by martin5575** [aurelia/validation#276]
Hi all,

I wonder, if there is any Validation rule for select boxes? 
Unfortunately the Validation rules for a field bound to a drop down list (i.e. <select> <option>) does not work yet. (I double checked the field names spelling several times... )

Should this feature work already?

-I use validateTrigger.change as Trigger
-I bind the selected field as value (value.bind=...)
-Empty Option has the value ""
-Other Options are bound as model (model.bind=...)

Does anyone have a Suggestion for this issues?

Thanks in advance!
Martin

**Comment by EisenbergEffect** [comment]
If you have a question, please ask it in gitter. If you have a bug, please use the issue template.
