### ISSUE TITLE
Support conditional nested properties

### ISSUE THREAD

**Issue by heruan** [aurelia/validation#277]
Say I have this form:
```html
<form>
    <input value.bind="name & validate">
    <input value.bind="address.street & validate" disabled.bind="!address">
    <input value.bind="address.city & validate" disabled.bind="!address">
</form>
```
where `address` may be `null`; in that case, validation fails with:
```
property-info.js:23 Uncaught Error: The 'address' part of 'address.street&validate' evaluates to null instead of an object.
```
In my opinion it would be better to skip validation instead of throwing.

**Comment by jdanyow** [comment]
Try using `.required().when(obj => obj !== null)`.  Maybe we can add an option for this in the future.

**Comment by jdanyow** [comment]
Thought about this some more- the inputs should be removed using an `if` binding when the object is null otherwise you're going to hit the automatic object creation issue https://github.com/aurelia/binding/issues/205

**Comment by heruan** [comment]
Thank you @jdanyow for the feedback, but the issue triggers when inspecting the binding to find which property to validate, so it's not a matter of `when()`. Also, removing inputs with `if`-binding seems a bit too radical, since I may have an event listener which creates the object on my needs.

In my opinion `property-info` shouldn't fail so hard on `null`/`undefined` since the case may be handled otherwise. That's the reason for https://github.com/aurelia/validation/pull/278, which enables this behavior; do you see any side effect?

**Comment by jdanyow** [comment]
I don't think it's a good idea to data-bind inputs to properties on objects that don't exist. I've recommended against doing that in https://github.com/aurelia/binding/issues/205. As you can see from the number of distinct people involved in that issue- it causes strange issues.

I think the `if` binding is the most bullet-proof way to implement something like this. It eliminates the need for ambiguous logic in both the validation controller and the binding engine itself, giving you more predictable behavior.

**Comment by heruan** [comment]
I see, thank you. I've found a workaround, it works and it may be of help to others:
```html
<form>
    <input value.bind="name & validate">
    <fieldset with.bind="address">
        <input value.bind="street & validate" disabled.bind="!address">
        <input value.bind="city & validate" disabled.bind="!address">
    </fieldset>
</form>
```
Somehow the `with`-binding prevents validation from failing and if `address` is null it stays null, if not it validates as expected.

**Comment by jdanyow** [comment]
when you edit the street/city field, does the value end up being stored on the override context?

**Comment by jdanyow** [comment]
re-opening, at least two other people have run into this.  The current behavior is causing too much confusion.
