### ISSUE TITLE
aurelia.build

### ISSUE THREAD

**Issue by doktordirk** [aurelia/validation#282]
the aurelia build entry for easy webpack (and future aurelia.cli) is missing

**Comment by jdanyow** [comment]
@niieani do you know what is missing? I'm not up to speed on the webpack reqs for plugins.

**Comment by niieani** [comment]
See #291. For future reference, `aurelia.build.resources` need to list all the files that are imported dynamically via Aurelia's loader. Listing them there allows Webpack to automatically add them to the bundle.

**Comment by jdanyow** [comment]
thanks!

**Comment by heruan** [comment]
Is the package name required to be prefixed to `aurelia.build.resources`? I see it's prefixed in other packages, like `aurelia-templating-resources`.

**Comment by niieani** [comment]
@heruan no, you can refer to files directly if they're in the same package.
