### ISSUE TITLE
validate() optimisation

### ISSUE THREAD

**Issue by jsobell** [aurelia/validation#286]
Currently, calls to validate() are added to the end of the Promise chain to ensure they fire in order and wait for any previous validation tasks to complete.
However, if validate() is already in progress, all subsequent validation requests should resolve to the results of the current processing request (so long as the current one is `validate()` and not `validate(propertyOrRule)`).
As such, the subsequent calls should be added to a list of resolves to be called with the result of the current `validate()` Promise chain.
You can see this issue by calling validate five times with a 1000ms rule, and the call takes 5000ms to return, while it should return in 1000ms as calls 2-5 all fall into the same transaction of model checking.
It's also worth noting that we must advise users to lock the model after calling `validate()`, as any changes during this time may or may not be detected by the rules, as we don't snapshot the model and rules may be async.
`validate(propertyOrRule)` calls against the same 'transaction' at the controller scope can also be queued against a running `validate()`'s result, although these are unlikely to occur in practise.

**Comment by jdanyow** [comment]
If subsequent calls to validate() while validation is ongoing are to receive the same result as the initial call to validate, the developer would need to lock the model(s) (disable the inputs), otherwise race conditions would occur.

But if the race conditions are prevented, there's no need to add the logic to make subsequent calls to validate enlist in the current validate task.

**Comment by jsobell** [comment]
The model lock issue always applies. As soon as there's an async rule, the possibility of fields being edited before that rule has resolved is high, hence my comment re 'advise users to lock the model'.
> there's no need to add the logic to make subsequent calls to validate enlist in the current validate task

Do you mean that if they've locked the model, there's no reason to call validate() again?
Perhaps this is an unnecessary optimisation. We'll see :)

**Comment by jdanyow** [comment]
locking the model would lead to strange UI behavior for folks using the `blur` or `change` validate triggers

**Comment by jsobell** [comment]
Sorry, by 'lock the model' I mean prevent the user entering data, i.e. lock the UI.

**Comment by jdanyow** [comment]
with blur- you'd tab to the next field and the inputs would be locked until validation completed- or worse with change you'd press a key and the inputs would lock.

the input locking recommendation would make sense for manual validation though

**Comment by jsobell** [comment]
The lock only applies on final submission, i.e. `validate()`, not `validate(property)`, as the per-field validations are intended as informant rather than 'important', and in theory you could end queuing a list of field-edit validation requests if you have a slow async validation on change in a textbox.
This does mean you have to wait for all field level validations to complete before beginning the full validate() (which means all the outstanding Promises are irrelevant), and is one situation where the ability to cancel pending Promises would have been nice.

**Comment by jdanyow** [comment]
@jsobell can this be closed?

**Comment by jsobell** [comment]
I think so. I'm still not convinced that we won't have some interesting situations when people are running async features and timers, and calling validation, but I'll close it anyway.
