### ISSUE TITLE
Add an ".equals(value)" rule

### ISSUE THREAD

**Issue by eikaramba** [aurelia/validation#298]
I think that is a nice addition as it is a standard validation rule to check if a checkbox is checked or not. This would then just validate whether a boolean is true(valid) or not||undefined(invalid).

A use case is a signup form where the user needs to aggree to the Terms&Condition.

**Comment by eikaramba** [comment]
for now i used a custom rule like this:

```
ValidationRules.customRule(
  'checked',
  (value, obj, bool) => {
    return value === null || value == bool;
  },
  "${$displayName} must be ${bool}.",
  (bool) => ({ bool })
);

........

.ensure('terms').satisfiesRule('checked', true)
```

**Comment by jsobell** [comment]
Or you can simply say
`.ensure(a => a.agree).satisfies(v => v === null || v == true).withMessage('You must agree to the terms')`

**Comment by jsobell** [comment]
Actually, unless I'm missing something...
```
.ensure(a => a.agree).required().withMessage('You must agree to the terms')
```

**Comment by jsobell** [comment]
I was missing something. `required()` considers boolean false to be a value...
Might need to look at that too...

**Comment by eikaramba** [comment]
thx for that, i knew i oversaw something.

**Comment by jdanyow** [comment]
@eikaramba / @jsobell what do you think about:

```js
.ensure(a => a.agree).equals(true).withMessage('You must agree to the terms')
```

Not sure how broadly applicable this will be but it seems like it might be a tiny bit more generic than a "checked" rule.

**Comment by eikaramba** [comment]
i think it is great :)

**Comment by jsobell** [comment]
Sounds good. It will probably only ever be used for `===true`.
Can you think of any other usage scenarios? My first thought was that you could allow an expression... which makes it identical to `.satisfies`.

**Comment by jdanyow** [comment]
lets sit on this one for a while and wait for some additional use-cases.

**Comment by eikaramba** [comment]
well every checkbox where you want it to be checked would be the use case. I guess that is quite a big one actually. but if satisfies() works, i guess it would be enough for now to update the docs and add the example.

**Comment by jsobell** [comment]
This came up again today. We either need a `.true()` or a '.equals()`.
The only other case for `.equals` I can think of is `.equals("I AGREE")` on a text field, and even that's questionable.

**Comment by eikaramba** [comment]
in favor of a more generic solution i would prefer equals(). sure it seems unlikely that this has a real-world impact, but i guess one should better not limit the users expectations here. For example github is making you enter the exact repository name again in a textfield, before the delete button is activated.

**Comment by jdanyow** [comment]
ok, taking this off hold and adding it to the `beta` milestone.
