### ISSUE TITLE
AJAX validation support

### ISSUE THREAD

**Issue by janvanderhaegen** [aurelia/validation#3]
Suggestion by @devmondo (moved from old plugin repository):
i dont know if i missed it or it is not there yet, but AJAX validation is really needed, specially for cases where you want to check duplicate username on server in create account scenarios

thanks in advanced.

**Comment by EisenbergEffect** [comment]
Yep, some sort of way to plugin an async validation rule. Perhaps just understanding promises returned from validation rules will open up all that is needed.

**Comment by janvanderhaegen** [comment]
Q: what is the behavior if checkAll() is called (to get the latest validation status) while a promise is unresolved?
Suggested: property is invalid? What would the error message be?

**Comment by zewa666** [comment]
The property should be invalid in this case I guess. The error message might be something generic like "Async validation couldn't be executed"
