### ISSUE TITLE
Rule prioritization and bailing

### ISSUE THREAD

**Issue by jsobell** [aurelia/validation#301]
We need to be able to specify that the list of rules against a property (or tagged rule-set) should be handled sequentially and fail on the first failing rule.
Example scenario: `.required().satisfiesRule('slowServerSideCheck')`
Do we default to bail (my preferred option) and allow something like `.parallel()`, or default to simultaneous and allow '.sequential()`, `.bail()`, `.bailOnError()` or whatever?

**Comment by jdanyow** [comment]
What if we did this:

* Every property-rule (or object-rule) that results from a call to `.required()`, `.email()`, `.satisfiesRule('slow-server-check')`, etc is assigned a default priority bucket of `0`.
* Developers can override the default priority by calling `.required().priorty(1)`.
* Rules are evaluated in priority bucket order (lowest to highest)
* Rules in a particular bucket are evaluated in parallel (everything in the `0` bucket executes at the same time).
* If any rule in the current bucket is invalid (or throws an unexpected exception), validation is terminated (subsequent buckets will not be evaluated)

This would enable very granular control over the parallelism, sequencing with common-sense bailing.

**Comment by jdanyow** [comment]
Related issue: https://github.com/aurelia/validation/issues/289

**Comment by jsobell** [comment]
I assume each property rules would be independently handled (i.e. not all level 0, then all level 10 across properties), in which case we might as well implement something like a .then() clause that increments the level for all subsequent rules.
i.e.
```
.ensure('startDate')
    .required()
    .then()
    .satisfiesRule('date1') // runs in parallel with:
    .satisfiesRule('date2') // this one
    .then()
    .satisfiesRule('reallyLastRule')
    .on(this);
```

**Comment by jdanyow** [comment]
In the example here: https://github.com/aurelia/validation/issues/301#issuecomment-243916855, everything has a priority of 0 except the property-rule resulting from the `.satisfiesRule('emailUnique')`, whose priority is 100.

**Comment by jsobell** [comment]
Yes, I understand that, but that syntax suggests that the `.priority(100)` applies only to the email rule, so when someone adds `.satisfiesRule('usernameUnique')` (assuming it will follow the emailUnique) it will actually be priority(0), so will execute with the lead rules.

I'm suggesting that the priority number is irrelevant for anything other than ordered 'grouping', and that as such we can achieve an identical but more convention based approach by assigning the priority internally by simply using `.then()` as a group separator. The grouping order (i.e. priority) comes from the index of the `.then` separated block's.
If we keep the idea of `.priority(n)` but retain its state, we can also include a `.then()` that is implemented as simply saying "this FluentEnsure.priority++".

This also brings in the issue of manual rules. At the moment I don't see anything to specify that a rule only applies to manual validation (effectively saying priority(-1)) because we often have some rules that we only want executing on a full validate().
We can either say they have to be allocated in a new rule:
```
.ensure('startDate')
    .required()
.ensure('startDate')
    .manual()
    .satisfiesRule('lastSecondExpensiveCheck') // runs in parallel with:
    .satisfiesRule('lastSecondOtherExpensiveCheck') // this one
```
or we treat the fact that some rules are only used on full validation as being the lowest priority, and exclude them from partial validations.

If we did this by setting priority to -1 (for example) the validation resolver can ignore those rules on all but the full validate(), and we could have a syntax such as
```
.ensure('startDate')
    .required()
    .manual()
    .satisfiesRule('lastSecondExpensiveCheck') // runs in parallel with:
    .satisfiesRule('lastSecondOtherExpensiveCheck') // this one
```
This maintains the conventional order-based priorities, with the only restriction being that you can't then use .priority or .then to append non-manual rules.

What do you think?

**Comment by stefan505** [comment]
I have just encountered the issue with prioritization as well. For example:

```
        ValidationRules
            .ensure((h: Home) => h.email)
            .required()
            .email()
            .maxLength(100)
            .satisfies(this.MayUseEmailAddress)
            .withMessageKey('email-exists')
            .on(this);
```

In the above scenario, I want the `MayUseEmailAddress()` call to only happen once the rules listed before are all satisfied. 

As an alternative for now, I'm thinking of performing `MayUseEmailAddress()` validation "manually", by:

1) Reacting to the bound `email` value changes.
2) Perform `MayUseEmailAddress()` if there's no validation errors.
3) Add the validation result manually if needed using `addError()` on the controller. 

Unless there's another way?

**Comment by jdanyow** [comment]
This is next on the list. It's currently the last remaining item before we move to beta. It looks like your scenario is the same as @jsobell's - you need rule prioritization within an ensure "bucket". All rules in for the email property must be valid before allowing the `.satisfies(this.MayUseEmailAddress)` can be allowed to execute.
