### ISSUE TITLE
Requiring 'NewInstance.of' in @inject(NewInstance.of(ValidationController))

### ISSUE THREAD

**Issue by nano2nd** [aurelia/validation#306]
**I'm submitting a feature request**

* **Library Version:**
0.12.2

* **Operating System:**
Windows 10

* **Node Version:**
5.4.1

* **NPM Version:**
3.3.12

* **JSPM OR Webpack AND Version**
JSPM 0.16.32

* **Browser:**
all

* **Language:**
TypeScript 1.8

**Current behavior:**
You must now include NewInstance.of to get a new ValidationController

**Expected/desired behavior:**
Injecting just the plain ValidationController would always create a new instance by default. Creating a singleton instance would be optional.

* **What is the motivation / use case for changing the behavior?**
I cannot think of a non-rare case where you would want the same instance of the ValidationController throughout the application. As of now, I must use NewInstance.of for every module/form I want to validate within the application.

**Comment by jdanyow** [comment]
To achieve what `NewInstance.of` (or it's alternative, `ValidationControllerFactory`) do, you'd need to write the following code:

```js
import {Container, inject} from 'aurelia-dependency-injection';
import {ValidationController} from 'aurelia-validation';

@inject(Container, ValidationController)
export class MyViewModel {
  constructor(container, controller) {
    container.registerInstance(ValidationController, controller); // this makes the controller discoverable to "& validate", etc.
  }
  ...
}
```

And we'd need to make `ValidationController` transient.

As you can see, it's a lot simpler to write `NewInstance.of` or inject the `ValidationControllerFactory`.  More info in the docs:

http://aurelia.io/hub.html#/doc/article/aurelia/validation/latest/validation-basics/12
