### ISSUE TITLE
controller.validateTrigger=validateTrigger.change is not handling blur

### ISSUE THREAD

**Issue by jsobell** [aurelia/validation#308]
Unfortunately we still need the blur detection for required field handling, so we either need to automatically include blur as a trigger, or allow the user to specify two triggers.

**Comment by jdanyow** [comment]
Apologies- I'm not clear on what you mean here. Please include an example with the gist and a description of the expected behavior.

**Comment by jsobell** [comment]
Sure, the issue is shown here: [https://gist.run/?id=f5725cdc0f807450fe4555794449d851](https://gist.run/?id=f5725cdc0f807450fe4555794449d851)
It's not a bug as-such, it's just highly undesirable.
If you tab over the required fields, no error appears, although as you type it obviously does.
The problem is that people want change events to provide more immediate feedback, and we've removed the most immediate feedback for required fields.

I'm not wild on 'assuming' people also want blur events to be handled, but with 'change' I'm can't think why they wouldn't.

This example was a test of the option binding, and demonstrates nicely why the event type needs to be assignable on a per-component basis. The option doesn't trigger as it changes because there's no blur event, so in theory you need the change event (but only for this field), and strictly speaking you want it to validate on the binding event, as this allows throttle and debounce (which is an issue on option fields if the user holds up/down keys).
This is why I was wondering if the validateTrigger should have the option 'validateTrigger.bind' as its default?

**Comment by jdanyow** [comment]
got it- a `changeOrBlur` validate trigger? would that do it?

**Comment by jsobell** [comment]
Possibly. How will this react with the binding behaviours? Are we doubling up on them?
I know it's a bit weird, but it may be better to have `changeOnly`, for the unlikely event that someone ever wants to *not* catch the blur?
I can see us getting inundated with issues saying that `change` is ignoring required fields...
