### ISSUE TITLE
"Silent" validation?

### ISSUE THREAD

**Issue by RobertHerhold** [aurelia/validation#309]
Would it be possible to have a "silent" validation option where any errors are returned in the Promise from calling `validate`, but any renderers would not be notified or affected in any way? I would like to check if my form input is valid without triggering the error renderers.

**Comment by jdanyow** [comment]
you could use the Validator class directly, to avoid UI side-effects. Just `@inject(Validator)` and then call `this.validator.validate(object)` or `this.validator.validate(object, propertyName)` or `this.validator.validate(object, propertyName, rules)`.

**Comment by jsobell** [comment]
Here's an example Gist:
https://gist.run/?id=2e3195f8d463b06e72f0bd292e7a8b9c
