### ISSUE TITLE
Errors with Date Custom Rule in Documentation

### ISSUE THREAD

**Issue by y2k4life** [aurelia/validation#313]
The example in the [Custom Rules](http://aurelia.io/hub.html#/doc/article/aurelia/validation/latest/validation-basics/9) section for Date do not work.

Below is a link to a gist that demonstrates the errors. On that gist there is a form with two inputs, input A which follows the example in the documentation and B which are proposed changes to fix the issues. Below the link are 3 simple test to compare the differences between A and B along with the results. The big issue is test number 3 even though the date is valid with example A you still get an error message.

https://gist.run/?id=16a95f1011028170fc6d5e200c196314

1) Leave Blank
Sample A - You get two Validation Message, 'Required' & 'Must be date'
Sample B - One Validation Message, 'Required'
2) Enter 'ABC'
Sample A - One Validation Message, 'Must be date'
Sample B - One Validation Message, 'Must be date'
3) Enter '01/01/2016'
Sample A - One Validation Message, 'Must be date'
Sample B - Valid

**Comment by jsobell** [comment]
Same issues as #314 for the same reason.
The Gist you posted has the problem at startup:
```
  startDateA = '';
  startDateB = '';
```
Those are not dates. Use typescript, and you will get an error.
Again, dates are not strings.
If you want to validate that a string is applicable as a date, you could write a custom rule, or even just use a regex expression, but the underlying property would be a string too, not a date.

**Comment by y2k4life** [comment]
I update it to not initialize the fields. I don't want to imply a date, I want the inputs to be blank. So I don't initialize them, I updated the gist. I get the same issue with 1 & 3.

**Comment by y2k4life** [comment]
With my update 1) will not happen, but if you enter a value, then clear it out by way of space(s) or backspace it will. I know this is rare case, but because it can happened there needs to be a guard/check for it. Say a user enters a value then clears it out and then tries to submit the form, then issue 1 still applies even if the fields are not initialized. `f = ''`
I get a date is a date, but how does it go from the form as a string to the validation rule as a date? When is the conversion done?

**Comment by jsobell** [comment]
You have to use a ValueConverter. There's no ambiguity here. If the user applies validation to a jQuery datepicker, it will already be a Date object. The fact that you sometimes use a text field to enter a date is your design choice, and so you need a value converter.
As I said previously, this is a DOM/javascript issue, and is unrelated to the validation rule, and the only complaint might be considered to be one of omission, in that it doesn't mention that if you apply this to a text input field, you will have to convert it into a date object.
The custom rule applies to a *date* field, period. Not a text field that someone subsequently might want to convert into a date field, but a *date* field.

**Comment by y2k4life** [comment]
No reason as to why this was close?
