### ISSUE TITLE
Errors with  Integer Range Custom Rule in Documentation

### ISSUE THREAD

**Issue by y2k4life** [aurelia/validation#314]
The example in the [Custom Rules](http://aurelia.io/hub.html#/doc/article/aurelia/validation/latest/validation-basics/9) section for Integer Range do not work.

Below is a link to a gist that demonstrates the errors. On that gist there is a form with two inputs, input A which follows the example in the documentation and B which are proposed changes to fix the issues. Below the link are 4 simple test to compare the differences between A and B along with the results. The big issue is test number 4 even though the value is valid with example A you still get an error message.

Another issue is the message for A are missing the max value. The message is missing a $, changed from ${config.max} to ${$config.max}.

https://gist.run/?id=8adacec7627d792a304f62a899f21049

1) Leave Blank
Sample A - Two Validation Message, 'Required' & 'integer between 1 and .'
Sample B - One Validation Message, 'Required'
2) Enter 'ABC'
Sample A - One Validation Message, 'integer between 1 and .'
Sample B - One Validation Message, 'integer between 1 and 5000.'
3) Enter '-1'
Sample A - One Validation Message, 'integer between 1 and .'
Sample B - One Validation Message, 'integer between 1 and 5000.'
4) Enter '100'
Sample A - One Validation Message, 'integer between 1 and .'
Sample B - Valid

**Comment by jsobell** [comment]
The `${$config.max}` is indeed a bug, but the parseInt part is not.
The rule applies to number properties, not string, as when it's applied to a numeric property (such as age) it should indeed fail if it contains a string.
In the case of an input field, it's up to you to use a valueConvertor to change it to a numeric value, as an HTML Input tag always returns a string.
This is unrelated to Aurelia as it's a javascript situation that you have to address in any program with a numeric input on-screen.
The reason you get two error messages for blank is for the same reason. At the moment the value is "", which is impossible for a numeric field, so the rule does not check for an empty string in a number property.

**Comment by y2k4life** [comment]
Would it be safe to say that 80 to 90 percent of validation is going to be with forms and therefore the input more than likely will be strings?
I removed the initialization of the fields. I updated the gist. I don't want to assume what the input should be so it should be blank. I still get the error in 1 & 2.
I can I write a single rule that can be using to validate an object with inputs not from a form and a rule from a form.
Because there is nothing to say how they are used would it not be safe to assume that someone would do something like what I did and try to use these validations in a form?
I pulled these form you blog. I agree with what your saying then something need to show how to convert these to the data type and then validation. There is the waffling back and for how how to write validation rules.

**Comment by y2k4life** [comment]
With my update 1) will not happen, but if you enter a value, then clear it out by way of space(s) or backspace it will. I know this is rare case, but because it can happened there needs to be a guard/check for it. Say a user enters a value then clears it out and then tries to submit the form, then issue 1 still applies even if the fields are not initialized. `f = ''`

**Comment by jsobell** [comment]
Same response as #313 . Are numbers typically entered as text in a form? That's not relevant. Validation tests the model field, not the UI input control,
Treating a numeric field as a string is unwise, unsafe, and causes all sorts of problems. If you choose to have `user.age` as a string, that's up to you, and you can modify the example Date Custom Rule to work on strings, but I'd guess everyone else will store it as a number, so the published custom rule applies.

**Comment by y2k4life** [comment]
No reason as to why this was close?

**Comment by lstarky** [comment]
One additional observation... the Gist example integerRangeB does not actually work either.  It validates non-integers like 40.5 and 23.1.  I would suggest changing `Number.isInteger(num)` to `Number.isInteger(1 * value)` to correct this.  The change would need to be in line 44 of app.js.

**Comment by lstarky** [comment]
Also, if I'm not mistaken, the original point of this issue was to correct the documentation so that it would be working.  The documentation as currently posted still does not work.  The easiest correction to the currently posted documentation would be to change:
`|| Number.isInteger(value) && value >= config.min && value <= config.max,`
to
`|| Number.isInteger(1 * value) && value >= min && value <= max,`

Further explanation:
1. Checking Number.isInteger(value) fails in some cases because the value is entered as text on the form.
2. config.min and config.max are incorrect.  The values are passed as simply min and max.

Can someone please double-check this and then update the documentation again here:
http://aurelia.io/hub.html#/doc/article/aurelia/validation/latest/validation-basics/10

Thanks!
