### ISSUE TITLE
ValidationRenderer doesn't indicate when reset is being applied

### ISSUE THREAD

**Issue by jsobell** [aurelia/validation#315]
The transition of invalid->valid is not the same as invalid->untested, and some people want to display a nice green box when a field has been flagged as valid.
Normally, you would add the green box in the renderer's remove method, but that is also called on reset, resulting is a screen of green boxes.
It appears we either need a flag to indicate that the fields are being reset, or we need another property array so we have render, unrender, and reset.

**Comment by jsobell** [comment]
Actually, this is a bit more tricky, as we only unrender elements if they currently have an error.
It looks like we would have to pass 'reset' an array of all of the elements that may have ever been rendered, to allow the user to remove the success flags, unless we retain the success list in the same way as errors.

**Comment by jsobell** [comment]
We also have the issue that nothing is called in the render when a rule passes validation, so after a reset, tabbing over a required field calls the renderer with empty array, while in fact it needs a list of the elements that have just been validated successfully.
https://gist.run/?id=0f88fdb113c4692ebe666b1761036004

**Comment by jsobell** [comment]
Including @narmstrong1988 in this

**Comment by jdanyow** [comment]
Adding to the beta milestone. This is a core use-case that needs to be supported.

**Comment by narmstrong1988** [comment]
Thanks for this guys. I'm really liking the validation library and really looking forward to the beta version coming. The success styling will be great.
