### ISSUE TITLE
validationg only visible fields

### ISSUE THREAD

**Issue by Ma3yTa** [aurelia/validation#317]
How validate only visible input fields? I didn't get response in gitter

**Comment by MikaelPorttila** [comment]
This could be done with conditional validation in the view-model by using .when(statement):

From docs:
``` javascript
ValidationRules
  .ensure('email')
    .email()
    .required()
      .when(order => order.shipmentNotifications)
      .withMessage('Email is required when shipment notifications have been requested.');
```
For documentation check here: http://aurelia.io/hub.html#/doc/article/aurelia/validation/latest/validation-basics/2

I can't find a way to disable the validation from the view, one nice feature would be to have a validat-disable attribute or binding-behavior that could ignore ensures - something like this:

``` javascript
<input type="text" value.bind="model.name & validate" validation-disabled.bind="vmDisablePropertyBoolean">
```

**Comment by Ma3yTa** [comment]
@jdanyow it would be good to have attribute like _validation-disabled_

**Comment by jsobell** [comment]
@Ma3yTa Validation is against the model, not the UI. As such it's not possible to have a model reference the UI while it's validated, as there may well not be a UI there.
If your UI is adapting its displayed inputs based on other properties, those properties must be in the model anyway.
Bear in mind that this whole process is model validation, not UI validation. The UI simply triggers the rules to be checked, and optionally can be used to display the results.
If you really want to ignore a field that is has validation rules against it, either attach it to a different controller and ignore that one, or filter it out of your errors list and ignore the fact there's an error when you call validate().  Is this a good idea? I don't think so, but it depends on your use-case.

**Comment by jdanyow** [comment]
only thing I would add to @jsobell's explanation is there are two ways to enlist your model in validation:

1. via the `& validate` decorator- which tells the controller to validate a specific object/property combination. If you use the `if` binding command to add/remove the input from the DOM it will not be validated while it's removed from the DOM.

2. via the `addObject` method on the controller.  You must call `removeObject` to remove the object from the set of objects to be validated.
