### ISSUE TITLE
aurelia-binding dependency typescript compilation error TS1110 in aurelia-binding.d.ts

### ISSUE THREAD

**Issue by activebiz** [aurelia/validation#319]
**I'm submitting a bug report**

* **Library Version:**
0.12.2

**Please tell us about your environment:**
* **Operating System:**
OSX 10.x|Linux (distro)|Windows [7|8|8.1|10]

* **Node Version:**
6.4.0

* **NPM Version:**
3.10.3

* **Browser:**
all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView

* **Language:**
TypeScript 1.8

**Current behavior:**

```
[typescript] node_modules/aurelia-validation/node_modules/aurelia-binding/dist/aurelia-binding.d.ts(414,10): error TS1110: Type expected.
[typescript] node_modules/aurelia-validation/node_modules/aurelia-binding/dist/aurelia-binding.d.ts(415,22): error TS1110: Type expected.
```

This is related to fix https://github.com/aurelia/binding/issues/487

**Comment by jdanyow** [comment]
aurelia-validation is written in TypeScript 2.0. It will not be back-ported to 1.x like the binding d.ts because the 2.x release is just around the corner.  At the time of this writing they're at RC 2: https://github.com/Microsoft/TypeScript/releases
