### ISSUE TITLE
Strange behavior during route changes...

### ISSUE THREAD

**Issue by jsobell** [aurelia/validation#322]
Reported by @landofjoe
If a route is followed, left, then subsequently re-activated, the validation rules fail to behave as expected.
https://gist.run/?id=3fff92116a50070bb7cbee0f89309654
Replacing the `ControllerFactory.createForCurrentScope()` with `NewInstance.of` works though.

**Comment by jdanyow** [comment]
yikes. this is a serious bug with `ValidationControllerFactory`.
