### ISSUE TITLE
Validation Binding Error with v. ^0.12.3

### ISSUE THREAD

**Issue by alpox** [aurelia/validation#327]
**I'm submitting a bug report**

* **Library Version:**
0.12.4

**Please tell us about your environment:**
* **Operating System:**
Linux KUbuntu

* **Node Version:**
4.4.7

* **NPM Version:**
3.10.6

* **JSPM OR Webpack AND Version**
webpack 1.13.2

* **Browser:**
Chromium

* **Language:**
TypeScript 2.0.2

**Current behavior:**
Since version 0.12.3 I get the following error in my validation binding:
![auswahl_009](https://cloud.githubusercontent.com/assets/12485194/18467236/6fde916a-799f-11e6-8f3b-bcbbfcc4ba9c.png)

Which previously worked well. I went back to version 0.12.2 to test and it worked flawlessly. This error occurs with the versions 0.12.3 and 0.12.4 of `aurelia-validation`.

**Expected/desired behavior:**
Binding a value with the validate binding behaviour which is coupled with a validationController should not throw an error.

**Comment by jdanyow** [comment]
this almost seems like you have multiple versions of aurelia-binding.  I would say execute `jspm inspect --forks` but it you're using webpack.

try executing `npm install aurelia-binding@latest aurelia-templating@latest aurelia-validation@latest --save`

**Comment by alpox** [comment]
@jdanyow didn't expect that. Seems to work now, thank you :smile: I doubt that i had multiple versions of it, i run `npm prune` right after installing the new dependencies, but maybe i had an old version of `aurelia-binding` or templating around.

Can be closed :-)
