### ISSUE TITLE
Conditional validation - sub-objects

### ISSUE THREAD

**Issue by jsobell** [aurelia/validation#332]
So we're seeing the first issue I mentioned re recursive validation requirements.
https://gist.run/?id=6f32a7865a306daa1062e84a10b6c493
@dtaalbers posted this as a requirement to only validate the address if the checkbox is ticked.
So he has a validation on the Driver object, but that is being validated regardless of the when clause, as we can't sensibly add the .when to the child and have it refer to a property in the parent.
Not sure of the right way to approach this...

**Comment by jdanyow** [comment]
In the specific example mentioned in the gist ^^^ I'd do something like this: https://gist.run/?id=419abb8656c1c19395cd1b3aa45bac45

**Comment by EisenbergEffect** [comment]
@jdanyow Can we close this as an answered question or do we need to keep this open to track a feature?

**Comment by jdanyow** [comment]
added a reference to this in the primary issue and closing.
