### ISSUE TITLE
Setting the Validate Trigger based upon properties

### ISSUE THREAD

**Issue by Didd** [aurelia/validation#333]
**I'm submitting a feature request**

* **Library Version:**
1.0.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
4.4.7

* **NPM Version:**
3.10.5

* **AURELIA CLI**
* **Browser:**
Chrome 52.0.2743.116

* **Language:**
ESNext

**Current behavior:**

Currently, 'validationTrigger' applies for all properties. And validation trigger based on properties doesn't seem to be supported. 

**Expected/desired behaviour:**

Besides the current behaviour it would be nice if validation trigger works on property basis. For example, validation  for email property can be triggered on blur rather than on change. On other hand validation for name property can be triggered on change and on blur. Thus the need for validation trigger based on property rather than always applying the same trigger for all properties. 

* **What is the motivation / use case for changing the behavior?**
The main motivation is to enhance user experience. .

**Comment by jdanyow** [comment]
#303
