### ISSUE TITLE
validation-errors custom attribute doesn't seem to pick from addError method

### ISSUE THREAD

**Issue by Didd** [aurelia/validation#335]
It appears validation-error custom attribute is not picking from addError method. In my case I had to hack in to fix it. Any advice on this ?

Here is the detail :- 
 `let error = this.controller.addError("The email you entered is not in our record. Please try again.", ResetPassword, 'email');`

In the above scenario this.emailErrors refers to an array property. Then on the view I have the following :- 
`validation-errors.bind="emailErrors"`

So whenever I wanted to iterate over emailErrors property it shows me that it has no errors while addError has already included errors checked from the server.

As a further info, my validateTrigger happens on 'change' event.

**Comment by jdanyow** [comment]
The second parameter is the object instance that has the error, not the type of the object. I think if you make that change it will work as you expect. Let me know if it doesn't.

**Comment by Didd** [comment]
worked fantastically, changed it to 'this'. Thank you.
