### ISSUE TITLE
Make `npm run test` work on windows

### ISSUE THREAD

**Issue by doktordirk** [aurelia/validation#337]
win 10
 npm -v
3.6.0
 node -v
v5.7.0

```
npm run test
> tsc && ./node_modules/karma/bin/karma start --single-run

'.' is not recognized as an internal or external command, operable program or batch file.
```

`npm run test-watch` works fine

**Comment by Ma3yTa** [comment]
Try npm install concurrently -g

**Comment by doktordirk** [comment]
yeah, that's not it

**Comment by jdanyow** [comment]
The `&&` isn't compatible with windows. I have the same issue because I develop on windows.

Use `npm run test-watch` for the time being.

**Comment by dkent600** [comment]
I'm still having this problem, in Aurelia-validation when I run `npm run develop`.  `npm run test-watch` doesn't exist.

` npm run tests` works fine, but doesn't help when I need to run in a debugger.

**Comment by dkent600** [comment]
The following syntax enables `npm run develop` to work for me:

`"develop": "concurrently \"tsc --watch\" \"karma start\""`
