### ISSUE TITLE
Rule is called twice, calling backend service, so undesirable

### ISSUE THREAD

**Issue by sspilleman** [aurelia/validation#341]
Hi,

Please see code of my constructor below. What I (obviously) want to achieve is that a backend service is only called when the email address is "valid". This works. When the email address is valid though, I see that the backend service is called twice. Am I doing something wrong? Or is this a bug?

BTW, As you can see I implemented my own regex(this._emailRegex) to test for valid email address. Can I also call the standard validation rule? Why do I need to test this again as I also have the email() already in the chain.

Thanks!

Sander

```javascript
	constructor(private userService: UserService, private controllerFactory: ValidationControllerFactory) {
		this.controller = controllerFactory.createForCurrentScope();
		this.controller.validateTrigger = validateTrigger.change;
		validationMessages['passwordmatch'] = `Passwords don't match`;
		validationMessages['alreadyexists'] = `Email already exists!`;

		ValidationRules.customRule('passwordmatch',
			(value, obj) => {
				return obj.password === obj.password2;
			}, validationMessages['passwordmatch']);

		ValidationRules.customRule('alreadyexists',
			(value, obj) => {
				if (this._emailRegex.test(obj.email)) {
					return this.userService.exists(obj.email);
				} else {
					return true;
				}
			}, validationMessages['alreadyexists']);

		ValidationRules
			.ensure('fullname')
			.required()
			.ensure('email')
			.required()
			.email()
			.satisfiesRule('alreadyexists')
			.ensure('password')
			.required()
			.ensure('password2')
			.required()
			.satisfiesRule('passwordmatch')
			.on(this._user);

		setTimeout(() => this.controller.validate(), 500);
	}
```

**Comment by jdanyow** [comment]
Hi @sspilleman, this issue is being tracked here: https://github.com/aurelia/validation/issues/301

**Comment by sspilleman** [comment]
TY! Can you also please answer the question? (Can I also call the standard validation rule? )

**Comment by jdanyow** [comment]
In the next release you'll do this:
```js
ValidationRules
  ...
  .ensure('email')
    .required()
    .email()
    .then()
    .satisfiesRule('alreadyexists')
  ...
```

Which says *validate the required and email rules. If both are valid, validate the alreadyexists rule.*

**Comment by sspilleman** [comment]
Yes, that is what I got indeed. Maybe I was a bit unclear in how I asked the question but... As you can see from my code, I build the regex to validate the email address myself (i test it with the piece this._emailRegex.test(obj.email)). So I implemented te email() rule again and you guys already built it right?. Can I call your/existing validation rule?

**Comment by jdanyow** [comment]
You can use the `Validator` to evaluate rules without causing side-effects in the UI. The `.tag(name)` fluent API feature along with `ValidationRules.taggedRules` enables referencing and evaluating specific rules in the set.

```js
import {Validator, ValidationControllerFactory, ValidationRules} from 'aurelia-validation';

@inject(ValidationControllerFactory, Validator)
export class Foo {
  user = { email: '' };

  constructor(controllerFactory, validator) {
    const allRules = ValidationRules
      .ensure('email')
        .required().tag('xyz')
        .email().tag('xyz')
        .then()
        .satisfiesRule('alreadyexists')
      .on(this.user)
      .rules;
   
    const xyzRules = ValidationRules.taggedRules(allRules, 'xyz');

    validator.validateObject(this.user, allRules).then(errors => ....);
    validator.validateProperty(this.user, allRules).then(errors => ....);
  
    validator.validateObject(this.user, xyzRules).then(errors => ....);
    validator.validateProperty(this.user, xyzRules).then(errors => ....);
  }
```

Does this answer the question?

**Comment by sspilleman** [comment]
Yes! Thanks a lot (again)!

**Comment by sspilleman** [comment]
Sorry for misusing this closed issue thread to ask questions. Now I have this error:

```
Inner Error:
Message: Unable to parse accessor function:
function (a) {
            "use strict";

            return a.data.fullname;
        }
```
thrown by: 

> getAccessorExpression — validation-parser.js:45

I tried THIS (This one doesn't throw the exception, but it just doesn't work):
```
ValidationRules
			.ensure("data.fullname"})
			.displayName('Full Name')
			.required()
```
THIS (Exception)
```
ValidationRules
			.ensure(function (a) {"use strict"; return a.data.fullname; })
			.displayName('Full Name')
			.required()
```
THIS (Exception)
```
ValidationRules
			.ensure(function (a) { return a.data.fullname; })
			.displayName('Full Name')
			.required()
```
AND THIS (Exception)
```
ValidationRules
			.ensure(a => a.data.fullname)
			.displayName('Full Name')
			.required()
```
None of these work.
Bug? Or am I doing something wrong? (again ;-)

Sander
