### ISSUE TITLE
if.bind is not refreshed

### ISSUE THREAD

**Issue by sspilleman** [aurelia/validation#346]
Hi,

I have a custom element "nav-bar", please see snippet below. I would like to hide any items that I can't navigate to. That fact is determined by a (dependency injected) service that checks that based upon the route settings (also see snippet below:

Of course that changes if the for instance the user is logged-in (also done via the userService). It works for the initial page load, only showing items that require no authentication (auth:false).

The nav-bar doesn't change after the user has logged in (ergo, the binding 'doesn't see' the fact that the result of a userService.canNavigateTo() has changed. I would like to prevent from using a signaller that is on a setInterval loop... Feels kinda dirty to me. Is this a bug? Of would you recommend a solution that I haven't thought of maybe?

Thank you!!!!

```javascript
example route:
{ route: 'users', name: 'users', moduleId: './pages/users', nav: true, title: 'Users', settings: { auth: true, role: ['admin'] } }
```

```html
nav-bar template snippet:
<li repeat.for="route of router.navigation" class="nav-item ${route.isActive ? 'active' : ''}">
	<a if.bind="userService.canNavigateTo(route.settings)" class="nav-link"  ref.bind="route.href">${route.title} ${userService.canNavigateTo(route.settings)}</a>
</li>
```

**Comment by sspilleman** [comment]
BTW, I've "solved" this by exposing the (previously private) user object from the userService, add an "updated" date field to it, modify the if.bind clause to "if.bind="userService.user.updated && userService.canNavigateTo(route.settings)" and changing the updated date on successful login... But still feels a bit tricky/hacky though.....

**Comment by jdanyow** [comment]
I recommend restructuring things a little bit: http://stackoverflow.com/a/38743867/725866

Make the `User` something you can `@inject`. Nothing should need to inject the `UserService`, except for your login logic.

With those changes in place your code might change to something like this:

user
```js
export class User {
  role = 'anonymous';
  isLoggedIn = false;
  name = 'Anonymous';
}
```

user-service
```js
@inject(User)
export class UserService {
  constructor(user) {
    this.user = user;
  }
  
  login(username, password) {
    return http.post(....)
      .then(result => {
        if (result.something...) {
           this.user.role = result.role;
           this.user.name = result.name;
           this.user.isLoggedIn = true;
        });
  } 
}
```
nav-bar:
```js
@inject(User)
export class NavBar
  constructor(user) {
    this.user = user;
  }
```
```html
<template>
  <li repeat.for="route of router.navigation" class="nav-item ${route.isActive ? 'active' : ''}">
    <a if.bind=route.settings.roles | contains:user.role" class="nav-link"  ref.bind="route.href">${route.title}</a>
  </li>
</template>
```

Other links that might be helpful: 
* http://stackoverflow.com/questions/35019879/rebuilding-routes-after-refresh
* http://stackoverflow.com/questions/33458274/how-to-switch-between-login-page-and-app-with-aurelia/33458652#33458652

**Comment by sspilleman** [comment]
Thanks!!! Really helpful. Nice one.
