### ISSUE TITLE
New feature: method to refresh display of error messages

### ISSUE THREAD

**Issue by manuel-guilbault** [aurelia/validation#349]
A method on the `ValidationController` that would simply refresh all currently displayed error messages could be useful. When integrating validation with i18n, this could allow to translate displayed messages when the locale changes, without going through the entire validation process (which vallidates the whole scope and can display new messages if some inputs that never had focus before are invalid).

**Comment by jdanyow** [comment]
@manuel-guilbault could you try this and let me know if it achieves the effect you are looking for:

```js
const controller = this.controller;
for (let { object, propertyName, rule } of controller.errors) {
  const rules = [rule];
  controller.validate({ object, propertyName, rules });
}
```

**Comment by manuel-guilbault** [comment]
This is exactly it.
Wouldn't it be interesting to bundle this code in an addition method, maybe something like ```updateErrors``` or ```revalidateErrors```? It would make integrating validation with i18n much smoother.
