### ISSUE TITLE
Change typescript type of `.tag()` from string to any

### ISSUE THREAD

**Issue by jsobell** [aurelia/validation#352]
The tag field is associated with a rule, so there's not really any need specify it as a string, as it can also be used to associate metadata with a rule.
@dkent600 wants to pass a list of associated properties to his renderer for object level rules, and of course this can also apply to property linked rules if they have `(v.obj) => obj.anotherProperty==true`.
If we leave it as type `any` it can also be used for its original intention but with more advanced filtering.

This also (I think) covers https://github.com/aurelia/validation/issues/279#issuecomment-250188672 and https://github.com/aurelia/validation/issues/351

**Comment by dkent600** [comment]
@jsobell Can you please give an example of how a developer would use this to address [279 (comment)](https://github.com/aurelia/validation/issues/279#issuecomment-250188672) and #351?

Thanks

**Comment by jdanyow** [comment]
I don't think tag will solve the two issues but keeping this open for non-string tags.

**Comment by jdanyow** [comment]
Closing- there are some data-binding capabilities I want to add that would enable binding to the validity of a tagged rule. Keeping the tag arg a string will make this easier/more-consistent.
