### ISSUE TITLE
get properties with validation rules fails on if.bind

### ISSUE THREAD

**Issue by jadrake75** [aurelia/validation#353]
**I'm submitting a bug report**

* **Library Version:**
0.12.5

**Please tell us about your environment:**
* **Operating System:**
Windows 10|Linux Centos

* **Node Version:**
6.3.0

* **NPM Version:**
3.10.6

* **JSPM OR Webpack AND Version**
CLI with RequireJS

* **Browser:**
all

* **Language:**
ESNext

**Current behavior:**
If you have a ValidationResult setup on an model in an element and the element is removed from the DOM with a if.bind="some-condition", the validators will attempt to be cleaned up.  However if the model/if is the result of get property, it may not be defined.  Thus the bindings are no longer valid and since the object is manipulated through the get property it does not trigger the modelChanged( ) on the element where in theory the "old" model could be cleaned up

I have put together a simple GIST which highlights this.  In the first case the if.bind is directory on the calculated property whereas the second is against the explicit object.  This is a drastic simplification of my code that simulates what I am seeing.
https://gist.run/?id=0741b16e19a25acf0b7c6a206c77742c

**Expected/desired behavior:**
Not sure exactly, but it would be nice if it handled this case a little cleaner

**Comment by jdanyow** [comment]
adding `@computedFrom('model.submodel')` to the getter solves the issue too

**Comment by bondib** [comment]
**This issue is not only with get properties! It's any time you use if.bind on an object which gets set to null or undefined and used with validation binding.**
Please see:

https://gist.run/?id=41ba422b4a16bd28aa291a3d11a724c7

**Comment by jdanyow** [comment]
related to #277
