### ISSUE TITLE
New feature: additional way to set displayName for property when creating ValidationRules

### ISSUE THREAD

**Issue by valichek** [aurelia/validation#355]
My intention is to have customizable translation of property names depending on validated model.
It could be smth like:
```javascript
ValidationRules.ensure('myProp').on(target).setDisplayName((propertyName) => {
  return i18next.t(propertyName);
})
```

**Comment by jdanyow** [comment]
check out the [customizing messages](http://aurelia.io/hub.html#/doc/article/aurelia/validation/latest/validation-basics/3) section in the docs.  There's an example showing how to override `getDisplayName`.

**Comment by jdanyow** [comment]
Also related: https://github.com/aurelia/validation/issues/328

**Comment by valichek** [comment]
@jdanyow setting `getDisplayName ` on MessageProvider is useful but too global.

**Comment by jdanyow** [comment]
ok- this sounds like it's a duplicate of #328 - please add any thoughts/use-cases there.

Thanks!
