### ISSUE TITLE
Missing Tasks

### ISSUE THREAD

**Issue by jdanyow** [aurelia/validation#357]
- [x] [prepare release task (bump version, changelog).](https://github.com/aurelia/binding/blob/master/build/tasks/prepare-release.js) :fire:
- [x] lint task (need to add tslint) :fire:
- [x] doc task: api.json generation is broken. [typedoc does not yet support typescript 2.0](https://github.com/TypeStrong/typedoc/issues/234) :fire:
- [ ] doc task missing the ability to [build examples](https://github.com/aurelia/binding/blob/master/build/tasks/doc.js#L53)
- [ ] [dev tasks](https://github.com/aurelia/binding/blob/master/build/tasks/dev.js) are missing

**Comment by niieani** [comment]
As for the Release Task, I'd go back to proposing [semantic-release](https://github.com/semantic-release/semantic-release) instead. If we can agree on a time and date I can do a screencast to show the interested parties (CC: @EisenbergEffect) how it works and why it's a simpler/better/faster workflow than doing manual releasing.

**Comment by PWKad** [comment]
Is there a preference for how these should be implemented?  If not then we can port over the associated gulp tasks to handle those scenarios.  If the idea is to keep them as npm scripts then perhaps more discussion is needed.

**Comment by AdamWillden** [comment]
As everything in aurelia is already using eslint, that would be my preference to use. I was just wondering if you were aware of this:

https://github.com/eslint/typescript-eslint-parser
https://github.com/nzakas/eslint-plugin-typescript

They have made tremendous progress over the last month from what I can see, although it is unfortunately still early days. There was something about tslint I wasn't such a fan of but couldn't quite put my finger on!

**Comment by niieani** [comment]
TypeDoc is 2.0 ready now.

**Comment by niieani** [comment]
@AdamWillden I'm aware of the TypeScript eslint plugin, it's awesome. I'd be happy to switch as soon as they mature a bit more if the rest of the team is okay with it.

**Comment by jdanyow** [comment]
I've been using tslint for TypeScript projects. Is there a compelling reason why eslint would be used instead of tslint?

**Comment by AdamWillden** [comment]
There's no good reason, it's probably just due to familiarity with eslint. Is there a tslint config in the works for aurelia? ...like the eslint one exists in `aurelia-tools`.

I also thought you could use the existing eslint config and extend it for typescript rather than maintaining two different linting configurations.

**Comment by niieani** [comment]
Yeah, that's the main reason - you get less maintenance, since you can keep the JS eslint config just adding the TS-specific options. I think eslint has a better extensibility story too. But yeah, it's not production-grade yet, so we should keep tslint for the time being.

**Comment by MeirionHughes** [comment]
If this is to be the de facto standard for the rest of the repos, have you considered changing the specs to typescript as well and also enabling breakpoint debugging of them (the specs).  I do this myself in https://github.com/aurelia/pal-nodejs . Personally, I find it extremely productive to be able to click on any source file to add a breakpoint and press f5 to build and test the library.

**Comment by jdanyow** [comment]
@MeirionHughes - the tests are written in TypeScript.

re: breakpoints - in my experience with this package and other packages, I'm typically debugging in the context of a broken test case, using the chrome instance launched by karma. I'm definitely willing to try a new approach. Do you want to tackle this in another issue/PR- I'm interested in seeing what you're doing.

**Comment by MeirionHughes** [comment]
Sorry, you replied before I could edit my comment. :D

I've mostly been doing my specs in the node process. In theory you can use https://github.com/Microsoft/vscode-chrome-debug extension to the same effect though for client stuff. Or you could use pal-nodejs to load up aurelia's libs directly in the nodejs process and do your testing there. 

I will have a play with both options.

**Comment by niieani** [comment]
TypeScript 2.1 was released yesterday, it might be good to use that as a base as it further improves upon many things (I've updated the skeleton to use it). It also means we can use await-async in the repos without worrying about performance with old targets, including es5.

**Comment by niieani** [comment]
I've worked on this a bit, I've put both the TS build and the doc build tasks into the aurelia-tools repo. I've also added a release task which generates the changelog and bumps the version.

**Comment by jdanyow** [comment]
closing- new typescript plan from meeting a few weeks ago supercedes this

**Comment by RichiCoder1** [comment]
I'm curious what the new typescript plan is?

**Comment by alastair-mcdonald** [comment]
Me too

**Comment by Gheoan** [comment]
By looking at https://github.com/aurelia/tools/pull/51 I think the plan is to have a single build tool (that uses typescript) for all aurelia libraries instead of each library having a separate build system.
