### ISSUE TITLE
ValidationController.addRenderer() use case issue

### ISSUE THREAD

**Issue by zeko77** [aurelia/validation#358]
**I'm submitting a bug report**
- **Library Version:**
  0.13.1

**Please tell us about your environment:**
- **Operating System:**
  Windows [10]
- **Node Version:**
  6.2.0
- **NPM Version:**
  3.10.3
- **JSPM OR Webpack AND Version**
  JSPM 0.16.46
- **Browser:**
  all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView
- **Language:**
  all

**Current behavior:**
According to documentation, it is recommended that
validationController,addRenderer(new BootstrapFormRenderer()); is executed in constructor of viewmodel. As validationController is singleton, renderer is added each time view is navigated to, resulting in multiple error messages during validation. Even if renderer is removed in view's deactivate method, removal can still be bypassed with aurelia.setRoot(), which makes this kind of renderer garbage-collection inconvenient

**Expected/desired behavior:**
Every validation error should be rendered only once, no matter how many times the view is created/navigated to.

I have managed to bypass this issue in main.js by importing

import {ValidationController } from 'aurelia-validation';
import {BootstrapFormRenderer} from 'common/bootstrap-form-renderer';
import {Container} from 'aurelia-dependency-injection';

and

aurelia.start().then(() => {
          Container.instance.get(ValidationController).addRenderer(new BootstrapFormRenderer());
            aurelia.setRoot("shell");
        });

**Comment by jdanyow** [comment]
try adding and removing the renderer in `attached` and `detached` since those are guaranteed to be called (as opposed to `activate` and `deactivate` which might not be called if something like `setRoot` is used).

**Comment by zeko77** [comment]
This works as expected. What about when i have a edit-dialog over edit form? 
Validationcontroller is singleton, and if i tryto validate dialog model only, validtion on form below is triggered also. Can controller be instantiated per view-model basis?

**Comment by jdanyow** [comment]
a view-model can have one or more of it's own validation controllers

**Comment by jdanyow** [comment]
added a note in the docs that says to remove the renderer in unbind/detached if you added the renderer in attached/detached.
