### ISSUE TITLE
Not working with i18n

### ISSUE THREAD

**Issue by lstarky** [aurelia/validation#364]
**I'm submitting a bug report**
- **Library Version:**
  0.13.1

**Please tell us about your environment:**
- **Operating System:**
  Windows 10
- **Node Version:**
  4.6.0
  
  
- **NPM Version:**
  3.10.8
  
  
- **JSPM OR Webpack AND Version**
  Neither
  
  
- **Browser:**
  Chrome Version 53.0.2785.143 m
- **Language:**
  ESNext

**Current behavior:**
I have aurelia-validation working fine, but when I try to integrate it with aurelia-i18n so that the error messages can be translated, following the directions on the Hub Doc (http://aurelia.io/hub.html#/doc/article/aurelia/validation/latest/validation-basics/12), it doesn't work.  The error I get is `vendor-bundle.js:3394 Error: key/value cannot be null or undefined. Are you trying to inject/register something that doesn't exist with DI?(…)`

When I change to `const i18n = aurelia.container.get(I18N);`, the app loads but all of the i18n services stop working.

**Expected/desired behavior:**

I have posted this issue with my actual main.js code at:
http://stackoverflow.com/questions/40120143/aurelia-validation-with-i18n/40120848

- **What is the expected behavior?**
  The official Aurelia documentation should be updated to reflect a complete working example of integration of aurelia-validation and aurelia-i18n.
- **What is the motivation / use case for changing the behavior?**
  I want the validation error messages (like "First Name is required.") to be translated into the current localization language.

I see that other users are having the same issue.  See:
https://gitter.im/aurelia/validation?at=572cb91a12fa465406ea7e52

**Comment by EisenbergEffect** [comment]
@jdanyow There may be a clarification needed in the docs. Can you take a look?

**Comment by jdanyow** [comment]
I see what's happening- we can't use `container.get(I18n)` until after the i18n plugin has executed this line:

https://github.com/aurelia/i18n/blob/master/src/aurelia-i18n.js#L19
