### ISSUE TITLE
ValidationRenderer is not receiving any elements when view has @singleton(registerInChild=false)

### ISSUE THREAD

**Issue by dkent600** [aurelia/validation#365]
**I'm submitting a bug report**

* **Library Version:**
0.12.5

* **Operating System:**
Windows 10

* **NPM Version:**
3.10.3

* **JSPM OR Webpack AND Version**
JSPM 0.16.46

* **Browser:**
all 

* **Language:**
TypeScript 2.0.3

**Current behavior:**
1)  Create two views with associated viewmodels (I will attached the entire code).
2)  Apply each viewmodel the decorator `@singleton(false)` (I will attached the entire code)
3)  Navigate to the first view.  Note that validation is working
4)  Navigate to the second view, note that validation is not working.  This is because the ValidationRenderer is not receiving any elements in the render instruction.

**Expected/desired behavior:**
4)  Navigate to the second view, and validation should be working.  ValidationRenderer should be receiving elements in the render instruction.

* **What is the expected behavior?**
See above

* **What is the motivation / use case for changing the behavior?**
My application uses aurelia-validation and `@singleton(false)`   (until Aurelia releases the ability to cache views in the router)

**Comment by dkent600** [comment]
[view+viewmodel.zip](https://github.com/aurelia/validation/files/539192/view.viewmodel.zip)

**Comment by dkent600** [comment]
If I had to guess, I'd say that this is related to how ValidationController.createForCurrentScope() registers the returned controller instance in the current container.  Perhaps the two transient views share the same container?

**Comment by dkent600** [comment]
Also happens in validation version 0.13.1

**Comment by dkent600** [comment]
I find I am able to work around all of the issues surrounding this with the code I'm attaching below.  The changes are:

1)  use:

    `this.controller = container.get(ValidationController)` 

instead of:

    `this.controller = controllerFactory.createForCurrentScope()`

2)  add and remove the renderer in bind() and unbind().

3)  do a `controller.validate()` in bind() (after the first time)

Example code:

[views.zip](https://github.com/aurelia/validation/files/544716/views.zip)

**Comment by jdanyow** [comment]
@dkent600 I can look into this if you can setup a reproduction using this validation gist: https://gist.run/?id=3625244afe4f188785190b23f2e7f472

**Comment by dkent600** [comment]
@jdanyow  Try [this gist](https://gist.run/?id=15327a8bd5e74c7b8a757ef516a09d9b)

**Comment by jdanyow** [comment]
The magic automatic wireup of bindings with the validation controller is not compatible with view-models that are singletons registered in the root container (via `@singleton(registerInChild=false)` ). The automatic wireup relies on the standard process where viewmodels are instantiated in child containers.

If you're using `@singleton(false)` on your viewmodels you'll need to specify the controller instance in your bindings (`value.bind="firstName & validate:controller"`).

**Comment by dkent600** [comment]
@jdanyow Would I be correct in assuming that the best solution for this will be when aurelia enables us to cache views?

**Comment by jdanyow** [comment]
yep- unbind is what causes the validation errors, etc to unrender. Cached view+viewmodel pairs are not unbound, so the validation state will be preserved along with the rest of the state.

https://github.com/aurelia/router/pull/425
