### ISSUE TITLE
bug(validation) two controllers on a page, only one works

### ISSUE THREAD

**Issue by dkent600** [aurelia/validation#367]
**I'm submitting a bug report**

* **Library Version:**
0.13.1

* **Operating System:**
Windows 10

* **NPM Version:**
3.10.3

* **JSPM OR Webpack AND Version**
JSPM 0.16.46

* **Browser:**
all 

* **Language:**
TypeScript 2.0.3

**Current behavior:**
1)  see attached view and viewmodel.  There are two identical forms on the page, each validated by a different validaitoncontroller.
2) click the first form's Submit button
Result:  Validation looks fine
3) click the second Submit button
Result:  Validation is attempted, but renderer does not receive the form's elements, thus no validation error messages appear in the GUI

**Expected/desired behavior:**
In step 3) renderer should be receiving elements in the render instruction.

**What is the motivation / use case for changing the behavior?**
My application contains pages with multiple forms that require validation

Example code:
[code.zip](https://github.com/aurelia/validation/files/544827/code.zip)

**Comment by dkent600** [comment]
Phew, ok, github is back.  I have figured out how to do this:

1) Use a single ValidationController for the entire page
2) Add a single ValidationRenderer for the entire page
3) Validate each form individually.

Note that `ValidationControllerFactory.createForCurrentScope` returns a singleton in any case.  Thus steos two and three, above, are the keys to this.

Having figured out that this is not a bug, but rather a misunderstanding of how the validation framework works, I will close this issue.

**Comment by jdanyow** [comment]
@dkent600 you could also use `ValidationControllerFactory.create()` to create two controllers. Assuming you expose those on your vm with properties `controller1` and `controller2` you would then explicitly wire up your bindings to the appropriate controller like this: `<input value.bind="foo & validate:controller1">` and like this: `<input value.bind="foo & validate:controller2">`.

`createForCurrentScope` makes it possible for the `validate` binding behavior (and friends) to retrieve the controller from the container.

**Comment by dkent600** [comment]
ah, thanks, i didn't realize one could supply a controller to the binding like that, but I see it *is* documented.  :-P    Good thinking!

This is a good feature because it allows us to supply a separate renderer for each form at the same time.
