### ISSUE TITLE
feat(validation) `ValidationRules.customRule` message parameter take a function, eliminate third parameter

### ISSUE THREAD

**Issue by dkent600** [aurelia/validation#368]
I would like to propose that the `ValidationRules.customRule` message parameter take a function, just like the rule evaluation does (or function|string).  Then eliminate the awkward final parameter and the config object.  

Instead of this:

```
ValidationRules.customRule(
  'integerRange',
  (value, obj, min, max) => ... ,
  `\${$displayName} must be an integer between \${$config.min} and \${$config.max}.`,
  (min, max) => ({ min, max }) 
);
```

Rather this:

```
ValidationRules.customRule(
  'integerRange',
  (value, obj, min, max) => ... ,
  `(value, obj, min, max) => { `\${$displayName} must be an integer between \${min} and \${max}.`,
);
```

**Comment by dkent600** [comment]
Or this:

```
ValidationRules.customRule(
  'integerRange',
  (value, obj, min ) =>{ 
        evaluator:  () => { return value >= min }, 
        message: `\${$displayName} must be an integer between \${min} and \${max}.`
    });
```

**Comment by jdanyow** [comment]
@dkent600 how would this work?

**Comment by dkent600** [comment]
@jdanyow  Before I spend time trying to answer your question, can you tell me whether you are aware of any particular challenge to it?

**Comment by jdanyow** [comment]
Just looking for more info on how you think this should be implemented. It wasn't clear to me from looking at the pseudo code you provided how this would be achieved.

Here's some info on how it works today:

`customRule` takes four args:

1. name of the rule
2. function to evaluate the rule
3. message template
4. function that takes the rule's custom parameters and produces a config object that can be accessed in the message template.

When you use a custom rule via the fluent API the function to create the config object (\#4) is evaluated to capture the rules configuration.

When a validation error is discovered the message template is used in conjunction with the captured configuration, object, display name, property and some other stuff to produce the message.

**Comment by dkent600** [comment]
OK, thanks!

I presented two options:

A)  replace args 3) and 4) with a single arg which would be a function that returns the message template.  The function would take the same arguments as in 2).  Optionally this new arg could also be provided as a string.

B)  replace args 2) 3) and 4), with a single arg that would be a function that returns an object like this:

```
(value, obj, min ) =>{ 
        evaluator:  () => { return ....  value >= min }, 
        message: `The value for \${$displayName} must be at least ${min}.`
    });
```

**Comment by Beijerinc** [comment]
If I may, I'm having trouble creating a custom rule that exposes a dynamic error message. I'm probably doing this wrong, but I'm trying to make a rule that takes a function and outputs a boolean that indicates whether it is valid or not. If an error occurs, that error is the validation message. (It's actually a service call, but that doesn't really matter.)

Right now, I have to do this to get it somewhat working, but as you can see it's not ideal:
```
ValidationRules.
	customRule("serviceCall",
		(value: any, object: any, serviceCallResult: ServiceCallDelegate, propertyName?: string) => {
			// Remove the previously generated error or we just keep adding new ones.
			if (this.previousServiceCallError) {
				this.validationController.removeError(this.previousServiceCallError);
				this.previousServiceCallError = null;
			}

			// Don't validate stuff that is not yours to validate.
			if (value === null || value === undefined) {
				return Promise.resolve(true);
			}

			// Perform the call and result in true or false to indicate validity. If something went wrong, add the error as a validation error.
			return serviceCallResult(value, object).
				then(x => x).
				catch(x => this.previousServiceCallError = this.validationController.addError(x.message, object, propertyName)).
				then(x => false);
		},
		// The custom rule doesn't have a predefined validation error. Passing 'null' here crashes it on some indexOf call it tries to do, presumably to check if it needs to replace parameters in the error message.
		"");
```
It seems to me that option B by @dkent600 comes close to supporting this scenario as well. If the evaluation of the rule could somehow return the error message, it would be much more dynamic. And if you always want to return the same message with variable parameters, you could simply return a constant string every time.

This might go against the concept of single rule evaluation, since you could use a single custom rule to validate everything you'd need to and return a different error message for every failed evaluation...

**Comment by dkent600** [comment]
@Beijerinc I'm not sure 100% sure that this would work in javascript, but if so, it might be the way to make option B work for your case: 

```
(value, obj, min ) =>{ 
        errorCode: any,
        evaluator:  () => { 
            let isValid:boolean = [...];
            this.errorCode = [...];
            return isValid;
        }, 
        message: `\${$displayName} is not valid: ${this.errorCode}.`
    });
```

**Comment by EisenbergEffect** [comment]
A feature to add or are we good to close this? @jdanyow

**Comment by jdanyow** [comment]
@dkent600 it's still not clear to me how these would work. I do agree the `ValidationRules.customRule` API is a little awkward and would like to improve it if there's an idea that will work within the constraints we have.

If I understand your suggestion correctly, this change would force people do define a new custom rule for every min/max value they need to validate.

When thinking about how to refactor this, make sure the `.satisfiesRule('integerRange', 1, 100)` side of things is also considered.

**Comment by dkent600** [comment]
@jdanyow No problem.

This is what I like the best (in typescript), I hope it is more clear:

Suppose you declare customRule and ICustomRuleConfig as follows:

```
static customRule(name: string, config: (value: any, obj?: Object, ...constraints: any[]) => ICustomRuleConfig): void;

interface ICustomRuleConfig {
    evaluator: () => boolean;
    message?: () => string;
}
```

then call it as follows:

```
ValidationRules.customRule(
            'min',
            (value, obj, min) => {
                return {
                    evaluator: (): boolean => {
                        return value !== null && value !== undefined && value >= min;
                    },
                    message: (): string => {
                        return `The value for \${$displayName} must be at least ${min}.`;
                    }
                }
            });
```

**Comment by dkent600** [comment]
A cleaner alternative, that would eliminate the ICustomRuleConfig  config object:

```
static customRule(name: string, 
    evaluator: (value: any, obj?: Object, ...constraints: any[]) => boolean,
    message: (value: any, obj?: Object, ...constraints: any[]) => string): void;

ValidationRules.customRule(
            'min',
            evaluator: (value, obj, min) => {
                        return value !== null && value !== undefined && value >= min;
                    },
             message: (value, obj, min) => {
                        return `The value for \${$displayName} must be at least ${min}.`;
                    }
            });
```

**Comment by jdanyow** [comment]
I see what you mean now- I don't really like the mixed escaping of the interpolation expressions in the message that this kind of change would introduce.

**Comment by dkent600** [comment]
I personally don't like the escaped bit at all.  Ideally I would want to find a way to eliminate it.

How about something like this:

```
ValidationRules.customRule(
            'min',
            evaluator: (value, obj, min) => {
                        return value !== null && value !== undefined && value >= min;
                    },
            message: (value, obj, context, min) => {
                        return `The value for ${context.displayName} must be at least ${min}.`;
                    }
            });
```

**Comment by EisenbergEffect** [comment]
@jdanyow I leave this decision up to you. However, if you take @dkent600's idea, I think the parameters should be in the same order if possible. If that's not possible, then lets make sure to have clear documentation on how/why it's that way.

**Comment by jdanyow** [comment]
The other approaches involve more closures and do not significantly improve the clarity of the API (this is subjective of course, just my opinion here :smile:). Closing this because v1 has shipped and I don't want to introduce a big breaking change like this for a while.
