### ISSUE TITLE
ValidationController.validate instance works differently depending on whether addObject has been called

### ISSUE THREAD

**Issue by dkent600** [aurelia/validation#369]
I might be reporting a bug here, but am not sure.  The behavior is not what I would expect.

Suppose I want to validate an object instance.  

I can call:

```
ValidationController.addObject(instance);
ValidationController.validate();
```

^^^ this works fine

Or I can call:

```
ValidationController.addObject(instance);
ValidationController.validate({ object: instance });
```

 and this works too.

Or I can call:

`ValidationController.validate({ object: instance })`

without calling `ValidationController.addObject(instance)`

This ^^^ doesn't work.  The validation renderer gets all out of sync when revalidating the same instance repeatedly.  One ends up with validation errors not being unrendered when they should.

My expectation is that the latter case would work fine, that calling `addObject` is only meant to be a convenience so that `ValidationController.validate` can be used to validate all instances that have been added, and that `addObject` would not be required if one is willing to call `ValidationController.validate({ object: instance })`.

**Comment by dkent600** [comment]
See [this gist](https://gist.run/?id=407d4dd99a6dd4e4018b4af3464ecff3).  Just press the Submit button more than once and see then validation errors accumulate.

**Comment by jdanyow** [comment]
thanks for the gist- was able to track this down.  It's fixed in https://github.com/aurelia/validation/commit/d57f09ff35de4a2d95cef037ba008678e2d01636 

I'm keeping this open and will re-test with the updated build when it's released.
