### ISSUE TITLE
validation does not work when value is bound using expression like "currentEntity[p] & validate"

### ISSUE THREAD

**Issue by antonmos** [aurelia/validation#371]
**I'm submitting a bug report**

* **Library Version:**
aurelia-validation@0.13.1

**Please tell us about your environment:**
* **Operating System:**
OSX 10.x
* **Node Version:**
6.3.0

* **NPM Version:**
3.10.3

* **JSPM OR Webpack AND Version**
JSPM 0.16.46

* **Browser:**
all 
* **Language:**
all 

**Current behavior:**
per http://aurelia.io/hub.html#/doc/article/aurelia/validation/latest/validation-basics/6, i should be able to use a binding like this 
```
 <input type="text"   value.bind="model[field] & validate">
```

Binding does work but there appears to be no way to define a rule that will fire.

**Expected/desired behavior:**

binding doenst work, ask demonstrated in the gist: https://gist.run/?id=44ecfbe8b7693ee6975d4f91f2d9150a

* **What is the expected behavior?**
validation should work correctly

**Comment by jdanyow** [comment]
@antonmos here's a working version: https://gist.run/?id=90812aab71ad6e131406b2a99ac9c5ea

Here are the two small changes I made to correct the issues with the usage of `.ensure(...)` and the data-binding:  https://gist.github.com/jdanyow/90812aab71ad6e131406b2a99ac9c5ea/revisions

**Comment by jdanyow** [comment]
@antonmos here's a working version: https://gist.run/?id=90812aab71ad6e131406b2a99ac9c5ea

Here are the two small changes I made to correct the issues with the usage of `.ensure(...)` and the data-binding:  https://gist.github.com/jdanyow/90812aab71ad6e131406b2a99ac9c5ea/revisions

**Comment by antonmos** [comment]
@jdanyow thank you for the workaround!!
However, i think either documentation needs to be updated or there is a bug.  The documentation explicitly claims that ` <input type="text"   value.bind="model[field] & validate">` should work.
I updated my gist to demonstrate that it doesnt when using the `.on(this)` syntax.

**Comment by jdanyow** [comment]
@antonmos you might have not seen the second change in my fork of your gist, this part was invalid:

```
.ensure("model[field]") 
```

needs to be:
```
.ensure("my-email") 
```

Once you fix that your gist will work.

**Comment by antonmos** [comment]
I did see it and thank you. My point is that the documentation says that validation should work with *dynamically* selected fields and *without* having to use "Explicit Binding Validation". 

I updated the gist to reflect this usecase.

from: http://aurelia.io/hub.html#/doc/article/aurelia/validation/latest/validation-basics/6
```
The binding behavior is able to identify the object and property name to validate in all sorts of binding expressions:

Automatic Binding Validation Copy
HTML
<input type="text" value.bind="firstName & validate">

<input type="text" value.bind="person.firstName & validate">

<input type="text" value.bind="person['firstName'] | upperCase & validate">

<input type="text" value.bind="currentEntity[p] & debounce & validate">
```

Thanks again!

**Comment by jdanyow** [comment]
Right but the docs don't say anything about using `.ensure` the way you've attempted:

`.ensure("model[field]")` and `.ensure(`model['${this.field}']`)` are invalid because they don't target a specific property.

Maybe what you're looking for is `.ensure(this.field)` ?

**Comment by antonmos** [comment]
That works, if i setup the rules in the constructor instead of in the module scope and use `.on(this)`.
This all makes sense now.   Thanks again!

**Comment by vermilion** [comment]
Hi, @jdanyow !
I'm having trouble with your gist https://gist.run/?id=90812aab71ad6e131406b2a99ac9c5ea

When typing something -> blur -> clear -> blur > type -> blur i get validation errors stacked but as normal they shouldn't
![image](https://cloud.githubusercontent.com/assets/2167823/19855392/5f41e814-9f85-11e6-9e79-e3efb4109bf1.png)

Need fix for this asap, thanks in advance!
