### ISSUE TITLE
Validation Documentation typo #2

### ISSUE THREAD

**Issue by rajajhansi** [aurelia/validation#374]
Under "Displaying Errors" section:

"The validation-errors custom attribute is implements the ValidationRenderer interface". should be 
"The validation-errors custom attribute implements the ValidationRenderer interface."

"It also automatically add itself to the controller using addRender when its "bind" lifecycle..." should be
"It also automatically add itself to the controller using addRenderer when its "bind" lifecycle..."

**Comment by dkent600** [comment]
Or:

"It also automatically add**s** itself to the controller using addRenderer **during** its "bind" lifecycle..."

**Comment by rajajhansi** [comment]
@dkent600 My bad. It reads as "adds" in Dochub :) I introduced that typo :) The real typo was addRender.

**Comment by jdanyow** [comment]
@rajajhansi thanks for the review! Any chance you'd submit a PR to correct this? There's an edit link at the top of the doc:

![edit](http://i.imgur.com/lLvaQHb.png)

**Comment by rajajhansi** [comment]
@jdanyow Done. https://github.com/aurelia/validation/pull/380
