### ISSUE TITLE
Cannot find 'aurelia-validation' module

### ISSUE THREAD

**Issue by bowczarek** [aurelia/validation#379]
Hi,
**I'm submitting a bug report**
I guess it's a bug, if not please prove me wrong, would be more than happy ;) I cut the issue template a bit because my rig specification is irrelevant.
- **Library Version:**
  0.13.1
- **Language:**
  TypeScript 2.0+

**Current behavior:**
Can't import 'aurelia-validation' module, example:
`import { ValidationRules } from 'aurelia-validation';`

The reason is that there's no single ambient module declaration in any of `*.d.ts` files in a distribution package, like before the plugin 'merge' there was such definition in aurelia-validationjs, take a look at https://github.com/aurelia/validatejs/blob/master/lib/validatejs.d.ts. So if you follow [aurelia validation documentation](http://aurelia.io/hub.html#/doc/article/aurelia/validation/latest/validation-basics/1) then you just can't import module. To make it work I have to include sources directly, unless I'm missing something.

I don't like also the way that `*.d.ts` files are inside the distribution package, like aurelia used to have in some early versions. I guess it would be better to keep only transpiled code in a distribution package and `*.d.ts` should be manage by typings manager (outside of distribution package).

**Expected/desired behavior:**
There should be an ambient module declaration for 'aurelia-validation' plugin.

**Comment by jdanyow** [comment]
Sounds like you have a problem with your setup.

* What does your tsconfig look like- especially the module resolution setting? 
* How are you installing your dependencies? npm? jspm?
* What editor are your using?
* Are you using typings, tsd or the new `@types`?

**Comment by bowczarek** [comment]
Hi Jeremy, thanks for reply.

- Basically, it's aurelia skeleton so module resolution is 'node'
- According to http://aurelia.io/hub.html#/doc/article/aurelia/validation/latest/validation-basics I'm installing aurelia-validation with jspm
- vscode
- typings
