### ISSUE TITLE
Pass a "nested.property" to Validator.validateProperty

### ISSUE THREAD

**Issue by fkleuver** [aurelia/validation#389]
**I'm submitting a feature request**

**Current behavior:**
Given a Rule with a nested property accessor (like "some.nested.property"), the accessor is treated as a single property rather than nested properties, e.g. `obj["some.nested.property"]`

**Expected/desired behavior:**
The property to be accessed like so: `obj.some.nested.property`

This is my proposed solution (line 108 for the function call; the function itself is at the bottom): https://github.com/fkleuver/validation/blob/master/src/implementation/standard-validator.ts

**What is the motivation / use case for changing the behavior?**
When dynamically generating validation rules from arbitrary JSON, it's not always possible/practical to stick to direct property accessors. It appears to be relatively simple to implement, but correct me if I'm overseeing something!

**Comment by jdanyow** [comment]
#283
