### ISSUE TITLE
validation-errors attribute doesn't work with not-in-scope validation controller

### ISSUE THREAD

**Issue by dkent600** [aurelia/validation#391]
**I'm submitting a bug report**

* **Library Version:**
0.13.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
7.2.0

* **NPM Version:**
4.0.2

* **JSPM OR Webpack AND Version**
JSPM 0.16.46

* **Browser:**
all 

* **Language:**
TypeScript 2.0

**Current behavior:**

When:

1) You are using the `validation-errors` attribute, like `validation-errors.bind="myErrors"`
2) and the validation controller is specified via the validate binding behavior argument (like `validate:myController`) rather than being discoverable in the viewmodel's container

Then:

When the data is validated the myErrors array is not updated.

**Expected/desired behavior:**

When the data is validated the myErrors array should be updated to contain a list of errors.

**Gist**
Gist that demonstrates:  https://gist.run/?id=7103145949f2b899337a635ff6b8ca74

**Motivation / use case for changing the behavior?**
I would like to use validation-errors in a scenario where I have multiple forms and multiple validationcontrollers on the same page and therefore have to provide the controller to the validate binding behavior.

**Comment by dkent600** [comment]
Solution could be to allow controller to be provided to the `validation-errors` attribute.

**Comment by jdanyow** [comment]
This is something I want to add too- depends on https://github.com/aurelia/templating-binding/issues/56 - let me know if this is something you would be interested in contributing and I could help out with any questions.

**Comment by dkent600** [comment]
@jdanyow Sure, I can have a go at this.  

Should I wait to get started until [aurelia/templating-binding/issues/56](https://github.com/aurelia/templating-binding/issues/56) is done?

I will want to know what the default binding mode should be.

**Comment by jdanyow** [comment]
I was thinking we'd need to tackle https://github.com/aurelia/templating-binding/issues/56 first, then we could easily do this issue. If the default bindable feature isn't in place before we add this feature there will be unnecessary boilerplate/rework for people using `validation-errors.bind` today.

Take a look at https://github.com/aurelia/templating-binding/issues/56 and let me know what you think.

**Comment by dkent600** [comment]
Are you suggesting that I work #56 too?

**Comment by dkent600** [comment]
I would be fine with working aurelia/templating-binding#56 too.
