### ISSUE TITLE
Aurelia Validation Demo Broken

### ISSUE THREAD

**Issue by allencoded** [aurelia/validation#395]
The most recent official blog post I could find on aurelia validation was:
http://blog.aurelia.io/2016/06/14/new-validation-alpha-is-here/

In it there is a gist demo of a supposedly working validation.
https://gist.run/?id=381fdb1a4b0865a4c25026187db865ce

Unfortunately though it doesn't appear to work. If you fill out the first name then leave the last name blank it tells you that the first name is not filled out. Are there any newer gists of working aurelia validation code?

**Comment by jdanyow** [comment]
I had to update the gist to account for some of the breaking changes in the beta release listed here: https://github.com/aurelia/validation/releases/tag/1.0.0-beta.1.0.0

Should be all set now. Thanks for reporting this!
