### ISSUE TITLE
Existing errors incorrectly removed from ValidationController

### ISSUE THREAD

**Issue by DavidBLynch** [aurelia/validation#396]
**I'm submitting a bug report**

* **Library Version:**
1.0.0-beta.1.0.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.9.1

* **NPM Version:**
3.10.8

* **JSPM OR Webpack AND Version**
JSPM 0.16.48

* **Browser:**
all

* **Language:**
ESNext

**Current behavior:**
Given propertyA and propertyB set up for validation.

1. On initial validate() both properties are invalid and are added to this.errors
2. Set propertyA to a valid state, This will remove the propertyA error from this.errors
3. Set propertyA to an invalid state.  This will **_replace_** the propertyB error with the propertyA error.

**Expected/desired behavior:**
Don't accidentally clear the errors collection

**My local fix**
In the ValidationController.processResultsDelta() function the following bit of code is incorrect:

```javascript
if (newResult.valid) {
    this.errors.splice(this.errors.indexOf(oldResult), 1);
} else {
    this.errors.splice(this.errors.indexOf(oldResult), 1, newResult);
}
```
for cases where oldResult does not exist in the errors collection an **_existing_** error will be replaced with the a new error.  The following is a correct implementation:

```javascript
const existingErrorIndex = this.errors.indexOf(oldResult);

if (newResult.valid) {
    if (existingErrorIndex != -1) {
        this.errors.splice(existingErrorIndex, 1);
    }
} else {
    if (existingErrorIndex != -1) {
        this.errors.splice(existingErrorIndex , 1, newResult);
    } else {
        this.errors.push(newResult);
    }
}
```

**Comment by jdanyow** [comment]
Could you please include a minimal reproduction of the issue? I'll use it to write the tests for the fix. Here's a gist with a basic form using the latest Aurelia bits you can use as a starting point:

https://gist.run/?id=381fdb1a4b0865a4c25026187db865ce

**Comment by DavidBLynch** [comment]
Here ya go.  

https://gist.run/?id=0da3ab14d2c728f1b3c6cc7e229e38eb

With my changes the form starts out validated and showing 3 errors.  To reproduce just add a single char to first name.  This will clear the first name error and the error count will be 2.  Then delete the first name char, which will cause first name to error, but the error count will incorrectly remain at 2.  This happens because the code above doesn't find the oldResult, and thus splices -1 indexes from the end of the errors array.  This overwrites an existing entry in the errors collection.
