### ISSUE TITLE
Allow for passing a callback function as "displayName"

### ISSUE THREAD

**Issue by DavidBLynch** [aurelia/validation#397]
**I'm submitting a feature request**

* **Library Version:**
1.0.0-beta.1.0.0

**Current behavior:**
The FluentRules.displayName()  method takes a string.  

**Expected/desired behavior:**
For cases where the displayName is dynamic (varies due to other control values) I need a way to return the a calculated display value.  A callback function that returns a string would be ideal.

* **What is the expected behavior?**
When building the error message the StandardValidator.getMessage() call would check if displayName is a function, and call it if it is.

**Comment by jdanyow** [comment]
closing- this has been added
