### ISSUE TITLE
Server Side Validation

### ISSUE THREAD

**Issue by akircher** [aurelia/validation#398]
Is there a goal to get server side validation to work before 1.0.0?  I notice that there is no [documentation](http://aurelia.io/hub.html#/doc/article/aurelia/validation/latest/validation-basics/13) yet.  When I try to run `node aurelia-validation` or `node aurelia-validation/dist/commonjs/aurelia-validation` I get error such as `Element is not defined`.

**Comment by akircher** [comment]
Seems like it might be a while before it is officially supported and documented.  In the meantime, is there some workaround that would allow me to just play around with it in node?  Judging from your unit tests, it seems like this may be possible.

**Comment by jdanyow** [comment]
You may just need to replace element with DOM.Element from aurelia-pal.

**Comment by akircher** [comment]
Thank you!  The tests helped point me in the right direction.
