### ISSUE TITLE
aurelia-binding has no exported member 'Unparser' error

### ISSUE THREAD

**Issue by AngkouLee** [aurelia/validation#401]
**I'm submitting a bug report**

* **Library Version:**
v1.0.0-beta.1.0.1

**Please tell us about your environment:**
* **Operating System:**
Windows 7

* **Node Version:**
6.5.0

* **NPM Version:**
3.10.6

* **JSPM OR Webpack AND Version**
None

* **Browser:**
Chrome 55.0.2883.87
* **Language:**
TypeScript 2.0.0

**Current behavior:**

After set up aurelia-validation by following the guides from aurelia.io, I was trying to import **ValidationController** from aurelia-validation. When I try to build the project, I got the error said "**Module ''aurelia-binding'' has no exported member 'Unparser'**.", the problem is located at 'node_modules/aurelia-validation/dist/commonjs/implementation/validation-parser.d.ts(1,43)'

**Expected/desired behavior:**

* **What is the expected behavior?**
What I did was trying to import ValidationController from the aurelia-validation, no other code was written. And I have tried aurelia-validation in another project for testing, everything works fine there (that project was created by aurelia-cli, all default settings). My guess is maybe the use of Typescript in my current project cause the error, as the error was located in a *.d.ts file.

**Comment by jdanyow** [comment]
@AngkouLee I think you might have an old version of aurelia-binding installed. Try blowing away your node_modules/jspm_packages folder(s) and re-installing.

https://github.com/aurelia/binding/blob/1.1.1/src/aurelia-binding.d.ts#L353

**Comment by AngkouLee** [comment]
Hi @jdanyow thank you for the reply.
I updated to the latest aurelia-binding v1.1.1, unfortunately the error is still there.
I used 'npm list aurelia-binding' to double check aurelia-binding is update to date.
