### ISSUE TITLE
Add "easy" method to create custom rules like globalResources

### ISSUE THREAD

**Issue by djensen47** [aurelia/validation#407]
**I'm submitting a feature request**

* **Library Version:** 1.0.0-beta.1.0.1

The mechanism for adding a global element, attribute, binding behavior, and value converter in Aurelia is clean, reusable, and "easy." 

Maybe the same is true for custom validation rules but after digging around, the best I could find was this answer on SO: http://stackoverflow.com/questions/41619161/create-a-global-validation-rule-with-aurelia-validation

Shoving a dozen or more custom validation rules in `app.js` doesnt' feel as clean and reusable as making a custom value converter.

My request is to create a mechanism, like globalResources for custom validation rules.

---

In the meantime, what I plan on doing is to create a dir called `resources/custom-rules` and in that dir an `index.js` which will define all of the rules. I'll invoke that from `app.js`.

**Comment by djensen47** [comment]
Again, if there _is_ a better way of creating dozens of custom rules, then I apologize, I just couldn't find the answer. Thanks.

**Comment by stsje** [comment]
Here's one way of adding custom validation rules. You'll only have to do it once.
```
import environment from './environment';
import { setupValidationRules } from './validation/custom-rules';

export function configure(aurelia) {
  aurelia.use
    .standardConfiguration()
    .feature('resources')
    .plugin('aurelia-validation');

  if (environment.debug) {
    aurelia.use.developmentLogging();
  }

  setupValidationRules();
  aurelia.start().then(() => aurelia.setRoot());
}
```
```
import { ValidationRules } from 'aurelia-validation';

export function setupValidationRules() {
  ValidationRules.customRule(
    'digits',
    (value, obj) => value === null || value === undefined || value.length === 0 || /^[0-9]+$/.test(value),
    `\${$displayName} må kun indeholde tal.`
  );
}
```

**Comment by djensen47** [comment]
Yeah, that is almost exactly what I'm doing now.

**Comment by dkent600** [comment]
@djensen47 It sounds like what you want is something like "create a dir called resources/custom-rules and in that dir an index.js which will define all of the rules", and then the ability to refer to that file via something like `aurelia.use.globalCustomValidators('./resources/custom-rules/index.js')`.

And inside index.js you would have:

```
ValidationRules.customRule(
    'digits',
    (value, obj) => value === null || value === undefined || value.length === 0 || /^[0-9]+$/.test(value),
    `\${$displayName} må kun indeholde tal.`
  );
```

Is that correct?

If so, then is it fair to say that the primary difference between what you propose and what is doable now would be these two lines of code:

Proposal:
`aurelia.use.globalCustomValidators('./resources/custom-rules/index.js')`

Can do now:
`import './resources/custom-rules/index.js'`

**Comment by jdanyow** [comment]
closing this- I don't see the benefit of this over using the plain ES6 import statement in your previous comment (excerpt below) or using `aurelia.use.feature(...)` and defining the rules within your feature module's configure method.

>Proposal:
>`aurelia.use.globalCustomValidators('./resources/custom-rules/index.js')`
>
>Can do now:
>`import './resources/custom-rules/index.js'`

**Comment by Sayan751** [comment]
It might be worth noting that with TypeScript, custom validation rule needs to be wrapped in IIFE and needs to be exported.

Example:
`customRules\Rule1.ts`:
``` typescript
export default (() => {
    ValidationRules.customRule("rule1", (value, object, ...) => {/* evaluate rule */ }, "");
})();
```
`customRules\index.ts`:
``` typescript
export * from "./Rule1";
```

And finally importing all rules:

``` typescript
import "./customRules/index";
```

When I used only `ValidationRules.customRule("rule1", (value, object, ...) => {/* evaluate rule */ }, "");` in `customRules\Rule1.ts`, empty/no JavaScript file was generated. If you think, I have missed something, please let me know.
