### ISSUE TITLE
Input fields created with repeat.for in DOM not working with Aurelia Validation

### ISSUE THREAD

**Issue by kvadd** [aurelia/validation#408]
First of all, I want to thank you guys for an amazing framework! We use it for all our new projects for it's ease of use and primary your dedication to keeping standards.

However, I think I have hit a bug with Aurelia Validation plugin when repeat.for is responsible for rendering input fields that require validation.

**I'm submitting a bug report**

* **Library Version:**
1.0.8

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.2.1

* **NPM Version:**
3.9.5

* **JSPM OR Webpack AND Version**
JSPM 0.16.34

* **Browser:**
all

* **Language:**
TypeScript 2.0.3

**Current behavior:**
Input fields that are created under a repeat.for in the DOM are not detected as validated fields.

**Expected/desired behavior:**
Repeated input fields should be included in the binded value 'validate'

https://gist.run/?id=d21cdf00e9a3fd30c50c72f4a4b4df98

* **What is the expected behavior?**
Repeated input fields should have the ability to be validated.

* **What is the motivation / use case for changing the behavior?**
For example: For dynamic created forms, when getting form information from another source.

**Comment by dkent600** [comment]
If you change this line in the gist:

`<form submit.delegate="submit()">`

to this:

`<form submit.delegate="submit()" with.bind="$parent">`

then the validation works.

Just sayin'.  I'm not sure if this should be necessary or not.

**Comment by dkent600** [comment]
It seems odd that the code change I described above would be required because without it is perfectly possible to bind to the fields in $parent.  It is just the validation code that is having the issue.
