### ISSUE TITLE
Clear Error

### ISSUE THREAD

**Issue by smithaitufe** [aurelia/validation#409]
I have a code that does validation using two different rules.

My question is how do I clear the errors base on a particular view?

Is there something like 

`this.controller.clear({rules: this.certificate_item_rules})`

**Comment by jdanyow** [comment]
The controller has a `reset` method. You can call it with no arguments to clear all the errors. You can pass [an instruction](https://github.com/aurelia/validation/blob/master/src/validate-instruction.ts) to the reset method to target a specific object/property/rules.

http://aurelia.io/hub.html#/doc/article/aurelia/validation/latest/validation-basics/12
