### ISSUE TITLE
New feature: custom property name key per rule to control display name

### ISSUE THREAD

**Issue by sam-piper** [aurelia/validation#415]
**I'm submitting a feature request**

* **Library Version:**
aurelia-validation@1.0.0-beta.1.0.1

* **Operating System:**
Windows 10

* **Node Version:**
6.2.0

* **NPM Version:**
4.0.3

Currently, the name of the property bound to a validation rule is also explicitly the key that is used in order to determine the display name parameter for message formatting.

I'm using the i18n plugin with standard integration as per Aurelia docs, so the property name is acting as the resource key for localizing the field name.

Most of the time this convention is fine, but in some cases I have rules where the property name in the view-model is not the same as the field resource that I want to use in the formatted message, but I have no option to customize the property name key per rule, unlike the message which I can do using `withMessageKey()` on each rule.

I can't use `displayName()` because that forces me to do the localization when the rule is declared. Having a callback in displayName() isn't ideal because that requires the view-model to handle the translation effort.

I'd like to be able to specify a custom property name key for each validation rule, using a method like `withPropertyNameKey(string)` or `withDisplayNameKey(string)`, following the same pattern as `withMessageKey()`, so that the property name resource can be resolved exactly as required without requiring the property name to automagically match the field resource.

**Comment by jdanyow** [comment]
Could you use `.displayName(...)` as your `withPropertyNameKey(...)`? Something like `.displayName('@key/some-key')` and add some logic to your implementation of [`getDisplayName`](https://github.com/aurelia/validation/blob/8255f697f8114be126a6286db63a0e6edd37b42b/src/implementation/validation-messages.ts#L54) that checks for display names that are keys and handles them appropriately?

**Comment by sam-piper** [comment]
Yes, that would work fine, thanks for the suggestion. Happy to leave it then.
