### ISSUE TITLE
aurelia-validation is not an ES module

### ISSUE THREAD

**Issue by MaximBalaganskiy** [aurelia/validation#417]
**I'm submitting a feature request**

* **Library Version:**
1.0.0-beta.1.0.0

* **Operating System:**
Windows 10

* **Node Version:**
6.4.0

* **NPM Version:**
3.10.3

* **JSPM OR Webpack AND Version**
JSPM 0.17.0-beta.40

* **Browser:**
all 

* **Language:**
TypeScript 2.0

**Current behavior:**
`import { ValidationRules } from "aurelia-validation";` imports undefined value

**Expected/desired behavior:**
`import { ValidationRules } from "aurelia-validation";` imports a class

* **What is the expected behavior?**
Importing a class

* **What is the motivation / use case for changing the behavior?**
Most of the aurelia modules are ES modules which allows using named imports. 
With SystemJS 0.20 being now compliant with CTC NodeJs ES module directions (https://github.com/nodejs/CTC/pull/60/files#diff-2b572743d67d8a47685ae4bcb9bec651R217, https://github.com/systemjs/systemjs/releases/tag/0.20.0) we cannot use named imports anymore.  This might become true for webpack loader as well.

This forces developers using a different import syntax
```
import av from "aurelia-validation";
var ValidationRules = av.ValidationRules;
```

**Comment by jdanyow** [comment]
If you add `exports.__esModule = true` to the file is the issue resolved?

It's `dist/commonjs/aurelia-validation.js` right?

**Comment by MaximBalaganskiy** [comment]
Not sure if that will be enough... It would also need `exports.ValidationRule = blah;` assignment.
Yes, it's in the `aurelia-validation` file

**Comment by MaximBalaganskiy** [comment]
I can try tomorrow. End of day here

**Comment by jdanyow** [comment]
sounds good- let me know what you find

**Comment by MaximBalaganskiy** [comment]
Confirmed, just adding the following code solves the issue
```
  Object.defineProperty(exports, "__esModule", {
    value: true
  });
```

Is it something added manually or by turning some flag in the build script?

**Comment by jdanyow** [comment]
Could you try one other thing? In your SystemJS config, add:

```
meta: {
  'aurelia-validation': { esModule: true, format: 'cjs' },  // (or format: 'amd' depending on which one you're loading)
}
```

**Comment by MaximBalaganskiy** [comment]
Will check tomorrow

**Comment by MaximBalaganskiy** [comment]
I actually tried it already. While it works fine in an unbundled app, it does not work in a bundled one.

**Comment by jdanyow** [comment]
```
        map: {
          'aurelia-validation': 'node_modules/aurelia-validation/dist/amd',
        },
        meta: {
          'aurelia-validation': { esModule: true, format: 'amd' },
        },
        packages: {
          'aurelia-validation': { main: 'aurelia-validation.js' },
        }
```

```
        map: {
          'aurelia-validation': 'node_modules/aurelia-validation/dist/amd',
        },
        packages: {
          'aurelia-validation': { main: 'aurelia-validation.js', meta: { esModule: true, format: 'amd' } },
        }
```
