### ISSUE TITLE
Make compatible with new webpack/PLATFORM changes

### ISSUE THREAD

**Issue by RichiCoder1** [aurelia/validation#418]
See title. This plugin needs to be updated so it can take advantage of the new changes to bundling.

**Comment by jdanyow** [comment]
@RichiCoder1 / @jods4 / @niieani 

Let me know what I need to do here- I'm not up to speed on the webpack changes you guys have been working on.

**Comment by jods4** [comment]
A quick look at the sources I think wrapping the `globalResources` string with `PLATFORM.moduleName` should be enough. That's here:
https://github.com/aurelia/validation/blob/master/src/aurelia-validation.ts#L80-L82

Other than that it should work right out of the box, so the main task is to do some tests.

When you're done, can you please report it to aurelia/pal#21? I'm keeping a list of all core libraries that have been tested with the new webpack build. Thanks!

**Comment by jods4** [comment]
@RichiCoder1 
If you want to help, adding the following to your webpack build is the equivalent of adding `PLATFORM.moduleName` in code, so you can test it yourself (maybe even do a PR):
```js
module.exports = {
  // ...
  plugins: [
    // ...
    new ModuleDependenciesPlugin({
      "aurelia-validation": [  
        './validate-binding-behavior',
        './validation-errors-custom-attribute',
        './validation-renderer-custom-attribute' ]
    }
  ]
};
```

**Comment by jdanyow** [comment]
thanks @jods4 :dancers:

**Comment by RichiCoder1** [comment]
@jdanyow Nice!
@jods4 Oh cool, I'll have to remember that plugin! I ended up doing it just by doing something like this:
```
PLATFORM.moduleName('aurelia-validation/validate-binding-behavior');
PLATFORM.moduleName('aurelia-validation/validation-errors-custom-attribute');
PLATFORM.moduleName('aurelia-validation/validation-renderer-custom-attribute');
```
To basically the same effect.

**Comment by jods4** [comment]
@RichiCoder1 That plugin is very useful to work out dependencies that are not properly documented in 3rd party libs.

One difference with adding the `moduleName` above to your own code is that the dependencies are attached to the right file, which could be relevant if you code split. Usually (single bundle), it doesn't matter.

**Comment by RichiCoder1** [comment]
@jods4 Just, code splitting was something I was playing around with just around the same time as this :)
