### ISSUE TITLE
Errors added using addError() during validation are lost

### ISSUE THREAD

**Issue by RomkeVdMeulen** [aurelia/validation#429]
Errors added using `ValidationController.addError()` during validation are lost, while those added after validation are rendered properly.

See https://gist.run/?id=d3d94013f712540176470bce974581b1

**Comment by jdanyow** [comment]
this is working "as-designed"- the definition of rules (ValidationRules.ensure....) is independent of the controller. Calling addError inside the rule evaluation makes assumptions about when, how many times the rule will be checked.

Better to do the addError work in your "submit" method.
