### ISSUE TITLE
WithMessage

### ISSUE THREAD

**Issue by Mordred** [aurelia/validation#43]
Hi,

I'm getting an error with this code:

```js
    this.username = '';
    this.password = '';

    this.validation = validation.on(this)
      .ensure('username')
        .isNotEmpty()
        .withMessage('Username is required')
      .ensure('password')
        .isNotEmpty()
        .withMessage('Password is required');
```

An error:

```
inner error: TypeError: Cannot read property 'withMessage' of undefined
    at ValidationRulesCollection.withMessage (http://localhost:1337/jspm/github/aurelia/validation@0.2.1/validation/validation-rules-collection.js:121:66)
    at ValidationGroupBuilder.withMessage (http://localhost:1337/jspm/github/aurelia/validation@0.2.1/validation/validation-group-builder.js:204:47)
    at ValidationGroup.withMessage (http://localhost:1337/jspm/github/aurelia/validation@0.2.1/validation/validation-group.js:299:33)
```

What am I doing wrong?

**Comment by janvanderhaegen** [comment]
Ooops, turns out the .isNotEmpty() (because it's such a special case) does not handle the .withMessage, whereas all other validation rules do. 
Going to fix that right now!

**Comment by janvanderhaegen** [comment]
I have released aurelia-validation 0.2.2, which contains this fix. 

Is there a reason why you are replacing all default validation messages 'is required' with your own 'Username is required'? Will you do this only in this specific case or is it an application-wide UX issue? Perhaps we can facilitate your use case a bit, in which case please do submit an issue on how we could help!

**Comment by Mordred** [comment]
I'm using
```js    validationConfig.useViewStrategy(ValidateCustomAttributeViewStrategy.TWBootstrapAppendToInput);
```

because login form has no labels, only placeholders in the inputs. But when the username is empty, only ```is required``` text is displayed which looks bad without label.

**Comment by fragsalat** [comment]
Just a note for new people. Not this has changed. Do the following

```javascript
import {TWBootstrapViewStrategy} from 'aurelia-validation';

export function configure(aurelia) {
    aurelia.use.plugin('aurelia-validation', (config) => {
            config.useLocale('de-DE').useViewStrategy(TWBootstrapViewStrategy.AppendToInput)
        });

    aurelia.start().then(a => a.setRoot('app/app'));
}
```
