### ISSUE TITLE
Textarea onchange trigger causes cursor to jump to end of the line (only Internet Explorer)

### ISSUE THREAD

**Issue by lutzleo** [aurelia/validation#431]
**I'm submitting a bug report**

* **Library Version:**
1.0.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.10.2

* **NPM Version:**
3.10.6

* **JSPM OR Webpack AND Version**
aurelia-cli@0.28.0

* **Browser:**
IE 11 (11.0.10240.17319)

* **Language:**
TypeScript 2.2.2

**Current behavior:**

This behaviour is Internet Explorer specific:

Simple validation rules defined:
```
ValidationRules
  .ensure((a: App) => a.email)
  .displayName('E-Mail')
  .required().email().on(App);
```

OnChange Validation behaviour on textarea:
`<textarea cols="70" rows="30" type="text" value.bind="email & validateOnChangeOrBlur"></textarea>`

When I start typing everything is working as expected. But when I move the cursor before some text and start typing the cursor jump to the end of the line. The on change trigger is causing this weird behaviour.

i.e.:
Started with writing "111111...". Jump to the beginning of the line and start typing "2222....". After a short amount of time the cursor jumps to the end.
![image](https://cloud.githubusercontent.com/assets/26089893/24712281/bcd806e4-1a22-11e7-8d22-c9a3a99d634d.png)

**Expected/desired behavior:**

* **What is the expected behavior?**
The cursor should not jump to end of the line.

* **What is the motivation / use case for changing the behavior?**
Users/Customers are confused about this behaviour.

**Comment by jdanyow** [comment]
@lutzleo please put together a minimal reproduction using this plunker so we can troubleshoot this for you.
http://plnkr.co/edit/5vMoxM?p=preview

thanks!

**Comment by lutzleo** [comment]
Hi @jdanyow,

thanks for your comments. 

How to update the aurelia-validation version to 1.0.0 in the rawgit cdn?

VM1307 system.js:4 Uncaught (in promise) Error: XHR error (404) loading https://cdn.rawgit.com/jdanyow/aurelia-plunker/v0.10.1/jspm_packages/npm/aurelia-validation@1.0.0.js
	Error loading https://cdn.rawgit.com/jdanyow/aurelia-plunker/v0.10.1/jspm_packages/npm/aurelia-validation@1.0.0.js

see http://plnkr.co/edit/ne1tThGZc0RrVvVPz5mY?p=preview

Thank you.

**Comment by jdanyow** [comment]
Try forking the plunker I provided here: https://github.com/aurelia/validation/issues/431#issuecomment-292415392 - it has an up to date version of aurelia.

**Comment by lutzleo** [comment]
@jdanyow 
But this plunkr does not have the correct aurelia-validation version:

"aurelia-validation": "npm:aurelia-validation@0.6.0" (config.js)

I have to use the version 1.0.0.

**Comment by jdanyow** [comment]
I don't think we're looking at the same plunker. 

Try replacing your plunker's index.html with the code below. This will ensure you're up to date.

```html
<!doctype html>
<html>
  <head>
    <title>Aurelia</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body aurelia-app>
    <h1>Loading...</h1>
    
    <script src="https://jdanyow.github.io/rjs-bundle/node_modules/requirejs/require.js"></script>
    <script src="https://jdanyow.github.io/rjs-bundle/config.js"></script>
    <script src="https://jdanyow.github.io/rjs-bundle/bundles/aurelia.js"></script>
    <script src="https://jdanyow.github.io/rjs-bundle/bundles/babel.js"></script>
    <script>
      require(['aurelia-bootstrapper']);
    </script>
  </body>
</html>
```

**Comment by jdanyow** [comment]
closing- abandoned
