### ISSUE TITLE
validate binding behaviour fails when controller isn't instanced yet.

### ISSUE THREAD

**Issue by Einarsson** [aurelia/validation#433]
**Current behavior:**
If a validation controller isn't instanced before the view attaches, the validate binding behaviour fails.

**Expected/desired behavior:**
I want it to reevaluate the binding if the controller context changes and not crash when it isn't set yet.

* **What is the motivation / use case for changing the behavior?**
Our scenario works likes this:
https://gist.run/?id=a366ac61762992e3e4e227a67264cad6

We never create viewModels using the container, they are always created by the outer "routed" viewModel. The viewModel is also created when the data has finished loading. We don't want to load the required view data in activate because not loading the interface before the loading is bad UX. We want the user to get the view feedback instantly then show with spinners/disabled fields that things aren't ready yet.

However since the controller isn't there yet until the viewmodel is created the binding behaviour crashes.

I'm not sure how other people approach this, maybe there is a clean workaround already that I havn't found. I feel like this should be considered fixing since it worked in the previous versions of validation.

Cheers!

**Comment by Einarsson** [comment]
I could work around it by creating a custom attribute like the old version used.
Bind the controller and viewmodel into it, use a propertyobserver to observe the property changes then manually call controller.validate and send the result to a renderer.

If you hadn't used the binding to trigger the validation, the controller doesn't have an internal binding registered to work with and thus the results arent even send propertly to the render, cause the element sent to the renderer along with the result, is null.

`import { inject, bindable } from 'aurelia-framework';
import { BindingEngine } from 'aurelia-binding';
import { WindowAbstraction } from '../browser-abstractions/window-abstraction';
import { BootstrapFormRenderer } from './bootstrap-form-renderer';

@inject(Element, BindingEngine, WindowAbstraction, BootstrapFormRenderer)
export class ValidationControllerCustomAttribute {
  _element = null;
  _controllerLoaded = false;
  _bindingEngine = null;
  @bindable controller;
  @bindable viewmodel;

  constructor(element, bindingEngine, window) {
    this._element = element;
    this._bindingEngine = bindingEngine;
    this._window = window;
    this._renderer = new BootstrapFormRenderer();
  }

  controllerChanged(controller) {
    if (controller && this.viewmodel) {
      this._controllerLoaded = true;
    }
  }

  viewmodelChanged(viewmodel) {
    if (viewmodel) {
      this._viewmodelLoaded = true;
    }
  }

  async bind(binding, source, rulesOrController, rules) {
    if (!this.controller && !this.viewmodel) {
      this._window.queue(() => this.bind(), 10);
    } else {
      let bindAttribute = this._element.attributes['value.bind'];
      let bindValue = bindAttribute.value;
      let split = bindValue.split('.');
      let propertyName = split[split.length - 1];
      let observer = this._bindingEngine.propertyObserver(this.viewmodel, propertyName).subscribe(async (value) => {
        let result = await this.controller.validate({ object: this.viewmodel, propertyName: propertyName });
        this._renderer.clearAndRender(this._element, result.results[0]);
      });
    }
  }`


`<input class="form-control" id="billing_street" placeholder="Gatuaddress" type="text" value.bind="viewModel.header.billingStreet" validation-controller="controller.bind:viewModel.header.validationController; viewmodel.bind:viewModel.header"/>`

This feels very ugly but at least it works. Although we had to bypass alot of the nice features the framewould normally handles.

**Comment by jdanyow** [comment]
The validation binding behavior requires a controller. Use the `if` binding controller to postpone data-binding your form until the view model (and controller) are available.

Updated version of your gist:
https://gist.run/?id=611ca9293371aed1c587a2511c3ef13c

Diff:
https://gist.github.com/jdanyow/611ca9293371aed1c587a2511c3ef13c/revisions

**Comment by Einarsson** [comment]
I know that is à possible workaround but I still think its a very bad restriction in the framwork and should be thought of and fixed eventually.

**Comment by jdanyow** [comment]
I disagree. I think it's bad to have the form visible and accepting user input before the view model it will be bound to has been instantiated.
