### ISSUE TITLE
withMessage docs incorrect.

### ISSUE THREAD

**Issue by JoshMcCullough** [aurelia/validation#434]
Happy to fix this typo if someone points me to the proper repo!

http://aurelia.io/hub.html#/doc/article/aurelia/validation/latest/validation-basics/1

The "withMessage" example has the escape `\` in the wrong location, should be:

```
.withMessage(`"\${$value}" is not a valid \${$displayName}.`)
```

**Comment by EisenbergEffect** [comment]
There's an edit button at the top of that article ;)

**Comment by JoshMcCullough** [comment]
Totally missed that, thanks!
