### ISSUE TITLE
Find untagged rules

### ISSUE THREAD

**Issue by RomkeVdMeulen** [aurelia/validation#436]
Currently when some rules are tagged and others aren't, you can get the untagged rules by calling:

```ts
ValidationRules.taggedRules(myRules, <any> undefined);
```

Is this an implementation detail that may change in the future? Or an intended part of the API? If the latter, it might be wise to change the parameter type for `taggedRules()` and perhaps add a note to the docs about this.

**Comment by jdanyow** [comment]
which would you prefer:

1. `ValidationRules.taggedRules(myRules, undefined);`
1. `ValidationRules.taggedRules(myRules);`
1. `ValidationRules.untaggedRules(myRules);`

I think I prefer 3.
.

**Comment by RomkeVdMeulen** [comment]
3 looks good.

**Comment by jdanyow** [comment]
excellent- would you be interested in opening a PR for this?
