### ISSUE TITLE
Validation annotations

### ISSUE THREAD

**Issue by jasoncarreira** [aurelia/validation#439]
**I'm submitting a feature request**

**Current behavior:**

all rules must be defined using the fluent syntax

**Expected/desired behavior:**
* **What is the expected behavior?**

I'd like to be able to annotate properties to define validations, i.e. : 

@required
@minLength(4)
private name : String;

* **What is the motivation / use case for changing the behavior?**

Less code to write. Easier to maintain. Keeping the property definition and validations all in one place.

**Comment by shawty** [comment]
+1 - get's my vote

**Comment by jdanyow** [comment]
#287
