### ISSUE TITLE
Add number validations

### ISSUE THREAD

**Issue by jasoncarreira** [aurelia/validation#440]
**I'm submitting a feature request**

**Current behavior:**

There are no number validations

**Expected/desired behavior:**

* **What is the expected behavior?**

I'd like to have number validations such as lessThan, greaterThan, between, etc. 

* **What is the motivation / use case for changing the behavior?**

I have a lot of numeric properties and having to use the satisfies() method takes up a lot more space than built-in number validations

**Comment by shawty** [comment]
+1 gets my vote too, this is such a common pattern on select based drop downs.

**Comment by jdanyow** [comment]
Would you mind sharing your custom validations for numbers? Will help us to make sure we're hitting your use cases.

**Comment by shawty** [comment]
@jdanyow me or the op?

**Comment by jdanyow** [comment]
Both! 😀

**Comment by shawty** [comment]
LOLZ...  :-)

Well for me, I usually create my drop downs something like the following:

    <select value.bind="theSelectValue">
      <option value="0">Please Select something</option>
      <option repeat.for="option of selectOptions" value.bind="option.value">${option.text}</option>
    </select>

My "selectOptions" are then populated thus:

    private selectOptions = [
      { value: 1, text: "Option 1" }
      { value: 2, text: "Option 2" }
      { value: 3, text: "Option 3" }
      { value: 4, text: "Option 4" }
    ];

Or by loading from Ajax in that format.

I then handle my rules in the VM thus:

      ValidationRules.customRule(
          'ddlValueSelected',
          (value: number, sender: ProjectDetails) => {
            if (value > 0) {
              return true;
            }
    
            return false;
          },
          `Drop down value MUST be selected`
        );

        ValidationRules
          .ensure((p: myVmType) => p.theSelectValue).satisfiesRule('ddlValueSelected').withMessage("Option must be selected.")
          .on(this);

Or more often, I actually create a 

      private myData = {}

Then bind my controls to

      myData.foo....

and put the validation on

      .on(this.foo)

If that helps :-)

Shawty

**Comment by jasoncarreira** [comment]
Here's mine, so far:

```ValidationRules.customRule(
    'numberRange',
    (value, obj, min, max, dollar : boolean = true) => {
      let number = numeral(value).value();
      return value === null || value === undefined
        || number >= min && number <= max
    },
    `\${$displayName} must be between \${'$config.min} and \${$config.max}.`,
    (min, max) => ({ min, max })
  );

  ValidationRules.customRule(
    'lessThan',
    (value, obj, max) => {
      let number = numeral(value).value();
      return value === null || value === undefined
        || number <= max
    },
    `\${$displayName} must be less than \${$config.max}.`,
    (max) => ({ max })
  );

  ValidationRules.customRule(
    'greaterThan',
    (value, obj, min) => {
      let number = numeral(value).value();
      return value === null || value === undefined
        || number >= min
    },
    `\${$displayName} must be greater than \${$config.min}`,
    (min) => ({ min })
  );```

**Comment by jdanyow** [comment]
thanks!

**Comment by JoyalToTheWorld** [comment]
Any progress on this issue?
