### ISSUE TITLE
validation-parser.d.ts has a dependency on 'Unparser', which doesn't exist in aurelia-binding anymore

### ISSUE THREAD

**Issue by frances-brussee** [aurelia/validation#441]
**I'm submitting a bug report**

* **Library Version:**
1.0.0

**Please tell us about your environment:**

* **Operating System:**
Windows 8.1

* **Node Version:**
5.1.0

* **NPM Version:**
3.3.12

* **JSPM OR Webpack AND Version**
JSPM 0.16.25

* **Browser:**
all

* **Language:**
TypeScript 1.8.35

**Current behavior:**
Installed the latest version of aurelia-validation. TypeScript compiler throw the following error:

_**validation-parser.d.ts(1,43): error TS2305: Module ''aurelia-binding'' has no exported member 'Unparser'.**_

The installed version of aurelia-binding is 1.2.1, which seems to be the most recent release.

**Expected/desired behavior:**
validation.parser.d.ts  has the correct reference to Unparser.

**Comment by jdanyow** [comment]
Weird, I see it in the d.ts: https://github.com/aurelia/binding/blob/master/dist/aurelia-binding.d.ts#L353

**Comment by frances-brussee** [comment]
Same thing occurred. aurelia-binding is on version 1.2.1

**Comment by frances-brussee** [comment]
Sorry, my bad. Our source code was looking in the wrong location for aurelia-binding.d.ts
