### ISSUE TITLE
Entity validation should be able to call validations on sub-objects

### ISSUE THREAD

**Issue by jasoncarreira** [aurelia/validation#442]
**I'm submitting a feature request**

**Current behavior:**

There's no way to pass validation down to sub objects

**Expected/desired behavior:**

I'd like to be able to pass validation down to associated sub objects.

```
export class Parent {
   name : string;
   address: Address;
   children: Child[] = [];

  constructor() {
      ValidationRules
            .ensure('name').required()
            .ensure('address').required().isValid()
            .ensure('children').isValid()
            .on(this)
  }
}

export class Child {
   name : string;
   address: Address;

  constructor() {
      ValidationRules
            .ensure('name').required()
            .ensure('address').required().isValid()
            .on(this)
  }
}

export class Address() {
   line1: string;
   line2: string;
   city: string;
   state: string;
   zip: string;

    constructor() {
        ValidationRules
            .ensure('line1').required()
            .ensure('city').required()
            .ensure('state').required()
            .ensure('zip').required()
            .on(this)
    }
}
```

* **What is the expected behavior?**

Validation should check the sub-objects when validating the parent object if the parent object's rules include the isValid() method on the child object

* **What is the motivation / use case for changing the behavior?**

Being able to model rich domain models with associated validations

**Comment by jdanyow** [comment]
The `ValidationController` is capable of multi-entity validation. Use `ValidationController.addObject` and `ValidationController.removeObject` to add and remove validation targets.

http://aurelia.io/hub.html#/doc/article/aurelia/validation/latest/validation-basics/9

**Comment by jasoncarreira** [comment]
That's not really the same thing. I only want to validate the child objects if the parent object is validated. If I remove the parent object from the validation controller the child objects would still be validated. 

Also, I'd have to pass the validation controller to the constructor of my domain models, which means I can't have form-agnostic validations defined for my domain models that go across multiple viewmodels and forms.

**Comment by jasoncarreira** [comment]
Further, the isValid() would let me add contextual validations in addition to the static validations defined on the domain models. 

```
export class myViewModel() {

private parent : Parent;

validate() {
   ValidationRules
      .ensure('parent').isValid()
      .ensure('parent.children'). maxItems(3).withMessage('In this case you can only have 3 children')
      .on(this)
}


}
```

**Comment by jreeter** [comment]
Bump on this,  I'd like to also be able to have a parent run through child validation.

**Comment by ErikSchierboom** [comment]
Another bump. This is an important feature.
