### ISSUE TITLE
npm package includes dependent packages in node_modules

### ISSUE THREAD

**Issue by alu** [aurelia/validation#445]
**I'm submitting a bug report**

* **Library Version:**
1.0.0

**Please tell us about your environment:**
* **Operating System:**
Linux (Fedora 25)

* **Node Version:**
7.10.0

* **NPM Version:**
5.0.1

* **JSPM OR Webpack AND Version**
webpack 2.6.1

* **Browser:**
not related

* **Language:**
not related

**Current behavior:**

aurelia-validation@1.0.0 package includes dependent packages in node_modules directory under the package directory.
```sh
$ npm install aurelia-validation
$ ls node_modules/aurelia-validation/node_modules
@types                             is-npm
JSONStream                         is-number
abab                               is-obj
...
```

Those modules causes a problem to me when build with webpack and excecute on browsers.
```
Error: Error invoking SVGAnalyzer. Check the inner error for details.
------------------------------------------------
Inner Error:
Message: _aureliaPal.DOM.createElement is not a function
```

* **What is the expected behavior?**
Exclude those modules in the package.

Thanks.

**Comment by MayGo** [comment]
Have same error when including aurelia-validation in latest skeleton-typescript-webpack
* package.json -  "aurelia-validation": "1.0.0"
* main.js -  .plugin(PLATFORM.moduleName('aurelia-validation')))

yarn install
npm start

`
Error: Error invoking SVGAnalyzer. Check the inner error for details.
------------------------------------------------
Inner Error:
Message: __WEBPACK_IMPORTED_MODULE_1_aurelia_pal__.a.createElement is not a function
`

Is there at least a work around?

**Comment by alu** [comment]
@MayGo Try delete contents in `node_modules/aurelia-validation/node_modules`. Solved in my enviroment.

**Comment by alu** [comment]
@EisenbergEffect 
Hi.

This is not a question, a packaging problem.

My solution is a workaround. We want new package that does not include depend modules.

**Comment by rowellx68** [comment]
@alu Thanks for this! I was having this issue as well

**Comment by JoshuaVSherman** [comment]
@alu @EisenbergEffect yes I have also been having this same issue, thanks for identifying the problem. I hope they make the proper fix for this in the near future and reopen this issue until it is actually fixed.
