### ISSUE TITLE
satisfiesRule typing breaks fluent api type flow.

### ISSUE THREAD

**Issue by RichiCoder1** [aurelia/validation#449]
The type definition is currently:
`    satisfiesRule(name: string, ...args: any[]): any;`
when it probably should be
`    satisfiesRule(name: string, ...args: any[]): FluentRuleCustomizer<TObject, TValue>;`

And as a result, any fluent rules added after it lose typing support (as they become `any`).

**Comment by EisenbergEffect** [comment]
@jdanyow Can you look into this?
