### ISSUE TITLE
Object properties don't work with default viewstrategy

### ISSUE THREAD

**Issue by CharlesPockert** [aurelia/validation#45]
If you bind to a property on an object the default (bootstrap) view strategy never finds the property for the binding string

e.g.

```
<input value.bind="someObject.someProperty"></input>
```

The code in the view strategy only strips the value converters from the binding but doesn't look at the dots

Simple fix would be to strip off anything before the last index of "." in the binding string in the view strategy:
```
 // Remove any dotted parts to the binding path as the validator deals with just the prop name
 if (bindingPath.indexOf('.') != -1)
     bindingPath = bindingPath.substring(bindingPath.lastIndexOf(".") + 1);
```

Then it will work a bit nicer for bootstrap out of the box

**Comment by janvanderhaegen** [comment]
Hey @CharlesPockert 
You're right, once your input binds to a different path ('someObject.SomeProperty') than the one you used to set up the validation (.ensure('SomeProperty')), the validateCustomAttribute can no longer match the two.

I believe your suggested workaround would create some complexity as you're cutting away important information (suppose your model has 'candidate.email' and 'candidate.previousJobReference.contactInfo.email', the validateCustomAttribute would no longer know which 'email' to show validation messages for).

The current workaround is to change your input to explicitly tell the validation which 'binding path' to use when comparing to the way your validation was set up (similar to AngularJS z-validate attribute):
``` html
<input value.bind="someObject.someProperty" validate="someProperty" ></input>
```
[This behavior is documented here](https://github.com/aurelia/validation/blob/master/doc/Intro.md#how-are-elements-and-validation-rules-matched)

I'm going to leave this issue open a little bit, as I think there might be a second workaround that I want to experiment with & document.

Thank you for using the validation plugin and providing feedback though. Your thoughts are always appreciated!

**Comment by CharlesPockert** [comment]
Ah great thanks for that I must have missed the validate custom attribute when I read the docs (I think I mostly looked at the examples and I don't recall seeing it in there) and I actually ended up realising this issue today and implementing the same approach in the end with a custom attribute (talk about reinventing the wheel!)

In fact this became particularly useful when I was binding to a dynamic path using indexer syntax as the view strategy had no idea what it was looking for in this case. So I'll be removing my custom attribute and replacing it with the one that already exists!

I'd be very interested in seeing some other ideas/approaches in linking the validation and model with the view as you are right, trimming the other binding info away could cause issues - I hasn't considered it as I haven't wandered into that situation yet.

I'm loving the validation plugin, I've used a few validators for angular and always felt they were unintuitive or limited, but this is a very clean implementation. 

I've even managed to get it to validate dynamic inputs created using repeat.for which I'd suspect would have taken a long time in angular.

**Comment by janvanderhaegen** [comment]
Hey @CharlesPockert 
Man thank you for the words of praise! They mean a lot to us!
We have an open issue, the validator does not handle collections very well, yet. I'd be interested in learning a bit more about your last statement (*validate dynamic inputs created using repeat.for*), if you would have some time to describe the issue you encountered and how you fixed it?

Thanks a million

Jan

**Comment by CharlesPockert** [comment]
Hi Jan, so let me set the scene:

In the application I'm working on, the users need to be able to create "alerts" (it's a front end for some monitoring software we have). Each alert has a "type" and each type has a different set of metadata associated with it (the metadata is simply a list of expected properties that require values on a particular type of alert).

I started with creating a view for each type of alert in which I create an input for each property and bind it to the `metadata` property on my alert model. I realised that the users would likely request a new alert type to be added (which may require some work in the back end to handle it or may not) and that since I was already holding a list of expected metadata in the database I could be more flexible by generating the inputs in a single view.

I now repeat over the expected property names and bind each input to the model using indexer syntax e.g:

`<input value.bind="alert.metadata[property.Name]" validate="${ property.Name }" validate.bind="property.Name">`

This is where the problem occurs - the view strategy only receives the string value from either of these attributes since it's looking at the DOM and not the VM (I tried adding `validate.bind` to the `bindingPathAttributes` array at first)

The easiest solution was to create a custom attribute to write the actual evaluated value to the DOM:

```
import {inject, customAttribute} from 'aurelia-framework';

@customAttribute("validate-hint")
@inject(Element)
export class ValidateHint {
	constructor(element) {
		this.element = element;
	}

	valueChanged(newValue) {
	    if (newValue) {
	        this.element.setAttribute("validate", newValue);
	    }
	}
}
```

Which I applied to the input.

The view strategy is a view concern and I like the clean separation between the validatior and the visuals, so I don't think it makes sense to involve the viewmodel in any way - is this the simplest solution do you think?

**Comment by janvanderhaegen** [comment]
Hey @CharlesPockert ,
that is great stuff!! Great workaround, it's amazing for me to see how people can take this validation plugin to levels I had never imagined.

Eventually, I want to be able to add support for collections. So each of your alerts would have it's own validation instance, and your VM would have one validation instance which monitors the collection of *alert.validation* for validity.  In your case, the validation on *alert* would be another 'collection-validation' on each of the properties.
I'm a big fan of metadata development myself, so rest assure one day your scenario will be fully supported out-of-the-box :-)

I'm going to close this issue and copy your comment in the 'collection' issue #10. 

Thank you again for the feedback. It has been both motivating and fascinating!
