### ISSUE TITLE
Validation and components with multiple inputs not validated as expected

### ISSUE THREAD

**Issue by waywardz** [aurelia/validation#453]
I'm submitting a bug report

Please tell us about your environment:

Operating System:
Windows 10

Node Version:
v6.9.1

NPM Version:
3.10.9

JSPM OR Webpack AND Version
webpack 2.3.3

Browser:
all

Language:
ESNext

Current behavior:
When a single input on a component with multiple input fields is validated, validation is not applied at the input level, and is instead applied at the component level.

Reproduction of behavior with a less than idea workaround that we have been using: https://github.com/waywardz/skeleton-navigation

The example is in skeleton-esnext-webpack.  I didn't bother updating the renderer to highlight the fields correctly, the error messages demonstrate the behavior.

My company now blocks gist.run, otherwise I would have done it there.  Working on getting it unblocked.

Expected/desired behavior:
I would expect each input to be validated independently regardless of whether its in a component or not.

What is the motivation / use case for changing the behavior?
The behavior isn't intuitive given how validation works outside of a component.  I demonstrated a workaround, but it definitely isn't ideal or intuitive.

**Comment by waywardz** [comment]
@jdanyow is there anything more I can provide for this one to get feedback on it?

**Comment by waywardz** [comment]
@EisenbergEffect is anyone available to help answer this question?

**Comment by jdanyow** [comment]
If you create a gist that shows what you're doing I'll be able to help.

https://gist.run/?id=381fdb1a4b0865a4c25026187db865ce
