### ISSUE TITLE
ValidationMessageParser::parseMessage() is not a function

### ISSUE THREAD

**Issue by mreiche** [aurelia/validation#454]
**I'm submitting a bug report**

* **Library Version:**
1.1.1

**Current behavior:**

Overriding getMessage() doesn't work anymore as described here: http://aurelia.io/hub.html#/doc/article/aurelia/validation/latest/validation-basics/2

```
i18n.js:52 Uncaught (in promise) TypeError: this.parser.parseMessage is not a function
    at ValidationMessageProvider.getMessage (i18n.js:52)
    at StandardValidator.getMessage (standard-validator.js:62)
    at eval (standard-validator.js:105)
    at <anonymous>
```

Method was renamed to ``parse()``

**Expected/desired behavior:**
This is a breaking change. Please don't do that.

* **What is the expected behavior?**
``parseMessage()`` should work again.

* **What is the motivation / use case for changing the behavior?**
I dunno.

**Comment by EisenbergEffect** [comment]
@jdanyow Can you address this? Perhaps a patch release that aliases the new method to the old one to restore compatibility?

**Comment by roelplieger** [comment]
Had the same problem, just replace parseMessage(...) by parse(...)
