### ISSUE TITLE
 Cannot find name 'object' when doing gulp build/watch with latest typings definitions

### ISSUE THREAD

**Issue by fuzzzerd** [aurelia/validation#455]
**I'm submitting a bug report**

* **Library Version:** > 1.0.0

**Please tell us about your environment:**
* **Operating System:** Windows 10

* **Node Version:** v7.2.1

* **NPM Version:** v4.6.1

* **JSPM Version:** JSPM 0.16.48

* **Browser:** all

* **Language:** TypeScript 2.1.6

**Current behavior:**
Running `gulp build/watch/bundle` results in errors:
> typings\modules\aurelia-validation\index.d.ts(50,13): error TS2304: Cannot find name 'object'.
> [15:57:24] gulp-notify: [Error running Gulp] Error: typings\modules\aurelia-validation\index.d.ts(50,13): error TS2304: Cannot find name 'object'.

Along with several other instances of the same error, over different line numbers. The one referenced here can be quickly seen by viewing these two tags of the file:

v1.0.0: https://github.com/aurelia/validation/blob/1.0.0/dist/amd/property-info.d.ts
v1.1.0: https://github.com/aurelia/validation/blob/1.1.0/dist/amd/property-info.d.ts

It appears to be related to the fact that versions > 1.0.0 use 'object' instead of 'Object'. 

By updating the `typings.json` to reference the v1.0.0 commit hash (instead of master, which is what skeleton example project uses) I'm able to correct that error. It seems to be unrelated to the version of the actual package I've got referenced from `jspm`.

**Comment by jdanyow** [comment]
need to update typescript- `object` is a built-in.
