### ISSUE TITLE
rule.condition is not a function

### ISSUE THREAD

**Issue by sboyd** [aurelia/validation#458]
**I'm submitting a bug report**

* **Library Version:**
1.1.1

**Please tell us about your environment:**
* **Operating System:**
OSX El Capitan

* **Node Version:**
7.8.0

* **NPM Version:**
4.5

* **JSPM OR Webpack AND Version**
2.1.0-beta.27

* **Browser:**
Chrome Version 59.0.3071.115 (Official Build) (64-bit)

* **Language:**
ESNext

**Current behavior:**

When attempting to use a custom rule I'm receiving an exception in the console.
I've created this Gist https://gist.run/?id=cbdbd016b63b8a89b3e1020e6204e1f1 which I modeled after the examples from the plugin documentation.

Whether I have it return a promise or not I receive the same error.

TypeError: rule.condition is not a function

I was able to work around this by doing the following.

.satisfies((value, object) => { return this.userProfileService.isEmailAddressAvailable(value) } ).withMessage('Email Address is already in use.')

**Expected/desired behavior:**
According to the documentation located here http://aurelia.io/hub.html#/doc/article/aurelia/validation/latest/validation-basics, which also seems to have a broken left hand navigation, it seems like what I'm trying to do and how I'm trying to do it should work.

* **What is the motivation / use case for changing the behavior?**
To achieve the level of code separation outlined in the documentation.

**Comment by kellyethridge** [comment]
In your Gist you should be calling your rule with `.satisfiesRule('isEmailAddressAvailable')` instead of `.satisfies('isEmailAddressAvailable')`.

**Comment by sboyd** [comment]
thanks @kellyethridge I completely missed that!
Have a great day --Steve

**Comment by sboyd** [comment]
Looks like the validation documentation has been fixed! Not sure if it had anything to do with my bug report but either way it was nice to see it fixed :0)
