### ISSUE TITLE
Suggestion: move PropertyAccessorParser to aurelia-framework

### ISSUE THREAD

**Issue by sam-piper** [aurelia/validation#462]
Hi guys,

The PropertyAccessorParser component used for creating typed references to property names (like we used to do in C# with expressions and now `nameof()`) is a really useful utility. 

We use it across our app for defining references to properties, so that they are not magic strings, as much as possible. Can I suggest that this component be moved to the base Aurelia framework, instead of being just in this plugin? It has uses far beyond just validation, and helps TypeScript do a better job.

Just a thought.

**Comment by jdanyow** [comment]
glad you found it useful!

@EisenbergEffect thoughts?

This is the class: https://github.com/aurelia/validation/blob/master/src/property-accessor-parser.ts

**Comment by EisenbergEffect** [comment]
How possible is it to move this to binding, keeping the fidelity of the TS definitions, but without needing to port all of the binding library to TypeScript?

**Comment by Alexander-Taran** [comment]
Stale since 2017
but seems useful

**Comment by TimVevida** [comment]
Or you could use the TypeScript-operator `keyof` ([available since TypeScript 2.1](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-1.html)). Then you can use strings, and the TypeScript compiler does the magic and checks if they are properties of a given object.

**Comment by Alexander-Taran** [comment]
@bigopon seen this one?

**Comment by bigopon** [comment]
I'm not sure we want to do it, validation is the only user of this, we don't want to punish apps that don't use it. Also, it can be simply copied if an apps need to.
