### ISSUE TITLE
ValidationMessageProvider.parser is private and therefore cannot be used when overriding getMessage

### ISSUE THREAD

**Issue by michaelbull** [aurelia/validation#464]
**I'm submitting a bug report**
**I'm submitting a feature request**

* **Library Version:**
1.1.1

**Please tell us about your environment:**
* **Operating System:**
Linux (Fedora 26)

* **Node Version:**
6.11.0

* **NPM Version:**
3.10.10

* **JSPM OR Webpack AND Version**
webpack 3

* **Browser:**
all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView

* **Language:**
TypeScript 2.4.2

**Current behavior:**

The [`parser`](https://github.com/aurelia/validation/blob/40060d7fbfd4ce2c042abe6d3b3006c2ade7a0af/src/implementation/validation-messages.ts#L32) field inside ValidationMessageProvider is marked as `private`.

The validation documentation shows [overriding ValidationMessageProvider.getMessage](http://aurelia.io/hub.html#/doc/article/aurelia/validation/latest/validation-basics/3). However, as `parser` is private, the overriden method cannot call `this.parser`.

The example code used to configure it:

```ts
export async function configure(aurelia: Aurelia): Promise<void> {
    aurelia.use
        .standardConfiguration()
        .plugin(PLATFORM.moduleName('aurelia-validation'))
        .plugin(PLATFORM.moduleName('aurelia-i18n'), (instance: I18N) => {
            instance.i18next.use(Backend);

            return instance.setup({
                backend: {
                    loadPath: '{{lng}}/{{ns}}',
                    parse: (data: any): any => data,
                    ajax: loadLocales
                },
                lng: 'en'
            });
        });

    ValidationMessageProvider.prototype.getMessage = function (key) {
        const i18n = aurelia.container.get(I18N);
        const translation = i18n.tr(`errorMessages.${key}`);
        return this.parser.parse(translation);
    };

    ValidationMessageProvider.prototype.getDisplayName = function (propertyName, displayName) {
        if (displayName !== null && displayName !== undefined) {
            return displayName;
        }
        const i18n = aurelia.container.get(I18N);
        return i18n.tr(propertyName);
    };

    // remainder omitted 
    // ...
```

The resultant error:

```
ERROR in [at-loader] ./src/main.ts:52:21 
    TS2341: Property 'parser' is private and only accessible within class 'ValidationMessageProvider'.
```

**Expected/desired behavior:**

* **What is the expected behavior?**

The parser field should be public to allow overriding functions to call `this.parser.parse`.

* **What is the motivation / use case for changing the behavior?**

The ability to use `aurelia-i18n` with `aurelia-validation` in a TypeScript project.

**Comment by jdanyow** [comment]
sounds good- would you like to send a PR with this change?
