### ISSUE TITLE
Validator.valid property is not always correct

### ISSUE THREAD

**Issue by elitemike** [aurelia/validation#465]
**I'm submitting a bug report**

* **Library Version:**
1.1.1

* **Operating System:**
Windows [8.1|10]

* **Node Version:**
6.9.5

* **NPM Version:**
5.3.0

* **Browser:**
Chrome 59.0.3071.115 | Firefox 54.0.1 | Edge 40.15063.0.0 | IE 11.483.15063.0

**Language:**
TypeScript 2.4

**Current behavior:**
If an object to validate has multiple validation rules specifically min length and max length.  the ValidateResult.valid property is incorrectly set at times. See demo project.  The ControllerValidateResult.valid property is always set to the correct state. 
[GIST DEMO](https://gist.run/?id=f8d6fa711287bad01a1fd57a554169ac)

**Expected/desired behavior:**

* **What is the expected behavior?**
The validate property should always be false if at least one validation rule fails

* **What is the motivation / use case for changing the behavior?**
For certain cases, knowing which property is invalid in the code is important as actions may need to be performed

**Comment by jdanyow** [comment]
I think I know what is causing the confusion here. The `minLength` / `maxLength` rules report "valid" when the text is null, undefined or empty string. It's the responsibility of the `required` rule to check whether the string is not null, undefined or empty. This may seem counter-intuitive but without this separation of responsibilities it would not be possible to define rules for a field that is optional but has a minLength of 3 when it is filled in.

**Comment by elitemike** [comment]
If you look at the demo, I do have required there along with the min required. It should never act as validated when the input is empty.

**Comment by jdanyow** [comment]
Your code was looking at the individual rule results rather than the overall result.

**Comment by elitemike** [comment]
My apologies, I have many validators in my real project and didn't bother to see if there was more than one result when  I was looping through in this GIST.  Anyways, is there functionality to know when an object is valid without validating each one separately? I will have an unknown number of objects with validation and I need to bubble the state up to a different UI element. I have a form with tabs and multiple levels within the tabs, I'm trying to expose the point an error is occurring.

**Comment by elitemike** [comment]
My workaround for my scenario so I can move on is to reset the property i'm tracking at object level to be valid. Then when I loop through validator results, I'm filtering on invalid only and setting my property. It works, but I also think I could utilize tags, though that would cause me to have to call validate an unknown number of times.  I would need to do performance testing to know which way is best, but right now the way that works is good enough and it only required me to make a minor change.  Again, thanks for pointing out my initial error, it makes complete sense now....

**Comment by jdanyow** [comment]
When you call controller.validate() you can provide an instruction that identifies which objects to validate. No instruction means validate them all. The method returns a promise that resolves to this: https://github.com/aurelia/validation/blob/master/src/controller-validate-result.ts

It has a prop that tells you whether overall validation passed or failed.

**Comment by elitemike** [comment]
Right, I'm aware of that. What I want doesn't exist built in, but I'm working with what is there. I would like to see a cleaner way of just knowing which objects are valid no matter how many validators that object has.  It would be nice to have an array of the objects on the ControllerValidateResult and then each object has the valid state along with the array of rule results for that object

**Comment by jdanyow** [comment]
Ah, ok- please open an issue for that and mention this issue number in it.
We can probably build that in pretty easily.
