### ISSUE TITLE
Auto-generate data validatiin based on server-side data model

### ISSUE THREAD

**Issue by brylie** [aurelia/validation#466]
**I'm submitting a feature request**

When designing a client/server application, it would be nice to maintain the data model in only one place, rather than having models defined on both client and server.

Out of curiosity, how might Aurelia ORM definitions be auto-generated from a server codebase, such as Django models?

What would be the general concepts involved in serializing a model definition from a server codebase, and de-serializing/using it in the Aurelia framework?

**Current behavior:**
Developers have to maintain tow definitions of their application data model.

**Expected/desired behavior:**
Client-side validators could be auto-generated from a serialized version of the server data model.

* **What is the motivation / use case for changing the behavior?**
To make it easier to maintain a client/server project, including changes, over time.

**Comment by jdanyow** [comment]
#363
