### ISSUE TITLE
Can not put validation rules on integer attributes

### ISSUE THREAD

**Issue by fracz** [aurelia/validation#474]
**I'm submitting a feature request or bug report, really don't know**

* **Library Version:**
1.1.2

I want to validate the following object:
```
let myObject  = {
  2: '',
  5: ''
};
```
The identifiers of properties are dynamic based on my data model.

**The 1st try**

```
ValidationRules.ensure(2).required().on(myObject);
```
results in the following error

> aurelia-task-queue.js:59 Uncaught Error: Unable to parse accessor function: 2

**The 2nd try**
```
ValidationRules.ensure(obj => obj[2]).required().on(myObject);
```
> Uncaught Error: Unable to parse accessor function: function (obj) { return obj[2]; }

OT: In fact, I have noticed that `.ensure(obj => obj.someProp)` works but `.ensure(obj => obj['someProp'])` does not. See [this gist](https://gist.run/?id=351e80d5800b85cefa465b886b4b0a45) for reference.

**The 3rd try**
```
ValidationRules.ensure('2').required().on(myObject);
```
builds the validation rules indeed, but they are not applied when used with `validate` binding behavior. I have debugged it down to [this line](https://github.com/aurelia/validation/blob/40060d7fbfd4ce2c042abe6d3b3006c2ade7a0af/src/implementation/standard-validator.ts#L104) which compares `'2' !== 2` and skips the validation.

**The 4rd try (ugly hack aka workaround)**
This works, but is far from pretty.
```
const v = ValidationRules.ensure('2').required();
v.rules.forEach(rules => rules.forEach(rule => rule.property.name = parseInt(rule.property.name)));
v.on(myObject);
```

**Comment by jdanyow** [comment]
If you change:

https://github.com/aurelia/validation/blob/40060d7fbfd4ce2c042abe6d3b3006c2ade7a0af/src/implementation/standard-validator.ts#L104

To:

```js
if (!validateAllProperties && rule.property.name !== propertyName.toString()) { 
```

does it work?

**Comment by fracz** [comment]
Adding the `toString()` there causes the validation to be applied on given field as expected. However, the error is not being rendered in the GUI (I am using "standard" `BootstrapValidationRenderer` from examples). It works, when using my hack so I guess there is another strict comparison somewhere.
