### ISSUE TITLE
Tag function missing

### ISSUE THREAD

**Issue by dweber019** [aurelia/validation#475]
**I'm submitting a bug report**

* **Library Version:**
1.1.2

* **Language:**
TypeScript 2.6 and Webpack

**Current behavior:**
The `tag` function described here http://aurelia.io/docs/plugins/validation#defining-rules does not exist in the lastest version.

**Expected/desired behavior:**
Tag function does exists and works as described in the doc.

* **What is the motivation / use case for changing the behavior?**
I dynamically add and remove validation rules and it would be nice, if I could filter rules by tags.

**Comment by Alexander-Taran** [comment]
@jdanyow is it actionable?

**Comment by dweber019** [comment]
Sorry got it wrong. It depends on the location in the method chain where you can use the tag method.
