### ISSUE TITLE
Cannot find module 'aurelia-validation'.

### ISSUE THREAD

**Issue by joelowrance** [aurelia/validation#476]
**I'm submitting a bug report**

* **Library Version:**
1.1.2

* **Operating System:**
Windows 10

* **Node Version:**
8.9.4

* **NPM Version:**
5.6.0

* **JSPM OR Webpack AND Version**
JSPM 0.16.53

* **Browser:**
all

* **Language:**
TypeScript X.X 

**Current behavior:**
"Cannot find module aurelia-validation"

**Expected/desired behavior:**
No errors.

**Steps to reproduce**

1.  Unzip typescript skeleton project
2.  Add `"aurelia-validation": "npm:aurelia-validation@^1.1.0",` to package.json or `jspm install aurelia-validation`
3. `npm install`
4. `node_modules` and `typings` folders are created.  The validation package is downloaded, but nothing is created in the `typings` directory unlike the rest of the Aurelia packages.

Both VS Code and gulp report the following error
`[09:27:11] gulp-notify: [Error running Gulp] Error: src\users.ts(3,36): error TS2307: Cannot find module 'aurelia-validation'.`

Below is the output from npm install.  In the `typings install` step, the other packages are listed.

PS D:\Dev\AuSkeletonGulp\skeleton-typescript> npm install
npm WARN deprecated es6-module-loader@0.17.11: This project has been deprecated for "npm install es-module-loader" based on the newer loader spec.
npm WARN deprecated typings@2.1.1: Typings is deprecated in favor of NPM @types -- see README for more information
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-f2 or higher to avoid a RegExp DoS issues 4 for compatibility with current and future versions of Node.js   .2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0 4 for compatibility with current and future versions of Node.js.2 or higher to avoid a RegExp DoS issue                            cote trying bluebird@https://registry.npmjs.org/bluebird/-/bluebird-3.5.1.tgz by hash: sha512-MKiLiV+I1AA596t9w1sQJ8jkiSr5+ZKi0WKrYGUn6d1Fx+Ij4tIj+m2WMQSGczs5jZVxV339chE8iwk6F64wjA==npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update t to graceful-fso minimatch 3                                         of Node.js
.0.2 or higher to avoid a RegExp DoS issue           ll pacote tryinpm WARN deprecated graceful-fs@1.2.3: please upgradenpm WARN deprecated minimatch@0.2.14: Please update t
o minimatch3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade
 to gracefulnpm WARN deprecated minimatch@0.2.14: Please update to minima
tch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgradenpm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade
 to granpm WARN deprecated minimatch@0.2.14: Please update to mi
nimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgradenpm WARN deprecated minimatch@0.2.14: Please update tominimatch 3.0.2 or higher to avoid a RegExp DoS issuenpm WARN deprecated graceful-fs@1.2.3: please upgrade
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
o minimatch 3.0.2 or higher to avoid3: please upgrade a RegExp DoS i                     with current andssue
npm WARN deprecated graceful-fs@1.2.mber-like: sillo minimatch 3.0.2 or higher to avoida RegExp DoS issuenpm WARN deprecated graceful-fs@1.2.
3nd future versions of Node.js
: please upgrade to graceful-fs 4 for: sill pacote
npm WARN deprecated graceful-fs@1.2.3: please upgradenpm WARN deprecated graceful-fs@1.2.3: pcurrent and fulease upgrade to graceful-fs 4 for compatibility wit  [h current an                            wline: sill pnpm WARN deprecated graceful-fs@1.2.3: p
lease upgrade to graceful-fs 4 for compatibility wi
th currentand future versions of Node.js
npm WARN deprecated graceful-fs@1.2.3: please upg
rade to graceful-fs 4 for compatibilitywith curr
npm WARN deprecated graceful-fs@1.2.3: p
lease upgrade to graceful-fs 4 for compatibility
 with current and future versions of Node.js
[           .......] | extract:ms: s[[grade to graceful-fs 4 for compatibility
 withcurrent and future versions of Node.js
[           .......] | extract:ms: s[[grade to graceful-fs 4 for compatibility
 with current and future versions of Node.js[           .......] | extract:ms: s[[  [
          [            ......] / extract:esp
[           .......] | extract:ms: s[[ [           [            ......] / extr
[           .......] | extract:ms: s[[   [           [            ......] / et   [           [                     ...   ......]               si[           . / extract:esprima: sill         ......epac[                      | extract:ent      ......] | extract:destroy: si
   [           [  ......] / extract:espri
m         ......] \ e[a: sill pac[            .
.....] | extract:ent[....] | extract:destroy:s
i[            ......] | e....] | extract:destroy:
si[            ......] | extract:u[            ......] \ e[            ......] | extract:ent[        [            .....[            ......] - extract:data-uri-to-bu[            ......] [        ......] | extract:data-[            .....[  [            ......] / extract[           ....          [            .....[            ......] - extract:data-uri-to-bu[            ......] bac
si[            ......] | extract:u[            ......] \ e[            ......] | extract:ent[            [            .....[            .......                                                                                                                                     [...] - extract:data-uri-to-bu[            ......] [            ......] | extract:data-[            .....[  [            ......] / extracct:bt[                                                                                                                                      [           .....[            ......] \ extract:backo2: sill pacote backo2@https://registry.npmjs.org/backo2/-/[            ......] \ extD:\si[            ......] | extract:u[            ......] \ e[            ......] | extract:ent[            [            .....[
.:backo2: sill pacote backo2@https://registry.npmjs.o[            ......] - extract[            ......] \ extract:colors: sill pacote co.....] - extract:data-uri-to-bu[            ......] [            ......] | extract:data-[            .....[  [            ......] / extr
a   [            ......] / extract:clean-css: sill pacote clean-css@https://registry.npmjs.org/clean-css/-/clean-css-4.1.9.tgz extractedsi[            ......] | extract:u[            ......] \ e[            ......] | extract:ent[            [            .....[......] - extract:data-uri-to-bu[            ......] [            ......] | extract:data-[            .....[  [            ......] / extract[         .....[            ......] \ extract:backo2: sill pacote backo2@https://registry.npmjs.org/backo2/-/[            ......] \ extract:backo          .....[            ......] \ extract:backo2: sill pacote backo2@https://registry.npmjs.org/backo2/-/[            ......] \ extract:bac                                                                                                                                           xtrko2: sill pacote backo2@https://registry.npmjs.o[            ......] - extract[            ......] \ extract:colors: sill pacote color[   [   ex        ......] / extract:clean-css: sill pacote clean-css@https://registry.npmjs.org/clean-css/-/clean-css-4.1.9.tgz ex[            ......] v\          .....[            ......] \ extract:backo2: sill pacote backo2@https://registry.npmjs.org/backo2/-/[            ......] \ extract:b
axtract:clean-css: sill pacote clean-css@https://registry.npmjs.org/clean-css/-/clean-css-4.1.9.tgz extracte[            ..[            .....cko2: sill pacote backo2@https://registry.npmjs.o[            ......] - extract[            ......] \ extract:colors: sill pacote color[   [
          ......] / extract:clean-css: sill pacote clean-css@https://registry.npmjs.org/clean-css/-/clean-css-4.1.9.tgz ex[            ......]t
 / extract:clean-css: sill pacote clean-css@https://registry.npmjs.org/clean-css/-/clean-css-4.1.9.tgz extracte[            ..[            ..           ......] / extract:clean-css: sill pacote clean-css@https://registry.npmjs.org/clean-css/-/clean-css-4.1.9.tgz ex[            ......] / extract:clean-css: sill pacote clean-css@https://registry.npmjs.org/clean-css/-/clean-css-4.1.9.tgz extracte[            ..[            ......] / ex[            ......] / extract:source-map: sill pacote source-map@https://registry.npmjs.org/source-map/-/source-map-0.5.7.tgz extracted t[            ......] / extract:source-map: sill pacote source-map@https://registry.npmjs.org/source-map/-/source-map-0.5.7.tgz extracted [            ......] / extract:source-map: sill pacote source-map@https://regis> uws@0.14.5 install D:\Dev\AuSkeletonGulp\skeleton-typescript\node_modules\uws> node-gyp rebuild > build_log.txt 2>&1 || exit 0
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> aurelia-skeleton-navigation-typescript@1.1.2 prepublish D:\Dev\AuSkeletonGulp\skeleton-typescript
> typings install

typings WARN badlocation "github:aurelia/binding" is mutable and may change, consider specifying a commit hash
typings WARN badlocation "github:aurelia/bootstrapper" is mutable and may change, consider specifying a commit hash
typings WARN badlocation "github:aurelia/dependency-injection" is mutable and may change, consider specifying a commit hash
typings WARN badlocation "github:aurelia/event-aggregator" is mutable and may change, consider specifying a commit hash
typings WARN badlocation "github:aurelia/fetch-client" is mutable and may change, consider specifying a commit hash
typings WARN badlocation "github:aurelia/framework" is mutable and may change, consider specifying a commit hash
typings WARN badlocation "github:aurelia/history" is mutable and may change, consider specifying a commit hash
typings WARN badlocation "github:aurelia/history-browser" is mutable and may change, consider specifying a commit hash
typings WARN badlocation "github:aurelia/loader" is mutable and may change, consider specifying a commit hash
typings WARN badlocation "github:aurelia/logging" is mutable and may change, consider specifying a commit hash
typings WARN badlocation "github:aurelia/logging-console" is mutable and may change, consider specifying a commit hash
typings WARN badlocation "github:aurelia/metadata" is mutable and may change, consider specifying a commit hash
typings WARN badlocation "github:aurelia/pal" is mutable and may change, consider specifying a commit hash
typings WARN badlocation "github:aurelia/pal-browser" is mutable and may change, consider specifying a commit hash
typings WARN badlocation "github:aurelia/path" is mutable and may change, consider specifying a commit hash
typings WARN badlocation "github:aurelia/polyfills" is mutable and may change, consider specifying a commit hash
typings WARN badlocation "github:aurelia/route-recognizer" is mutable and may change, consider specifying a commit hash
typings WARN badlocation "github:aurelia/router" is mutable and may change, consider specifying a commit hash
typings WARN badlocation "github:aurelia/task-queue" is mutable and may change, consider specifying a commit hash
typings WARN badlocation "github:aurelia/templating" is mutable and may change, consider specifying a commit hash
typings WARN badlocation "github:aurelia/templating-binding" is mutable and may change, consider specifying a commit hash
typings WARN badlocation "github:aurelia/templating-resources" is mutable and may change, consider specifying a commit hash
typings WARN badlocation "github:aurelia/templating-router" is mutable and may change, consider specifying a commit hash
typings WARN badlocation "github:aurelia/pal" is mutable and may change, consider specifying a commit hash
typings WARN badlocation "github:aurelia/pal" is mutable and may change, consider specifying a commit hash
typings WARN deprecated 2016-10-4: "registry:dt/whatwg-fetch#0.0.0+20160524142046" is deprecated (updated, replaced or removed)

**Comment by joelowrance** [comment]
Any update on this?

**Comment by RomkeVdMeulen** [comment]
I succesfully installed the `aurelia-validation` typings using this command:

```
typings install --save github:aurelia/validation#1.1.2
```

I added the version string because I'm manually keeping the version of the JSPM installed code and the typings synchronized, but the command will work without that.

**Comment by joelowrance** [comment]
@RomkeVdMeulen Tried this, but ended up with the same error as above above:

`typings\modules\aurelia-binding\index.d.ts(42,17): error TS2451: Cannot redeclare block-scoped variable 'getContextFor'. `

`typings\modules\aurelia-validation\index.d.ts(48,11): error TS2451: Cannot redeclare block-scoped variable 'getContextFor'.
`

Currently working around it by pointing my typings file to a forked repo where the offending line is commented out, but obviously that's not a viable long term approach.

**Comment by Alexander-Taran** [comment]
for JSPM setup you have to install typings separately
for d.ts conflict it is a the same issue: 
duplicate: https://github.com/aurelia/validation/issues/479

workaround applies.

**Comment by Alexander-Taran** [comment]
libraries involved updated and released
can be closed
