### ISSUE TITLE
validation package does not export ValidateCustomAttributeViewStrategyBase

### ISSUE THREAD

**Issue by mlaccetti** [aurelia/validation#48]
I'm attempting to create a custom validation strategy; according to the docs this should be sufficient:

validation.js:
```
import {ValidateCustomAttributeViewStrategyBase} from 'aurelia-validation';

export class CertChiefViewStrategy extends ValidateCustomAttributeViewStrategyBase {
  constructor() {
    super();
  }

  ...
}
```

Then configure the app to use the new validation strategy:
```
import {CertChiefViewStrategy} from './validation';
 
export function configure(aurelia) {
  aurelia.use
    .standardConfiguration()
    .developmentLogging()
    .plugin('aurelia-animator-css')
    .plugin('aurelia-validation', (config) => {config.useViewStrategy(new CertChiefViewStrategy())})
    .plugin('aurelia-bs-modal');
  aurelia.start().then(a => a.setRoot('app', document.body));
}
```

However, I get this nice error: `Super expression must either be null or a function, not undefined`

If I copy the `ValidateCustomAttributeViewStrategyBase` code into my class, everything is fine.  Is this a bug in the validator, framework, loader...?

**Comment by Aaike** [comment]
this is happening because the `aurelia-validation` package does not export `ValidateCustomAttributeViewStrategyBase`

change it to `import {ValidateCustomAttributeViewStrategyBase} from 'aurelia-validation/validate-custom-attribute-view-strategy';`

**Comment by mlaccetti** [comment]
`import {ValidateCustomAttributeViewStrategyBase} from 'aurelia-validation/validation/validate-custom-attribute-view-strategy';`

Fixed and happy

**Comment by janvanderhaegen** [comment]
Hey @mlaccetti ! Thanks for reporting this.
I reopened your issue, rather update the sources so the next person doesn't have to google the same exception! Thanks for the immediate support @Aaike !!

**Comment by janvanderhaegen** [comment]
https://github.com/aurelia/validation/commit/cfca0142fff2d1423f6e90eb635e64367e475375
