### ISSUE TITLE
Error target undefined.

### ISSUE THREAD

**Issue by jmdavid** [aurelia/validation#481]
I try to access the target element of error in a validation-summary, in order to give focus to element that has validation error, like this:
```
<ul class="error-summary-list" show.bind="errors.length">
        <li repeat.for="error of errors">
            <a class="error-summary-list-link" href="#" click.delegate="error.target.focus()"
               if.bind="controller!=null && autofocus">
                <template replaceable part="error">${error.message}</template>
            </a>
            <span if.bind="!(controller!=null && autofocus)">
        <template replaceable part="error">${error.message}</template>
        </span>
        </li>
    </ul>
```
But it seems that error.target is undefined.   There are many examples with that code, is it obsolete?  If so, how can I access the target?

**Comment by Alexander-Taran** [comment]
what the docs say?
http://aurelia.io/docs/plugins/validation#introduction

**Comment by jdanyow** [comment]
`element` is no longer a property of the `ValidationResult`, a while back things were refactored to support errors that were associated with multiple UI elements.

```html
  <form submit.delegate="submit()" validation-errors.bind="errorList">
    <ul>
      <li repeat.for="item of errorList">
        <a href="#" click.delegate="item.targets[0].focus()">
          ${item.error.message}
        </a>
      </li>
    </ul>
    ...
```

https://gist.run/?id=e66da4fd4abb25e08982fc1699bd78bb
