### ISSUE TITLE
Email validation passes without .com, .net, etc

### ISSUE THREAD

**Issue by raymak23** [aurelia/validation#487]
Hello,

I am using `Aurelia-Validation` in my project and trying to validate email address. When I add an email `example@g`, it passes the validation. Shouldn't email validation have `.com`, `.net`, etc at the end to pass the validation? See the [plunker ](https://plnkr.co/edit/8BO8AQ)link as an example.

Here is the screenshot:

![2018-04-25 10_09_35-plunker](https://user-images.githubusercontent.com/10405119/39251305-f37345ec-4870-11e8-8cad-cd54325eea48.png)

**Comment by Alexander-Taran** [comment]
technically you could have an email address @ root domains like .com .net .me .gl etc..

**Comment by raymak23** [comment]
yea, the problem is that validation shouldn't pass if the address does not have `.com`, `.net`, etc. Am I missing anything?  I think I may have to use regex to to additional validation.
