### ISSUE TITLE
No version match found for npm:aurelia-binding@^1.7.1 || ^2.0.0 when installing v1.2.0 using JSPM

### ISSUE THREAD

**Issue by paolostyle** [aurelia/validation#492]
**I'm submitting a bug report**

* **Library Version:**
1.2.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
8.9.2

* **NPM Version:**
5.8.0

* **JSPM**
JSPM 0.16.53

**Current behavior:**
See title - when installing latest (1.2.0) version using JSPM, I get this error:
```
err  Installing npm:aurelia-validation@1.2.0, no version match for npm:aurelia-binding@^1.7.1 || ^2.0.0

warn Installation changes not saved.
```
Seems like JSPM doesn't support `||` notation when specifing versions (see: https://github.com/jspm/jspm-cli/blob/master/docs/installing-packages.md). There are no such issues on NPM.

aurelia-templating-binding@1.4.2 has the same problem - should I report it on its GitHub page as well?

**Expected/desired behavior:**
Package should be installed properly without any errors.

**Comment by StrahilKazlachev** [comment]
Tracked in aurelia/framework#895

**Comment by bulldetektor** [comment]
This seems to be fixed with https://github.com/aurelia/validation/commit/4acb22803bf614e528548732c34acbd5beb7cdc6
