### ISSUE TITLE
IE11 changeOrBlur does not appear to wait for blur to validate on IE11

### ISSUE THREAD

**Issue by PWKad** [aurelia/validation#494]
**I'm submitting a bug report**
**I'm submitting a feature request**

* **Library Version:**
1.2.1

**Please tell us about your environment:**
* **Operating System:**
OSX 10.x

* **Node Version:**
8.9.3

* **NPM Version:**
5.5.1

* **JSPM OR Webpack AND Version**
JSPM 0.16.53

* **Browser:**
IE 11

* **Language:**
TypeScript 2.9.2

**Current behavior:**

When rendering a component with the validation controller's `validateTrigger` set to `changeOrBlur` the input appears to be validating and showing errors before a blur or change has occurred.  I tried to put together a repo in gist.run but forgot it doesn't run in IE11.  It works fine in Chrome.

I'm working on a repo currently but having issues due to really poor network connection at the moment.

**Expected/desired behavior:**

It acts the same.

**Comment by jdanyow** [comment]
@PWKad here's a plunker with validation- could you setup the repro there: http://plnkr.co/edit/4YDnUVs3HIoODMdOeZ4g?p=preview

(will work in IE)

**Comment by PWKad** [comment]
Of course, thanks, will do this today.

**Comment by PWKad** [comment]
Hmm I actually couldn't get Plunkr to open in IE11 will keep trying

**Comment by jdanyow** [comment]
@PWKad ok to close- turned out to be something else right?

**Comment by PWKad** [comment]
Yessir
