### ISSUE TITLE
ValidationMessageParser.parse  exception calling this.bindinqLanguage.parseInterpolation 

### ISSUE THREAD

**Issue by BojanPetkovic** [aurelia/validation#497]
**I'm submitting a bug report**

* **Library Version:**
1.2.2

**Please tell us about your environment:**
* **Operating System:**
10

* **Node Version:**
10.5.0

* **NPM Version:**
6.1.0

* **JSPM OR Webpack AND Version**
 webpack 4.1.1

* **Browser:**
Version 68.0.3440.75 (Official Build) (64-bit)

* **Language:**
TypeScript 2.7.2

**Current behavior:**
When flowing simple tutorial from https://aurelia.io/docs/plugins/validation/
there is exception:
Unhandled rejection TypeError: this.bindinqLanguage.parseInterpolation is not a function    at ValidationMessageParser.parse (webpack-internal:///./node_modules/aurelia-validation/dist/native-modules/implementation/validation-message-parser.js:34:42)    at ValidationMessageProvider.getMessage (webpack-internal:///./node_modules/aurelia-validation/dist/native-modules/implementation/validation-messages.js:42:28)    at StandardValidator.getMessage (webpack-internal:///./node_modules/aurelia-validation/dist/native-modules/implementation/standard-validator.js:70:63)    at eval (webpack-internal:///./node_modules/aurelia-validation/dist/native-modules/implementation/standard-validator.js:114:52)From previous event:    at _loop_1 (webpack-internal:///./node_modules/aurelia-validation/dist/native-modules/implementation/standard-validator.js:113:44)    at StandardValidator.validateRuleSequence (webpack-internal:///./node_modules/aurelia-validation/dist/native-modules/implementation/standard-validator.js:121:13)    at StandardValidator.validate (webpack-internal:///./node_modules/aurelia-validation/dist/native-modules/implementation/standard-validator.js:142:21)    at StandardValidator.validateProperty (webpack-internal:///./node_modules/aurelia-validation/dist/native-modules/implementation/standard-validator.js:44:21)    at execute (webpack-internal:///./node_modules/aurelia-validation/dist/native-modules/validation-controller.js:215:51)From previous event:    at ValidationController.validate (webpack-internal:///./node_modules/aurelia-validation/dist/native-modules/validation-controller.js:223:14)    at MdCreateCampaignDialog.onOk (webpack-internal:///components/campaigns/md-create-campaign-dialog:91:34)    at CallScope.evaluate (webpack-internal:///./node_modules/aurelia-binding/dist/native-modules/aurelia-binding.js:1578:19)    at Listener.callSource (webpack-internal:///./node_modules/aurelia-binding/dist/native-modules/aurelia-binding.js:5279:40)    at Listener.handleEvent (webpack-internal:///./node_modules/aurelia-binding/dist/native-modules/aurelia-binding.js:5288:10)    at HTMLDocument.handleDelegatedEvent (webpack-internal:///./node_modules/aurelia-binding/dist/native-modules/aurelia-binding.js:3363:20) 

**Expected/desired behavior:**

* **What is the expected behavior?**
No exception , works like in official tutorial

* **What is the motivation / use case for changing the behavior?**

**Comment by tankBug** [comment]
I also get this error after updating validation from 1.1.3 to 1.2.2.

**Comment by bigopon** [comment]
This seems like `BindingLanguage` is somehow not registered properly. Can I see your startup code in `main.js / ts` ?

**Comment by tankBug** [comment]
Sure, but it seems BindingLanguage isn't referenced in my startup code at all. I'm new to Aurelia, and I haven't purposefully added it. It just seems that the "validation-message-parser.js", a file that looks to be part of the "aurelia-validation" requires it, and also imports it (this is the first part of the file I copied from the dev tools, until it breaks):

`var __extends = (this && this.__extends) || (function () {
    var extendStatics = Object.setPrototypeOf ||
        ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
        function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
import { LiteralString, Binary, Conditional, LiteralPrimitive, CallMember } from 'aurelia-binding';
import { BindingLanguage } from 'aurelia-templating';
import * as LogManager from 'aurelia-logging';
import { ExpressionVisitor } from './expression-visitor';
var ValidationMessageParser = /** @class */ (function () {
    function ValidationMessageParser(bindinqLanguage) {
        this.bindinqLanguage = bindinqLanguage;
        this.emptyStringExpression = new LiteralString('');
        this.nullExpression = new LiteralPrimitive(null);
        this.undefinedExpression = new LiteralPrimitive(undefined);
        this.cache = {};
    }
    ValidationMessageParser.prototype.parse = function (message) {
        if (this.cache[message] !== undefined) {
            return this.cache[message];
        }
        var parts = this.bindinqLanguage.parseInterpolation(null, message);`

I don't know why they have misspelled the variable either, but that doesn't matter I suppose. 

Would you like to see my main.js anyway? If I need to add it to main.js, what would the syntax be?

**Comment by bigopon** [comment]
My guess is you registered validation plugin before calling `.standardConfiguration()`. And / or do something that triggered a `container.get(BindingLanguage)` before `aurelia.start()`. I got this issue once and it's exactly the same error

**Comment by tankBug** [comment]
Thanks for a quick reply!  
This is the order of how it's registered.  If I understood you correctly, this should be the right order?

`  aurelia.use
    .standardConfiguration()
    .feature(PLATFORM.moduleName('resources/index'))
    .plugin(PLATFORM.moduleName('aurelia-validation'))
    .plugin(PLATFORM.moduleName('aurelia-dialog'));`

I can't find any use of `container.get(BindingLanguage)` at all in my code, could that be the problem?

**Comment by bigopon** [comment]
The order looks fine. Did you call `aurelia.container.get` inside your startup before `aurelia.start()`, if not then I'm not sure what's causing the issue.

**Comment by tankBug** [comment]
> aurelia.start()
>       .then(() => {
>         let info = aurelia.container.get(InfoService);
>         let auth = aurelia.container.get(AuthService);
>         return auth.load(refreshToken).then((isAuthenticated) => {
>           let root = PLATFORM.moduleName('layouts/login');
>           document.documentElement.className = 'login-page';
>           if (isAuthenticated) {
>             root = PLATFORM.moduleName('layouts/main');
>             document.documentElement.className = '';
>           }
>           return aurelia.setRoot(root);
>         });
>       });

This is how it starts up. The aurelia.container() doesn't include the BindingLanguage at all, just the authentication service and info service. 

In the validation-message-parser, it can find the BindingLanguage, but the parseInterpolation function seems to be non-existent, so I'm currently looking into updating the aurelia-binding and dependencies, but after I updated the framework to the latest version, I've gotten a new error instead:

`Unhandled rejection TypeError: Cannot read property 'attrToRemove' of undefined`

So, I guess I'll have to update them all, and see if that resolves it. 

Btw, I'm using webpack, can this somehow be a problem?

**Comment by tankBug** [comment]
Update: 

I updated most of the aurelia packages, and after struggling with a non-working Gulp, I have now progressed (hopefully), and encountered a different error : 

`Unhandled rejection Error: BindingLanguage must implement inspectTextContent().`

I suppose that a discussion about that error doesn't belong in this thread, though.

**Comment by bigopon** [comment]
The error you just encountered is still the same with the previous one. Somewhere in your app, before the Aurelia instance has a chance to init the plugins, some plugins being loaded trigger the view compilation and thus causing the issue. I recommend commenting out part of the app from root and see which module is causing the issue.

**Comment by tankBug** [comment]
I see, I will investigate further. But do you think it makes sense that I don't get any errors when using aurelia-validation 1.1.3 vs 1.2.2, though?

**Comment by jdanyow** [comment]
should be fixed by #500
