### ISSUE TITLE
Validating multiple similar objects isn't working

### ISSUE THREAD

**Issue by fedoranimus** [aurelia/validation#498]
**I'm submitting a bug report**

* **Library Version:**
1.2.3

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
8.11.1+

* **NPM Version:**
6.2.0+

* **JSPM OR Webpack AND Version**
webpack 4+

* **Browser:**
all

* **Language:**
TypeScript 3.1

**Current behavior:**
As I mentioned on [StackOverflow](https://stackoverflow.com/questions/52141917/aurelia-validation-clarity-on-object-validation-w-addobject) I'm running into issues with validating objects using Aurelia-Validation.

I've created a custom element that returns an object via an onchange event:
`<type-ahead placeholder="Search for an airport..." change.delegate="updateAirport($event.detail, true)"></type-ahead>`

Whenever that change fires, the `updateAirport(...)` method is called on my VM:
```javascript
updateAirport(airport: IAirport, isOrigin: boolean) {
  if(isOrigin) {
    this.controller.removeObject(this.origin);
    this.origin = airport;
    this.controller.addObject(this.origin, this.originAirportRules);
  } else {
    this.controller.removeObject(this.destination);
    this.destination = airport;
    this.controller.addObject(this.destination, this.departureAirportRules);

    this.validate();
  }
}
```

Additionally, I've defined the following rules (called during bind()):
```javascript
private setupValidation() {
  ValidationRules.customRule(
    'airport',
    (value: IAirport, obj) => { 
      if(value && value.iata && value.iata.length === 3)
        return true;
      else
        return false;
      },
      `\${$displayName} must be an airport`
  );

  ValidationRules.customRule(
    'date',
    (value: Date, obj) => {
      return value instanceof Date
    },
    `\${$displayName} must be a Date.`
  );

  this.dateRules = ValidationRules
    .ensureObject()
      .required()
      .satisfiesRule('date')
    .rules;

  this.originAirportRules = ValidationRules
    .ensureObject()
      .required()
      .satisfiesRule('airport')
    .rules;

  this.departureAirportRules = ValidationRules
    .ensureObject()
      .required()
      .satisfiesRule('airport')
  .rules;

  this.controller.addObject(this.origin, this.originAirportRules);
  this.controller.addObject(this.destination, this.departureAirportRules);
  this.controller.addObject(this.departureTime, this.dateRules);

  this.validate()
    }
```

And the validate() call is just this:
```javascript
private validate() {
  this.controller.validate()
    .then(results => {
      console.log(results);
      this.canSubmit = results.valid;
    });
}
```

**Expected/desired behavior:**

* **What is the expected behavior?**
1. I wouldn't expect to have to call `.removeObject(...)` and then `.addObject(...)` on the controller in order to see validation updates. If I don't do this in `updateAirport(...)` the values in my controller never change, even though the objects have changed. (this.origin = airport)
2. Even though I add two airports (`this.origin` & `this.destination`), only the most recently changed one is displayed in my validation results array. See screenshot below (I would expect 6 rules, not 4. Also, this is only showing the destination, even though I had set the origin before this point)

![image](https://user-images.githubusercontent.com/179260/46224964-d9cb8480-c325-11e8-8fe2-7ad10b1d0f78.png)

* **What is the motivation / use case for changing the behavior?**
It's the behavior I would expect.

**Comment by bigopon** [comment]
@fedoranimus 

From https://github.com/aurelia/validation/blob/master/src/validation-controller.ts#L218

When invoking `.validate()` on a validation controller, it validates all existing object/rules pairs. Adding a new pair doesn't remove old pair and that's I think why is the reason valid on validation result did not change.

I think what you want to do is to define a custom rule, that look up for specific property `origin`/`destination` on an object, so that whenever you change it to new object, it will still be validated properly. 

Btw, if you could help setup what you want to do in a codesandbox, it'd be great. You can base on this https://codesandbox.io/s/1y1vkw6lnq (check the cutom-rules file, I've setup custom rule `airportTrip` to show what I meant above)

**Comment by fedoranimus** [comment]
@bigopon Okay, let me do some testing and I'll get back to you soon.

For some reason I didn't get a notification of your message so I'm just seeing this now.

**Comment by fedoranimus** [comment]
Thanks for your suggestion @bigopon. I got my validation to work by encapsulating everything in an object:

```typescript
private model: IModel = {
    origin: null,
    destination: null,
    departureTime: new Date()
}
```

Then I created rules as you suggested:

```typescript
private isValidAirport(airport: IAirport) {
    return airport && airport.iata && airport.iata.length === 3;
}

private validate() {
    this.controller.validate({ //NOTE: I found it had I had to specify these manually; empty ruleset otherwise
        object: this.model,
        rules: this.ruleSet
    })
    .then(results => {
        this.canSubmit = results.valid;
    });
}

private setupValidation() {
    ValidationRules.customRule(
        'date',
        (value: Date, obj) => {
            return value instanceof Date
        },
        `\${$displayName} must be a date`
    );

    ValidationRules.customRule(
        "airportTrip",
        (value, obj) => {
            return this.isValidAirport(obj.origin) && this.isValidAirport(obj.destination)
        },
        `\${$displayName} must be a valid route`
    );

    this.ruleSet = ValidationRules 
        .ensureObject()
            .required()
            .satisfiesRule('airportTrip')
        .ensure((m: IModel) => m.departureTime)
            .required()
            .satisfiesRule('date')
        .rules; //NOTE: Along with my earlier comment, this originally was .on(this.model), but it wasn't being associated with the controller
}
```

**Comment by bigopon** [comment]
@fedoranimus Glad to hear that 👍

**Comment by fedoranimus** [comment]
From my perspective, this issue can be closed now. Thank you for your help.

**Comment by bigopon** [comment]
@fedoranimus Thanks for the reminder. As I understand, this issue comes from an expectation that adding a new object/rules pair to a validation controller will make it validate only that newly added pair and ignore existing ones. If it's correct, it would be great if you could help our documentation based on your experience about this matter.

**Comment by fedoranimus** [comment]
@bigopon Ah, that's not the expectation I had.

My expectation is that _all_ object/rule pairs added to a validation controller would be validated. The current behavior is that _only the new_ object/rules pair is validated if the object is of the same shape (same properties). If two different objects are added (Airport & Date), the validation works as expected, but if two of the same objects (Airport x2) are added, the previous object seems to be replaced.

Does that make sense?
