### ISSUE TITLE
Split documentation

### ISSUE THREAD

**Issue by janvanderhaegen** [aurelia/validation#5]
ReadMe.MD is becoming too large to be useful... tl;dr
Need to split this into a quick 'overview'/'cheat cheat'/'example' page and multiple 'deeper dive' documents/examples...

**Comment by PWKad** [comment]
We can start to utilize the docs app to help with this by breaking the files down to sections and loading them up from aurelia/validation/docs (while still letting them stay here in the github repo)

**Comment by PWKad** [comment]
Tracking on task list at https://github.com/aurelia/validation/issues/174
