### ISSUE TITLE
Update Import of customAttribute to be from 'aurelia-templating' instead of 'aurelia-framework'

### ISSUE THREAD

**Issue by alienriver49** [aurelia/validation#506]
**I'm submitting a bug report**

* **Library Version:**
1.3.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
8.11.2

* **NPM Version:**
6.4.1

* **JSPM OR Webpack AND Version**
JSPM 0.16.53

* **Browser:**
all

* **Language:**
all

**Current behavior:**
validation-renderer-custom-attribute.ts imports customAttribute from 'aurelia-framework' which isn't listed as a dependency or peerDependency of the library. So, if you don't have it installed, you have to manually install it. I imagine most users already have this installed as a dependency, but we have a special case where we've wrapped the Aurelia framework with our own framework so our developers only need to install a few aurelia specific packages (aurelia-validation being one of them). JSPM then doesn't have the needed map for aurelia-framework.

**Expected/desired behavior:**
Just import customAttribute from aurelia-templating since this is already a dependency and used in the other custom attribute in this library.

**Comment by bigopon** [comment]
@alienriver49 Would be nice if you could submit a PR to fix this 👍

**Comment by alienriver49** [comment]
Done!

**Comment by Alexander-Taran** [comment]
@bigopon can you review? (-:

**Comment by bigopon** [comment]
Well, it's a simple fix, and @alienriver49 already did everything. Only waiting for @jdanyow or @EisenbergEffect to merge

**Comment by jdanyow** [comment]
merged- thanks @alienriver49 !
