### ISSUE TITLE
I am refering to aurelia validation.d.ts file from the  path"aurelia-validation": "github:aurelia/validation/dist/types/aurelia-validation.d.ts", but now it have been moved to parent folder results in 404 error for us. I can update the path, but could you point which is the right path.

### ISSUE THREAD

**Issue by dhanapalschandran** [aurelia/validation#510]
**I'm submitting a bug report**
**I'm submitting a feature request**

* **Library Version:**
major.minor.patch-pre

**Please tell us about your environment:**
* **Operating System:**
OSX 10.x|Linux (distro)|Windows [7|8|8.1|10]

* **Node Version:**
6.2.0

* **NPM Version:**
3.8.9

* **JSPM OR Webpack AND Version**
JSPM 0.16.32 | webpack 2.1.0-beta.17

* **Browser:**
all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView

* **Language:**
all | TypeScript X.X | ESNext

**Current behavior:**

**Expected/desired behavior:**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

**Comment by bigopon** [comment]
@dhanapalschandran Hi, what is your package version? Checking the package json file I think everything is having the value it should have. Can you describe a bit more about your error?

**Comment by spapaseit** [comment]
Hi @bigopon, I think the issue is that release v1.3.1 has either some breaking changes or misses files. I get several typescript errors for things like `ValidationController` not being found.

It all started a couple of hours back, together with the release of 1.3.1, and reverting to v1.3.0 fixes everything. Everything points at v1.3.1 being broken.\

**Comment by bigopon** [comment]
@spapaseit @dhanapalschandran Hi I just examined the package and realized my previous statement was wrong. It's indeed has wrong config. Submitting a PR soon. Sorry for that 😓
