### ISSUE TITLE
The 1.3.1 npm package is broken

### ISSUE THREAD

**Issue by pvalsecc** [aurelia/validation#511]
**I'm submitting a bug report**

* **Library Version:**
1.3.1

**Please tell us about your environment:**
* **Operating System:**
Ubuntu 18.04

* **Node Version:**
v8.10.0

* **NPM Version:**
3.5.2

* **JSPM OR Webpack AND Version**
webpack 4.23.1

* **Language:**
TypeScript 3.1.3

**Current behavior:**

Cannot find the class when doing:

```
import {
    ValidationRenderer,
    RenderInstruction,
    ValidateResult
} from 'aurelia-validation';
```

**Expected/desired behavior:**

Compile without error

**Comment by bigopon** [comment]
@pvalsecc Hi I've identified the issues. Will create a fix soon. Sorry for this 😓
