### ISSUE TITLE
Question: change event bubble behavior for INPUT TYPE="TEXT" elements

### ISSUE THREAD

**Issue by airboss001** [aurelia/validation#513]
I am doing some validation on my form fields where when a field is changed and validation is complete I need to check overall state and then enable or disable some actions. This form does have some nested checks (if changed then make sure value is this or return not valid)

@davismj recommended binding to the change event on the form container and doing that check there.

So I made that change and this is working, but in a limited fashion as it seems to only work for the select and input fields that are of type="checkbox" in my form. Where things go wonky is if the input field is of type="text", then there is no bubbling of the change event, and my change.bind is never being called when the text field has its value changed and my action is never being updated.

Here is a gist.run that shows the basics of how I am doing the validation.
If a change event is fired then there is a momentary message displayed.

To enable the button make a selection in Section 1, then any text in Section 3, and click off the input field to get the button to show enabled. Expected behavior is that when any text is entered it should enable in this case, not when clicking off.

You can see that when you enter anything in the text fields nothing is fired for the change event.

https://gist.run/?id=d20ab1beb72b3d475b1c63838ecbd585

Is this expected behavior?
If I needed to get that functionality is there any suggestions on how to do that?

(here is the thread on discourse)
https://discourse.aurelia.io/t/aurelia-validation-using-satisfies-and-when/2020/6

**Comment by airboss001** [comment]
I just tried keydown.delegate="validateChange()" and no change from change.delegate="validateChange()".

**Comment by airboss001** [comment]
I started off there, my numpad uses inputmask to (its a masked numpad to control entry format) and ended up for some reason going back to a string that I don't remember why now.
for example here is how the attribute is used:
```
<input type="text" value.bind="paveTimecard.data.wind & validate" readonly masked-numpad="mask.bind:'^[0-9]{5,5}[-]?[0-9]{0,2}$'; remove-leading-zeros.bind: false; show-dash.bind: true;">
```

**Comment by davismj** [comment]
You're getting into some pretty specific behavior here. It's a tricky problem to solve. In any case, Aurelia has no control over what events are fired from inputs. The browsers handle that.

You might want to try (a) using a pattern or (b) `<input type="tel" />`. Keeping things simple and using as many default components as possible means that things will behave more predictably. See this old but useful post. https://stackoverflow.com/questions/27103646/html5-input-type-number-with-regex-pattern-in-mobile

You might also try making sure that your change event that you are firing manually bubbles.

**Comment by airboss001** [comment]
First off, thank you for taking your time on this. I really appreciate it.

My issue is that this is an PWA application for student/rental pilots that will be using it while flying using iPads. The iOS keyboard is a real pain to try and hit the right key when there is any bouncing around, hence the custom larger button numpad layout for easier, specialized entry. I created a iOS app that had this feature and I am trying to replicate it on the PWA as the pilots are use to it and like the larger format.

**Comment by davismj** [comment]
Try (a) and (b) above to see if you can get the number input without having to do too much extra work.

**Comment by airboss001** [comment]
Ok, I found it.
My change event in the numpad did not explicitly set the bubbles flag.
I set that on event the event and now I am getting the correct response.

Thanks so much for getting my pointed in the right direction Matthew!

**Comment by davismj** [comment]
https://gist.run/?id=040775f06aba5e955afd362ee60863aa

Oops I was a minute too late.

**Comment by airboss001** [comment]
lol, story of my life. Thanks again!
