### ISSUE TITLE
1.3.2 Validate method throws error

### ISSUE THREAD

**Issue by gregoryagu** [aurelia/validation#515]
**I'm submitting a bug report**
* **Library Version:**
1.3.2

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Browser:**
all 
* **Language:**
TypeScript

**Current behavior:**
Exception is thrown when calling validationController.validate()
TypeError: this.bindingLanguage.parseInterpolation is not a function.

`this.validationController.validate();`

I tried reproducing this on gist.run.  However, the 1.3.2 does not appear to be being used yet on the same gist as when I run it on my machine, and on gist.run, different code is being run.  Gist.run runs successfully, mine does not.  I think I am running more recent code.

Looking at the debugger, there is no parseInterpolation function on this.bindingLanguage, which is why the exception is being thrown.

My code:

```
 ValidationMessageParser.prototype.parse = function (message) {
        if (this.cache[message] !== undefined) {
            return this.cache[message];
        }
        var parts = this.bindinqLanguage.parseInterpolation(null, message);
        if (parts === null) {
            return new LiteralString(message);
        }
        var expression = new LiteralString(parts[0]);
        for (var i = 1; i < parts.length; i += 2) {
            expression = new Binary('+', expression, new Binary('+', this.coalesce(parts[i]), new LiteralString(parts[i + 1])));
        }
        MessageExpressionValidator.validate(expression, message);
        this.cache[message] = expression;
        return expression;
    };
```

These are the properties of this.bindingLanguage: (Note the type is of Binding Language)

```
createAttributeInstruction: ƒ createAttributeInstruction(resources, element, info, existingInstruction)
createLetExpressions: ƒ createLetExpressions(resources, element)
inspectAttribute: ƒ inspectAttribute(resources, elementName, attrName, attrValue)
inspectTextContent: ƒ inspectTextContent(resources, value)
constructor: ƒ BindingLanguage()
__proto__: Object
```

This is the properties of this.bindingLanguage when run on Gist.run (note that the type is TemplatingBindingLanguage)

```
attributeMap: AttributeMap {elements: {…}, allElements: {…}, svg: SVGAnalyzer}
emptyStringExpression: LiteralString {isChain: false, isAssignable: false, value: ""}
observerLocator: ObserverLocator {taskQueue: TaskQueue, eventManager: EventManager, dirtyChecker: DirtyChecker, svgAnalyzer: SVGAnalyzer, parser: Parser, …}
parser: Parser {cache: {…}}
syntaxInterpreter: SyntaxInterpreter {parser: Parser, observerLocator: ObserverLocator, eventManager: EventManager, attributeMap: AttributeMap, language: TemplatingBindingLanguage}
__proto__: BindingLanguage
```

**Expected/desired behavior:**
Validation Completes successfully

**Comment by bigopon** [comment]
This is definitely duplicate version of something issue. Thought I'm not sure where it originates from, maybe there are some 3rd party plugin that uses old version of templating/binding or something?

**Comment by gregoryagu** [comment]
Thanks for the response.  I am going to close this, as it is no longer an issue.  (Not really sure what happened to resolve)

**Comment by Paul-Moura** [comment]
Hi.
I'm having this same issue; receiving the same exception. I've spent 8 hours today trying to find a solution. How would I identify if there is a duplicate version of something?

**Comment by MaximBalaganskiy** [comment]
Try searching for aurelia-templating aurelia-binding folders in
node_modules. If there is more than one you got a duplicate

**Comment by Paul-Moura** [comment]
Nope. One of each. 
I previously tried deleting the node_modules folder and running `npm install` per the recommendation of another thread. No change. I then ran `npm update`. No change.

**Comment by MaximBalaganskiy** [comment]
Delete the lock file as well

**Comment by Paul-Moura** [comment]
That did it!! You're the bomb.com!! Thank you!!
