### ISSUE TITLE
Instrumented code for code coverage is not getting parsed correclty

### ISSUE THREAD

**Issue by hiaux0** [aurelia/validation#571]
#547 addresses a related issue.
(other related: https://github.com/aurelia/testing/issues/94)

## Problem

What I found, is that the instrumented code (maybe special to this lib [`@jsdevtools/coverage-istanbul-loader`](https://github.com/JS-DevTools/coverage-istanbul-loader)) is using methods instead of simple properties

> :warning: There is a bug when parsing code, that has coverage-helper-code.
More specifically, aurelia-validation does not parse the helper code correctly https://github.com/aurelia/testing/issues/94.
I found a fix, but would need to PR to the aurelia repo and stuff.
(Maybe we just fork ourselves, will create a ticket)
![image](https://user-images.githubusercontent.com/30693990/167618939-6905fb74-12d8-4c26-a3f3-c8c05f60c443.png)

```diff
function (a) {
-    cov_2n0ovlwwxg.f[2]++;    // "normally"
+    cov_2n0ovlwwxg().f[2]++;   // maybe only @jsdevtools/coverage-istanbul-loader?
    return a.message;
}
```
## Suggested fix

A fix I found is to update the parts of the regex by including `()` (open and close paren)
```diff
export function getAccessorExpression(fn: string): string {
  /* tslint:disable:max-line-length */
-  const classic = /^function\s*\([$_\w\d]+\)\s*\{(?:\s*"use strict";)?(?:[$_\s\w\d\/\*.['"\]+;]+)?\s*return\s+[$_\w\d]+\.([$_\w\d]+)\s*;?\s*\}$/;
+  const classic = /^function\s*\([$_\w\d]+\)\s*\{(?:\s*"use strict";)?(?:[$_\s\w\d\/\*.['"\]+();]+)?\s*return\s+[$_\w\d]+\.([$_\w\d]+)\s*;?\s*\}$/;
                                                                                              ^ actual change here
```

----

Keywords: 
@jsdevtools/coverage-istanbul-loader
code coverage instrumented code

**Comment by bigopon** [comment]
@hiaux0 there @hiaux0 there are existing tests here <https://github.com/aurelia/validation/blob/862da07647f653036e4e2b29d4318d7fa8fec698/test/property-accessor-parser.ts#L47-L54>

It seems the fix is already figured out, can you help create a PR with some tests @hiaux0 ?

**Comment by hiaux0** [comment]
@bigopon 

> existing tests

Afai can see, it fixes just for normal properties, and not methods, ie.
```diff
- __gen$field.f[\'10\']
+ __gen$field().f[\'10\'] // I'm expecting `()`
```

> create a PR

yeah, I planned to when I find some spare time
