### ISSUE TITLE
Validation object not getting injected

### ISSUE THREAD

**Issue by sunptech** [aurelia/validation#60]
I have this class
```javascript
import {Validation} from 'aurelia-validation';
export class SignupModel {
     static inject() { return [Validation]; }
     constructor(validation) {
        console.log(validation); // logs as: undefined
        this.userName = '';
       this.validation = validation.on(this)
            .ensure('userName')
            .isNotEmpty()
            .hasLengthBetween(3, 10);
     }
}
```
I have also added the plugin to main
```javascript
export function configure(aurelia) {
  aurelia.use
    .standardConfiguration()
    .developmentLogging()
    .plugin('aurelia-validation')
    .plugin('./resources/index'); 

  aurelia.start().then(a => a.setRoot());
}
```
But not sure why, *validation* object is **undefined** in constructor.
Am I missing something?

**Comment by anthonyettinger** [comment]
This may help: https://stackoverflow.com/questions/30518642/how-to-use-aurelia-validate-with-a-object-properties-to-validate/30520646#30520646

**Comment by sunptech** [comment]
@anthonyettinger thanks for the response. The issue I am having is that the *validation* object itself is NOT injected in the SignupModel. it logs as **undefined**
But if try this
```javascript
import {Validation} from 'aurelia-validation';
export class SignupViewModel {
     static inject() { return [Validation]; }
     constructor(validation) {
        console.log(validation); // Correctly logs the object: *Object {observerLocator: Object, config: ValidationConfig}*
       }
}
```

**Comment by chovy** [comment]
seems like you haven't enabled `aurelia-validation`

**Comment by sunptech** [comment]
I have that.
<body aurelia-app="main">
and in main
```javascript
export function configure(aurelia) {
  aurelia.use
    .standardConfiguration()
    .developmentLogging()
    .plugin('aurelia-validation')
    .plugin('./resources/index'); // install application resources such as value-converters and custom html attributes.

    //.plugin('aurelia-breeze');   // install the aurelia-breeze integration plugin.

  aurelia.start().then(a => a.setRoot());
}
```

**Comment by janvanderhaegen** [comment]
@sunptech good news: you've set up the validation plugin correctly (and it even works in your viewmodels).
Now, if it works in your viewmodels but not in your models, it feels like your models are not being resolved by the correct aurelia container which does the injection. My gut feeling is that if you'd have anything else injected (custom repo, aurelia router, whatever), it would also not work. 
Could you show the piece of code where you instantiate your model? IE: how does your viewmodel get a model? Where does it come from?

**Comment by sunptech** [comment]
@janvanderhaegen you are right, it doesn't inject any of the aurelia components. I got it working in a different way: manually instantiate validation object and pass that to Model constructor
```javascript

**//Model**
import {ObserverLocator} from 'aurelia-framework';
import {Validation} from 'aurelia-validation';
export class SignupModel {
   constructor(validation) {
        this.userName='';
        console.log(validation);
        this.validation = validation.on(this)
        .ensure('userName')
            .isNotEmpty();
    }
static createInstance() {
        let j = new Validation(new ObserverLocator());
        console.log(j);
        return new SignupModel(j);
  }
}

**//VM**
@inject(SignupService)
export class Signup extends EntityViewModel {
    constructor(service) {
        super(service);
    }
}

**//EntityViewModel**
export class EntityViewModel {
    service;
    entity;
    constructor(service) {
        this.service = service;
    }

    activate(info) {
             if(info.id==='new'){
                this.entity=service.createNew();
             }
        }
}

//and the **SignupService**
import {BaseService} from '../base-service'
import {SignupModel} from './signup-model'

export class SignupService extends BaseService{
    constructor() {
        super();
    }
    loadExisting(id) {     }

    createNew() {
        return SignupModel.createInstance();
    }

    save(entity) {
        this.client.post('/users', entity).then(response => {
            console.log(response);
        });
    }
}
```

**Comment by janvanderhaegen** [comment]
Awesome, glad you got it working.

You're not passing the validation config to the constructor of the Validation object, as a second parameter. This happens to work as it will grab the default validation config, and the chance of us changing that internal detail is small.

Still, for the sake of safety but also making your code more S.O.L.I.D., you can inject the validation in your SignupService instead, then pass it to the constructor of your model from within the service.

Either way, glad we did find out a solution!!

**Comment by sunptech** [comment]
Thanks @janvanderhaegen as part of code cleanup, I had ended up doing same as you suggested (inject Validation) in service. Though I had overlooked config part. 
appreciate your help.

**Comment by janvanderhaegen** [comment]
Awesome!
For future reference (anyone coming across this post in the future): the validation library has a default configuration. In case you instantiate the validation without passing configuration, it'll grab this default configuration. This is the same configuration [that is passed when you install the plugin](https://github.com/aurelia/validation/blob/master/doc/Intro.md#one-config-to-rule-them-all).
It might be helpful (tests) to explicitly pass a validation, although usually you'll just want to use the 'main' configuration and override it at the level you need it (validation group, property, rule).
