### ISSUE TITLE
Support 'all fields are mandatory'

### ISSUE THREAD

**Issue by janvanderhaegen** [aurelia/validation#61]
Currently, all fields are optional. You have to signal every required field using .isNotEmpty().

The inverse should be possible too: all fields are required, dev has to signal optional fields using .canBeEmpty() or .isOptional().

Comments on best API?

**Comment by chovy** [comment]
Seems like it should just work off the `required` attribute on an input field.

**Comment by janvanderhaegen** [comment]
@chovy 
I have a couple of doubts if that should be the only implementation
a) not all value bindings will come from an input field (rich text editors, drag & drop, etc)
b) it mixes the view-model first approach with the view approach. Your rules are in the view-model, but if a field is optional or required is based on the view that binds to it
We should definitely do that when we support pure view-first declaration though: https://github.com/aurelia/validation/issues/7

**Comment by janvanderhaegen** [comment]
Fixed, see https://github.com/aurelia/validation/blob/master/doc/Intro.md#configtreatallpropertiesasmandatory
