### ISSUE TITLE
does validation work with foundation?

### ISSUE THREAD

**Issue by chovy** [aurelia/validation#62]
All the examples use bootstrap, I am wondering if foundation (zurb) is supported.

**Comment by janvanderhaegen** [comment]
@Chovy not natively, we only support TWBS so far.
If you want to, you can inherit ValidateCustomAttributeViewStrategyBase (https://github.com/aurelia/validation/blob/master/src/validation/validate-custom-attribute-view-strategy.js).
The only two methods to implement are
```
  prepareElement(validationProperty, element){
    throw Error('View strategy must implement prepareElement(validationProperty, element)');
  }
  updateElement(validationProperty, element){
    throw Error('View strategy must implement updateElement(validationProperty, element)');
  }
```
The first is called when binding happens. Element is your input element.
UpdateElement is called when the property (https://github.com/aurelia/validation/blob/master/doc/Intro.md#validationresult) changes (either isDirty, failingRule, isValid).

Then, set your custom view strategy on the main config (when installing aurelia-validation): https://github.com/aurelia/validation/blob/master/doc/Intro.md#configuseviewstrategyviewstrategyinstance. 

Feel free to share back your implementation and we can add it to the view strategies available by default :)

Thanks!

Jan
