### ISSUE TITLE
Does validation work in IE9/10?

### ISSUE THREAD

**Issue by janvanderhaegen** [aurelia/validation#64]
@BWard62 reported there's a nullref exception in older IE versions which are supported by the other aurelia libraries

**Comment by zewa666** [comment]
As mentioned in gitter the issue is related to this section here:
https://github.com/aurelia/validation/blob/master/src/validation/validation-group.js#L33-L36

If I comment that one out, the validation plugin works for IE9 as well

**Comment by BWard62** [comment]
Excellent!  Thank you for the great work on the validation plugin.
