### ISSUE TITLE
Add a 'submitted' class to the validate element after validate()

### ISSUE THREAD

**Issue by csaloio** [aurelia/validation#72]
I think it would be helpful if after someone calls validate() that the element with the validator bound on it  get some time of 'submitted' class on it to assist with styling the input controls it wraps.

So in this example:
```
<div validate.bind="validator">
                <input value.bind="firstname"/>
                <input value.bind="lastname"/>
</div>
```

After validate() had been called I'm suggesting this:
```
<div validate.bind="validator" class='submitted'>
                <input value.bind="firstname"/>
                <input value.bind="lastname"/>
</div>
```

**Comment by janvanderhaegen** [comment]
Hey csalolo,
I'll see if we can add some extra configuration/extension points to our view behavior so you can very easily implement your use case.
Will see to it this weekend.

Thanks

Jan

**Comment by csaloio** [comment]
Wonderful, thank you.

**Comment by PWKad** [comment]
Tracking at https://github.com/aurelia/templating-validation/issues/5
