### ISSUE TITLE
error when building the project: 'this' is not allowed before super()

### ISSUE THREAD

**Issue by atsu85** [aurelia/validation#74]
Hi, 
Building the code as instructed here
https://github.com/aurelia/validation/#building-the-code
fails with 
```
SyntaxError: c:/tmp/proj/cloned/aurelia/validation/src/validation/validation-rules.js: Line 143: 'this' is not allowed before super()
```
because following line
https://github.com/aurelia/validation/blob/master/src/validation/validation-rules.js#L143
is in a callback function that is given as an argument to the constructor of superclass.

@janvanderhaegen added this callback (with problematic line) 3 weeks ago with commit:
https://github.com/aurelia/validation/commit/5499ab6f59b719b7efc6c5e9d44510b8dfc3987d#diff-94ed0400a42b76c71f45ce4101d2255fR143

I'm wondering if I've done smth wrong myself or is the project really broken already for 3 weeks (broken already before the last release)? Could it be, that it works for someone because of using some older babel version?

**Comment by EisenbergEffect** [comment]
@janvanderhaegen It sounds like the compiler you are using is out of date and not compliant with the latest ES6 spec. Please update the version of Babel used on the validation library, fix all errors and do another release.

**Comment by janvanderhaegen** [comment]
Will check the versions used.
Not sure if re-release is needed (problem reported is when building the code, not when using the library). Either way, new release is coming this weekend anyways and will make sure this issue is resolved.

**Comment by janvanderhaegen** [comment]
Updated everything in a clean workspace and got the same error.
Moved offending callbacks to a static method and it works (https://github.com/aurelia/validation/commit/eb07bff6a016a40e0cdff9cd00d7328eacce886c).  IMHO this is a bug in the latest compiler, not in our code ;-)
