### ISSUE TITLE
Better error message when returning the response instead of the response.content in onValidate

### ISSUE THREAD

**Issue by Aaike** [aurelia/validation#75]
When doing
```
 .onValidate( () => {
        return this.http.post(...).then(response => {
            return response;
          });
      });
```

it seems harmless but it should of course return the response.content.
The only error at that point is an unhandled Promise error.

maybe it can detect if the value return is a `HttpResponseMessage` and say something more useful
or it can actually try to use the `.content` property automatically.

no proirity at all, just making note of it, will try to add it if i get some time.
unless you do it first of course @janvanderhaegen ;)

**Comment by janvanderhaegen** [comment]
:-)
Have a lot of time for our precious library this weekend. Will try to beat you to it :D
