### ISSUE TITLE
Loading the plugin generate errors when templates separated from js

### ISSUE THREAD

**Issue by KE-Cbu** [aurelia/validation#81]
hi, we separate templates from js in two directories with ConventionalViewStrategy.convertModuleIdToViewUrl and when I'm trying to load the validation
module I get error 500 on components in the console : 
> INFO [aurelia] Aurelia Starting
> index.js:38 DEBUG [aurelia] Loading plugin github:aurelia/templating-binding@0.13.0.
> index.js:38 DEBUG [aurelia] Configured plugin github:aurelia/templating-binding@0.13.0.
> index.js:38 DEBUG [aurelia] Loading plugin github:aurelia/templating-resources@0.13.0.
> index.js:38 DEBUG [aurelia] Configured plugin github:aurelia/templating-resources@0.13.0.
> index.js:38 DEBUG [aurelia] Loading plugin github:aurelia/history-browser@0.6.0.
> index.js:38 DEBUG [aurelia] Configured plugin github:aurelia/history-browser@0.6.0.
> index.js:38 DEBUG [aurelia] Loading plugin github:aurelia/templating-router@0.14.0.
> index.js:38 DEBUG [aurelia] Configured plugin github:aurelia/templating-router@0.14.0.
> index.js:38 DEBUG [aurelia] Loading plugin github:aurelia/event-aggregator@0.6.0.
> index.js:38 DEBUG [aurelia] Configured plugin github:aurelia/event-aggregator@0.6.0.
> index.js:38 DEBUG [aurelia] Loading plugin aurelia-validation.
> index.js:38 DEBUG [aurelia] Configured plugin aurelia-validation.
> main.js:15 github:aurelia/templating-resources@0.13.0/compose
> main.js:15 github:aurelia/templating-resources@0.13.0/if
> main.js:15 github:aurelia/templating-resources@0.13.0/with
> main.js:15 github:aurelia/templating-resources@0.13.0/repeat
> main.js:15 github:aurelia/templating-resources@0.13.0/show
> main.js:15 github:aurelia/templating-resources@0.13.0/replaceable
> main.js:15 github:aurelia/templating-resources@0.13.0/global-behavior
> main.js:15 github:aurelia/templating-resources@0.13.0/focus
> main.js:15 github:aurelia/templating-router@0.14.0/router-view
> main.js:15 github:aurelia/templating-router@0.14.0/route-href
> index.js:96 GET http://localhost:34222/aureliaview/github:aurelia/templating-resources@0.13.0/compose 500 (Internal Server Error)
> index.js:96 GET http://localhost:34222/aureliaview/github:aurelia/templating-resources@0.13.0/if 500 (Internal Server Error)
> index.js:96 GET http://localhost:34222/aureliaview/github:aurelia/templating-resources@0.13.0/repeat 500 (Internal Server Error)
> index.js:96 GET http://localhost:34222/aureliaview/github:aurelia/templating-resources@0.13.0/with 500 (Internal Server Error)
> index.js:96 GET http://localhost:34222/aureliaview/github:aurelia/templating-resources@0.13.0/show 500 (Internal Server Error)
> index.js:96 GET http://localhost:34222/aureliaview/github:aurelia/templating-resources@0.13.0/replaceable 500 (Internal Server Error)
> index.js:96 GET http://localhost:34222/aureliaview/github:aurelia/templating-resources@0.13.0/global-behavior 500 (Internal Server Error)
> index.js:96 GET http://localhost:34222/aureliaview/github:aurelia/templating-resources@0.13.0/focus 500 (Internal Server Error)
> index.js:96 GET http://localhost:34222/aureliaview/github:aurelia/templating-router@0.14.0/router-view 500 (Internal Server Error)
> index.js:96 GET http://localhost:34222/aureliaview/github:aurelia/templating-router@0.14.0/route-href 500 (Internal Server Error)

Any idea ?
Thanks

**Comment by janvanderhaegen** [comment]
Hey,

could you jspm to the latest aurelia-validation? We just upgraded our dependencies, which might fix this.

**Comment by KE-Cbu** [comment]
it works.. Thanks for the fix
