### ISSUE TITLE
Add d.ts generation

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia/validation#86]
Other aurelia repositories export their own d.ts file by using the babel-dts-generator plugin.

It would be great if the validation repository could do the same.

**Comment by janvanderhaegen** [comment]
Going to see if I can get help on this from the team!!

**Comment by Martin-Andersen** [comment]
Yes please add the d.ts file, typescript is a must.

**Comment by alexmills** [comment]
Any updates on whether the next release will include the d.ts file? :)

**Comment by JeroenVinke** [comment]
@janvanderhaegen are you willing to accept PR's for this?

**Comment by janvanderhaegen** [comment]
Willing to accept PR's for anything helpful!

**Comment by nomack84** [comment]
@janvanderhaegen Here you have it #122

**Comment by PWKad** [comment]
Closing as a duplicate of many others, first was #4 

Contributions still needed on this just trying to help triage the issues by narrowing down the open ones

Duplicate of #4
