### ISSUE TITLE
Aurelia-Validation in NPM package for node

### ISSUE THREAD

**Issue by Apcio** [aurelia/validation#87]
I found NPM package aurelia-validation:
https://www.npmjs.com/package/aurelia-validation

Does this plugin will be supported for Node.js, and working on server side ? 

This version is 0.1.0, and for Aurelia  framework there is 0.2.7 version.

**Comment by Apcio** [comment]
Does this plugin work with any schema validators ? Maybe you recommendend other library for validation on both server and client -side ?

Any RoadMap (further plans) for this plugin ?

**Comment by janvanderhaegen** [comment]
We're going to split aurelia-validation into a core validation library which works client&server side, and one that works client-side.
At that point I'll clean up the NPM package.

Schema validators are on the roadmap too, but we have a lot of high-prio work to do ;-)

**Comment by Apcio** [comment]
I'm happy now.
It that will happen, a lot of developers would have less work with validation.

It will be perfect, when I could create one module which contain a class validation. And on both sides I could used the same code. "One to rule them all" :)
