### ISSUE TITLE
Installation prevents latest skeleton app from working correctly.

### ISSUE THREAD

**Issue by shortly-portly** [aurelia/validation#91]
Downloaded and ran the latest skeleton app successfully (version 0.15.1).
jspm install aurelia-validation.
Ran the skeleton app but am now unable to select Welcome or Child Router tab.
I would expect to be able to select these two tabs with aurelia-validation installed.
Note: I have also followed the steps to configure aurelia-validation and at each step attempted to run the skeleton-app - get the same issue each time.
I cannot see anything in either the client console or the node console to indicate any problems.

**Comment by EisenbergEffect** [comment]
Did it run before you installed the validation library?

**Comment by shortly-portly** [comment]
Hi. Yes it ran fine. At first I assumed I'd made some kind of mistake in my code but I ran from a clean install and still got the same problem.

**Comment by EisenbergEffect** [comment]
@janvanderhaegen Seems there's an issue with the validation library. Can you look into this please?

**Comment by wshayes** [comment]
Could be an issue with jspm -- what version of jspm are you using @shortly-portly?

**Comment by shortly-portly** [comment]
I've done a little more digging and the culprit appears to be the submit.delegate="submit()" on welcome.html. Remove this and the welcome page display fine. Hope this helps.

**Comment by shortly-portly** [comment]
Bit more info: If I do a clean install of the skeleton followed by an install of validation using the jspm --lock option then it works.

**Comment by shortly-portly** [comment]
Hi Rob - just out of interest - has this been fixed or am I doing something wrong?

**Comment by EisenbergEffect** [comment]
It sounds like there's a version conflict with the validation library. @janvanderhaegen Can you comment on this? We've seen a number of issues similar to this with the validation library? How can we address this?

**Comment by janvanderhaegen** [comment]
@EisenbergEffect  @shortly-portly Let me update the versions again & republish.
