### ISSUE TITLE
Bundle minification causes I18N error

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia/validation#92]
I have noticed that when I minify my bundle (`jspm bundle -i -m * + */**`) some validation messages won't appear, and an error is thrown:

```
Unexpected behavior: a validation-rules-collection should always fulfil validation: I18N: Could not find: r in category: messages
build.js:19 Unhandled promise rejection Error: Unexpected behavior: a validation-rules-collection should always fulfil
    at Error (native)
    at http://domain.com/build.js:27:14515
    at n (http://domain.com/build.js:19:24869)
    at http://domain.com/build.js:19:25030
    at t.exports (http://domain.com/build.js:19:8329)
    at _.(anonymous function) (http://domain.com/build.js:19:27829)
    at Number.r (http://domain.com/build.js:19:27505)
    at i (http://domain.com/build.js:19:27526)
```

I have tried to change localization from nl-NL to en-US but this does not fix the problem.  Also, .required() is working fine, but the above error is thrown when I use `.isNumber()` or `.isEmail()`. there could be more validation rules causing errors.. All is well when I disable minification.

I have been able to reproduce this using the skeleton and latest version of aurelia-validation.  [Imgur](http://i.imgur.com/I7g0uo0.png). Repository is here: https://github.com/JeroenVinke/validation-error, minified bundle is here: https://github.com/JeroenVinke/validation-error/blob/master/dist/build.js

Not sure yet if this is caused by using the beta of JSPM, will investigate further..

**Comment by JeroenVinke** [comment]
I'm also getting this with jspm 0.15.6

**Comment by JeroenVinke** [comment]
I think I know why this is happening.. this is the minified validation-locale code:

```
o = function() {
				function e(t, r, i) {
					n(this, e), this.onValidate = r, this.threshold = t, this.message = i, this.errorMessage = null, __this.ruleName = this.constructor.name__
				}
				return e.prototype.withMessage = function(e) {
					this.message = e
				}, e.prototype.explain = function() {
					return this.errorMessage
				}, e.prototype.setResult = function(e, t, n) {
					if (e === !0 || void 0 === e || null === e || "" === e) return this.errorMessage = null, !0;
					if ("string" == typeof e) this.errorMessage = e;
					else if (this.message) if ("function" == typeof this.message) this.errorMessage = this.message(t, this.threshold);
					else {
						if ("string" != typeof this.message) throw "Unable to handle the error message:" + this.message;
						this.errorMessage = this.message
					} else this.errorMessage = n.translate(this.ruleName, t, this.threshold);
					return !1
				},
```

The name of the validation rule constructor is minified by renaming it to 'e'. The translation key is the same as the name of the constructor:
` this.ruleName = this.constructor.name; // minified constructor name is 'e'`
`n.translate(this.ruleName, t, this.threshold);`

This is probably why I18N is queried for the key 'e' instead of 'EmailValidationRule'. 

isRequired() is working because it is used differently: `message: this.isRequiredMessage ? "function" == typeof this.isRequiredMessage ? this.isRequiredMessage(e) : this.isRequiredMessage : t.translate("isRequired"),`

**Comment by EisenbergEffect** [comment]
@janvanderhaegen Yep, this is definitely a bug. Make sure not to use the name property of the function object anywhere in your code except in developer-oriented error messages. It will not be preserved when code is minified.
