### ISSUE TITLE
Adding a new language

### ISSUE THREAD

**Issue by dpinart** [aurelia/validation#97]
Hi I'd like to add a new language so I've created a ca-es.js file. How can I configure the plugin to use the new language?

**Comment by jadrake75** [comment]
I am assuming you read the instructions here? https://github.com/aurelia/validation/blob/master/doc/Intro.md#i18n

**Comment by dpinart** [comment]
Yes, I did but... must I add the new language language .js file into the jspm_packages/github/aurelia/validation@xx/resources? I mean, can I configure the language and the folder to find the language?

**Comment by janvanderhaegen** [comment]
Well you're right, there's only two ways to load a custom language that didn't come with the box:
a) place it where you unpacked the box (yes, the jspm_packages/..../resources) folder
b) contribute to github so it's now available for everyone

The latter would be much more appreciated than the former ;-)

**Comment by dpinart** [comment]
Oopps, sure I can conttribute with my mother language... Sorry I'm not very introduced in guthub but I will
